{
  "hash": "d1d495f9c3568b2ba29972351b9c1349",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlang: es\ndate-modified: '2026-03-12'\ntitle: La exploración de los datos mediante gráficos.\nabstract-title: Últimos cambios\nabstract: Reorganización del capítulo. Nueva sección sobre la forma de los datos. Ejemplos actualizados con datasets penguins, La Liga y temperatura de Oviedo.\nformat:\n  html:\n    code-fold: true\n    code-summary: Mostrar código\nengine: knitr\n---\n\n\n\n::: callout-note\n## Objetivos de aprendizaje\n\nAl finalizar este capítulo, el alumno será capaz de:\n\n- Construir e interpretar un diagrama de tallo y hojas (stemplot) a partir de un conjunto de datos pequeño, tanto manualmente como con Python y R.\n- Elaborar tablas de distribución de frecuencias con frecuencias absolutas, relativas y acumuladas en Excel, Python y R.\n- Crear e interpretar diagramas de barras para variables discretas en Excel.\n- Construir histogramas para variables continuas en Excel, Python y R, y seleccionar la amplitud de intervalo adecuada según el conjunto de datos.\n- Identificar e interpretar la forma de una distribución de datos (simétrica, asimétrica, bimodal) a partir de un histograma.\n- Describir la distribución de un conjunto de datos mediante el diagrama de caja (boxplot), identificando la mediana, los cuartiles, el rango intercuartil y los valores atípicos (outliers), y relacionar la forma del boxplot con la forma de la distribución.\n- Utilizar alternativas al boxplot (beeswarm, stripplot, violin plot) para visualizar distribuciones con mayor detalle.\n- Construir gráficos de densidad con Python y R y utilizarlos para comparar distribuciones entre grupos.\n- Crear e interpretar gráficos de dispersión para analizar relaciones entre dos variables numéricas, tanto en Excel como en Python y R.\n- Construir gráficos de series temporales e identificar tendencias, estacionalidad y anomalías, utilizando las funciones de remuestreo y ventanas móviles de pandas en Python y los equivalentes en R.\n- Elegir el tipo de gráfico más adecuado según el objetivo del análisis y el tipo de variable.\n\nLos conceptos clave introducidos en este capítulo son: **stemplot, distribución de frecuencias, frecuencia absoluta, frecuencia relativa, frecuencia acumulada, diagrama de barras, histograma, intervalo (bin), forma de los datos, distribución simétrica, distribución asimétrica, distribución bimodal, diagrama de caja (boxplot), cuartil, mediana, rango intercuartil (IQR), valor atípico (outlier), beeswarm, violin plot, gráfico de densidad, gráfico de dispersión, correlación, serie temporal, estacionalidad, tendencia, remuestreo, media móvil, matplotlib, seaborn, ggplot2, pandas**.\n:::\n\nUna imagen vale más que mil palabras, y en el análisis de datos, la visualización es fundamental para entender patrones, distribuciones y relaciones en nuestros datos.\n\nEn este capítulo estudiaremos cómo describir conjuntos de datos de forma visual, utilizando varios tipos de gráficos distintos:\n\n-   *Stemplot*\n-   Histograma\n-   Diagrama de caja o *boxplot*\n-   Gráfico de dispersión\n-   Gráfico de series temporales\n\nVeremos la relación visual entre un histograma y un diagrama de caja, y aprenderemos también a construir tablas de frecuencias en Excel, en Python y en R. Finalmente, veremos algunos otros tipos de gráficos que son útiles para aplicaciones concretas, como los gráficos de densidad.\n\n::: {.callout-note}\n## Librerías necesarias en este capítulo\n\nA lo largo de este capítulo se utilizan las siguientes librerías: \n\n- Python: `pip install palmerpenguins`\n- R: `install.packages(c(\"palmerpenguins\", \"ggbeeswarm\", \"patchwork\"))`\n\nLa mayoría forman parte de una instalación estándar de Python o R; `palmerpenguins`, `ggbeeswarm` y `patchwork` deben instalarse la primera vez.\n:::\n\n## El diagrama de tallo y hojas (*stem and leaf plot* o *stemplot*)\n\nEl diagrama de tallo y hojas, también conocido como *stemplot*, es una herramienta gráfica utilizada en estadística para representar la distribución de un conjunto de datos. Es especialmente útil para conjuntos de datos pequeños y proporciona una forma rápida y efectiva de visualizar la forma de los datos y su dispersión. El *stemplot* recibe este nombre porque el dibujo que resulta se asemeja a un tallo el que le salen las hojas que son los datos individuales.\n\nLos componentes de un *stemplot* son:\n\n-   **Tallo**: Representa el grupo principal de los valores de los datos. Generalmente, se usa la parte más significativa del número. Por ejemplo, en el número 43, el tallo podría ser 4.\n\n-   **Hojas**: Representan los dígitos finales o menos significativos de los valores de los datos. Siguiendo el ejemplo anterior, la hoja sería 3.\n\n#### Construcción del diagrama en la hoja de cálculo\n\nSupongamos que queremos medir la altura de un grupo de alumnos de nuestra clase. Éste es nuestro grupo:\n\n![](imagenes/grupo1.jpg)\n\nRealizamos la medida de altura de cada persona y registramos los valores en una hoja de cálculo, siguiendo las buenas prácticas que hemos visto al estudiar los *datos ordenados*.\n\n![](imagenes/aula1.webp)\n\nVamos a utilizar los datos de medidas de altura de nuestro grupo de alumnos. Quitamos el último dígito a la derecha de nuestros valores y colocamos verticalmente los valores resultantes ordenándolos de menor a mayor, y evitando las repeticiones. Para evitar errores en la escala, debemos incluir los valores intermedios aunque no haya ninguno en nuestros datos (en el ejemplo, el valor 16 que correspondería a los 160). Esto forma el \"tallo\" de nuestro diagrama:\n\n![](imagenes/aula1-stemplot-paso1.webp)\n\nA continuación añadimos las \"hojas\" en la celda a la derecha, que consisten en los valores que hemos \"cortado\" de nuestro árbol, uno al lado de otro, incluyendo esta vez los valores repetidos, en orden de menor a mayor. Por ejemplo, para el valor 135, descartamos 13 y utlizamos 5; para el valor 138, descartamos 13 y utilizamos 8, y así sucesivamente para todos los valores.\n\n![](imagenes/aula1-stemplot-paso2.webp)\n\n#### Construcción del diagrama en Python y R\n\nR permite realizar el *stemplot* mediante la función $stem()$ de forma automática. Python no incluye entre sus métodos básicos una función para hacer un *stemplot*, aunque sí la tiene en la librería `stemgraphic`; importamos de esta librería sólo la función `stem_text()`\n\n::: {#clr-instrucciones .callout-tip .content-visible when-format=\"html\"}\n## Importante: Explicación del código\n\nEn este capítulo veremos varios ejemplos de código R y Python.\n\nPara un explicación detallada del código, copia el código R o Python y pégalo en Gemini o en ChatGPT (o Copilot). A continuación. da esta instrucción a la IA (puedes copiar y pegar el párrafo):\n\n> Actúa como un tutor de programación. Explica este código instrucción a instrucción de forma detallada y sencilla, indicando qué hace cada línea y por qué es necesaria. Usa analogías con Excel o tareas manuales para que sea más fácil de entender.\n:::\n\n::: {.panel-tabset group=\"idiomas\"}\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom stemgraphic.text import stem_text\n\naltura_cm = [153,135,140,140,175,138,145,154,152,159,154]\nstem_text(altura_cm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n135\n    ¡\n 13 | 58\n    | \n 14 | 005\n    | \n 15 | 23449\n    | \n 16 |\n    | \n 17 | \n    | 5\n    !\n175\nKey: \n17|5 => 17.5x10 = 175.0 \n```\n\n\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\naltura_cm <- c(153,135,140,140,175,138,145,154,152,159,154)\nstem(altura_cm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  13 | 58\n  14 | 005\n  15 | 23449\n  16 | \n  17 | 5\n```\n\n\n:::\n:::\n\n:::\n\n### Interpretación del diagrama de tallo y hojas\n\n-   **Tallo**: Los números a la izquierda del símbolo `|` representan los valores base (o tallos), en este caso, las decenas de las alturas.\n-   **Hojas**: Los números a la derecha del símbolo `|` representan los dígitos adicionales (o hojas). Por ejemplo, en la línea `13 | 58`, el tallo es `13` (130), y las hojas son `5` y `8`, que corresponden a los datos `135` y `138`.\n\nEl diagrama nos dice que los valores en torno a 150 cm son los más frecuentes, y que hay un valor alto (175) que se separa un poco del resto.\n\n### Resumen\n\nEl *stemplot* es muy sencillo de hacer y nos da una visión rápida y compacta de la *distribución* de nuestros valores, así como de la posible existencia de valores que se separan del conjunto. Estos valores alejados, que se conocen en inglés como *outliers*, tienen mucha importancia en el analisis e interpretación de los datos, como veremos más adelante.\n\nLa ventaja principal del *stemplot* es que mantiene los valores originales de las observaciones, y puede hacerse fácilmente con bolígrafo y papel, sin necesidad de más herramientas.\n\nSu principal inconveniente es la elaboración manual (aunque lenguajes como R tienen funciones que lo contruyen de forma automática), y por lo tanto, la dificultad de aplicarlo a volumenes de datos medios o grandes. El uso generalizado de los ordenadores ha hecho que actualmente esta herramienta tenga muy poco uso, y se utilicen en su lugar otras más gráficas y de construcción automática, como el **histograma**.\n\n## Distribuciones de frecuencias\n\nUna **distribución de frecuencias** es una tabla que muestra la frecuencia con la que ocurren los valores diferentes en un conjunto de datos. Esta herramienta es fundamental en la estadística descriptiva y permite resumir y visualizar cómo se distribuyen los datos de manera clara y comprensible. A partir de una tabla de frecuencias se pueden construir diagramas de barra o histogramas para visualizar la tabla de forma gráfica.\n\nPara construir una distribución de frecuencias, agrupamos nuestros valores por intervalos, y contamos el número de observaciones que aparecen en cada intervalo. Los componentes de una distribución de frecuencias son:\n\n-   las **categorías o clases** son los intervalos o valores específicos de los datos que se están analizando. Cada categoría representa un rango de valores en caso de datos continuos, o valores específicos en caso de datos discretos.\n-   la **frecuencia absoluta** es un *recuento simple* de cuántas veces aparece cada valor en un conjunto de datos.\n-   la **frecuencia relativa** nos muestra la *proporción* de cada valor frente al total. Puede expresarse como fracción (entre 0 y 1) o como porcentaje (respecto a 100), y se calcula como: $$\n     \\text{Frecuencia Relativa} = \\frac{\\text{Frecuencia Absoluta}}{\\text{Número Total de Observaciones}}\n     $$\n-   la **frecuencia acumulada** nos dice cuántas observaciones están por debajo de un cierto valor.\n-   la **frecuencia relativa acumulada** es la proporción de valores que están por debajo de un cierto valor\n\n### Construcción de una tabla de frecuencias paso a paso en Excel\n\nPara crear una tabla de frecuencias de la variable `altura_cm` mediante una tabla dinámica en Excel, sigue estos pasos:\n\n**1. Selecciona los Datos**\n\n1.  Abre tu archivo de Excel y selecciona toda la tabla que incluye los encabezados (`nombre` y `altura_cm`).\n\n**2. Inserta una tabla dinámica**\n\n1.  Ve a la pestaña **Insertar** en la barra de herramientas de Excel.\n2.  Haz clic en **Tabla Dinámica**.\n3.  En el cuadro de diálogo que aparece, asegúrate de que el rango de datos seleccionado es correcto y elige dónde deseas colocar la tabla dinámica (en una nueva hoja de cálculo o en la hoja actual).\n\n**3. Añade la frecuencia absoluta**\n\n1.  En el panel de campos de la tabla dinámica, arrastra el campo `altura_cm` a la sección **Filas**.\n2.  Arrastra nuevamente el campo `altura_cm` a la sección **Valores**.\n\n**4. Ajusta la configuración de valores**\n\n1.  Haz clic en el campo `altura_cm` en la sección **Valores**.\n2.  Selecciona **Configuración de campo de valor**.\n3.  En el cuadro de diálogo que aparece, asegúrate de que esté seleccionada la opción **Recuento**\n4.  Acepta todo hasta volver a Excel.\n\n**5. Añade la frecuencia relativa**\n\n1.  En el panel de campos de la tabla dinámica, arrastra de nuevo el campo `altura_cm` a la sección **Valores**. Ahora la variable aparecerá como `altura_cm2`.\n\n**6. Ajusta de nuevo la configuración de valores**\n\n1.  Haz clic en el campo `altura_cm2` en la sección **Valores**.\n2.  Selecciona **Configuración de campo de valor**.\n3.  En el cuadro de diálogo que aparece, asegúrate de que esté seleccionada la opción **Recuento**.\n4.  En ese mismo cuadro, haz click en el botón **Formato de número**, selecciona **Número** y **2 decimales**, y acepta.\n5.  En ese mismo cuadro, selecciona la pestaña que dice **Mostrar valores como**\n6.  En el menú desplegable, escoge la opción **% del total de columnas**.\n7.  Acepta todo hasta volver a Excel.\n\n**7. Ordena y formatea**\n\n1.  Puedes ordenar las alturas en orden ascendente o descendente haciendo clic en la flecha junto a `altura_cm` en la tabla dinámica.\n2.  También puedes cambiar el formato de la tabla dinámica para que sea más fácil de leer.\n3.  Puedes renombrar los encabezados de la tabla para que sea más fácil de leer, rotulando las columnas, por ejemplo, como `frec_abs`y `frec_rel`, o cualquier otro encabezado que te resulte claro y útil.\n\n![](imagenes/aula1-td-frec.webp)\n\n### Construcción de una tabla de frecuencias mediante Python o R\n\n::: {.panel-tabset group=\"idiomas\"}\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\n\naltura_cm = [153,135,140,140,175,138,145,154,152,159,154]\nfrecuencias = pd.Series(altura_cm).value_counts()\nprint(frecuencias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n140    2\n154    2\n153    1\n175    1\n135    1\n138    1\n145    1\n152    1\n159    1\nName: count, dtype: int64\n```\n\n\n:::\n:::\n\n\n## R base\n\n\n::: {.cell}\n\n```{.r .cell-code}\naltura_cm <- c(153, 135, 140, 140, 175, 138, 145, 154, 152, 159, 154)\nfrecuencias <- table(altura_cm)\nprint(frecuencias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\naltura_cm\n135 138 140 145 152 153 154 159 175 \n  1   1   2   1   1   1   2   1   1 \n```\n\n\n:::\n:::\n\n\n## R con dplyr\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\ndf_alturas <- tibble(\n  altura = c(153, 135, 140, 140, 175, 138, 145, 154, 152, 159, 154)\n)\nfrecuencias <- df_alturas |>\n  count(altura, sort = TRUE, name = \"frecuencia\")\nprint(frecuencias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 2\n  altura frecuencia\n   <dbl>      <int>\n1    140          2\n2    154          2\n3    135          1\n4    138          1\n5    145          1\n6    152          1\n7    153          1\n8    159          1\n9    175          1\n```\n\n\n:::\n:::\n\n:::\n\nCon un poco más de código podemos hacer la tabla agrupando los valores en clases de amplitud 10, con las frecuencias absolutas y relativas. Es un poco más complicado, tómate tu tiempo para entender cada paso de las instrucciones.\n\n::: {.panel-tabset group=\"idiomas\"}\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport numpy as np\n\naltura_cm = [153,135,140,140,175,138,145,154,152,159,154]\nserie = pd.Series(altura_cm)\n\n# Crear intervalos automáticamente con amplitud 10\nbins = np.arange(min(altura_cm)//10*10, \n                 max(altura_cm)//10*10 + 20, 10)\n\n# Agrupar y contar\ntabla = pd.cut(serie, bins=bins).value_counts(sort=False)\n\n# Convertir a DataFrame con acumulados y relativos\ndf = tabla.to_frame(name='Frecuencia')\ndf['Frec_acum_%'] = df['Frecuencia'].cumsum()\n\n# escribimos la instrucción en dos lineas usando los paréntesis\ndf['Frec_rel_%'] = (\n  (df['Frecuencia'] / df['Frecuencia'].sum() * 100).round(2)\n)\ndf['Frec_rel_acum_%'] = df['Frec_rel_%'].cumsum()\n\nprint(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Frecuencia  Frec_acum_%  Frec_rel_%  Frec_rel_acum_%\n(130, 140]           4            4       36.36            36.36\n(140, 150]           1            5        9.09            45.45\n(150, 160]           5           10       45.45            90.90\n(160, 170]           0           10        0.00            90.90\n(170, 180]           1           11        9.09            99.99\n```\n\n\n:::\n:::\n\n\n## R base\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Definir los datos\naltura_cm <- c(153, 135, 140, 140, 175, 138, 145, 154, 152, 159, 154)\n\n# 2. Crear los cortes (bins) como en NumPy\nlimite_inf <- floor(min(altura_cm) / 10) * 10\nlimite_sup <- floor(max(altura_cm) / 10) * 10 + 10\n\nbins <- seq(limite_inf, limite_sup + 10, by = 10)\n\n# 3. Agrupar los datos en los intervalos\nintervalos <- cut(altura_cm, breaks = bins, right = FALSE)\n\n# 4. Crear la tabla de frecuencias\nfrecuencia <- as.vector(table(intervalos))\nnombres_intervalos <- levels(intervalos)\n\n# 5. Construir el data.frame con los cálculos\ndf <- data.frame(\n  Intervalo = nombres_intervalos,\n  Frecuencia = frecuencia\n)\n\n# Cálculos de acumulados y relativos\ndf$Frec_acum <- cumsum(df$Frecuencia)\ndf$Frec_rel_pct <- round((df$Frecuencia / sum(df$Frecuencia)) * 100, 2)\ndf$Frec_rel_acum_pct <- cumsum(df$Frec_rel_pct)\n\nprint(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Intervalo Frecuencia Frec_acum Frec_rel_pct Frec_rel_acum_pct\n1 [130,140)          2         2        18.18             18.18\n2 [140,150)          3         5        27.27             45.45\n3 [150,160)          5        10        45.45             90.90\n4 [160,170)          0        10         0.00             90.90\n5 [170,180)          1        11         9.09             99.99\n6 [180,190)          0        11         0.00             99.99\n```\n\n\n:::\n:::\n\n\n## R con dplyr\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\naltura_cm <- c(153, 135, 140, 140, 175, 138, 145, 154, 152, 159, 154)\n\nbins <- seq(\n  from = floor(min(altura_cm) / 10) * 10,\n  to   = floor(max(altura_cm) / 10) * 10 + 20,\n  by   = 10\n)\n\ntabla_frecuencias <- tibble(altura = altura_cm) |>\n  mutate(\n    intervalo = cut(altura, breaks = bins, right = FALSE)\n  ) |>\n  count(intervalo, name = \"Frecuencia\", .drop=FALSE) |>\n  mutate(\n    Frec_acum_pct= cumsum(Frecuencia),\n    Frec_rel_pct = round((Frecuencia / sum(Frecuencia)) * 100, 2),\n    Frec_rel_acum_pct = cumsum(Frec_rel_pct)\n  )\n\nprint(tabla_frecuencias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  intervalo Frecuencia Frec_acum_pct Frec_rel_pct Frec_rel_acum_pct\n  <fct>          <int>         <int>        <dbl>             <dbl>\n1 [130,140)          2             2        18.2               18.2\n2 [140,150)          3             5        27.3               45.4\n3 [150,160)          5            10        45.4               90.9\n4 [160,170)          0            10         0                 90.9\n5 [170,180)          1            11         9.09             100.0\n6 [180,190)          0            11         0                100.0\n```\n\n\n:::\n:::\n\n:::\n\nComo ves en el resultado, a veces se utilizan los símbolos `(` y `[` para definir los intervalos, tal como se hace en matemáticas.\n\n-   Intervalo **abierto**: El símbolo `(` se utiliza para denotar un intervalo abierto. El límite correspondiente **no** está incluido en el intervalo.\n-   Intervalo **cerrado o semiabierto**: El símbolo `[` se utiliza para denotar un intervalo cerrado o semiabierto. El límite correspondiente **sí** está incluido en el intervalo.\n\nEjemplos:\n\n-   $(a, b)$ representa todos los números reales **mayores** que $a$ y **menores** que $b$ (excluye los valores $a$ y $b$).\n-   $[a, b]$ representa todos los números reales **mayores o iguales** que $a$ y **menores o iguales** que $b$ (incluye $a$ y $b$).\n-   $[a, b)$ representa todos los números reales **mayores o iguales** que $a$ y **menores** que $b$ (incluye $a$, pero excluye $b$)\n-   $(a, b]$ representa todos los números reales **mayores** que $a$ y **menores o iguales** que $b$ (excluye $a$, pero incluye $b$).\n\nSi comparamos los dos métodos que hemos utilizado para construir la tabla de frecuencias, vemos que:\n\n-   en Excel los pasos que hemos dado no están registrados y a la vista, y, por lo tanto, no son fácilmente revisables\n-   en Python y R, todos los pasos y opciones que hemos utilizado están a la vista en el código del script\n\nSi otra persona quisiera modificar la tabla, le sería fácil editar el código y relanzar el script, mientras que en Excel no sería fácil asegurarse de todos y cada uno de los pasos y clicks de ratón que hemos dado para construir y formatear la tabla.\n\nEsta es una de las principales razones de la conveniencia del aprendizaje de `Python` incluso para las actividades más sencillas.\n\n### Ejercicio propuesto\n\nEn la tabla de frecuencias anterior, calcular **frecuencia absoluta acumulada** y **frecuencia relativa acumulada** en Excel, e incluirlas en la tabla como dos columnas adicionales. La **frecuencia relativa acumulada** nos permitirá crear **diagramas de Pareto**, muy útiles en los procesos de mejora de calidad.\n\n## Diagrama de barras\n\nCuando nuestra variable es *discreta*, podemos representar las frecuencias de cada valor de forma gráfica utilizando un diagrama de barras. Este diagrama utiliza barras rectangulares para representar la frecuencia de cada categoría.\n\nEste gráfico es muy utilizado para representar, por ejemplo, resultados de encuestas, como el número de votos que han obtenido los diferentes partidos políticos en unas elecciones, o tablas discretas, como los kilos fabricados por meses en una fábrica.\n\n::: {layout-ncol=\"2\"}\n![](imagenes/2024-12-07-excel-tabla-frec-1.webp){width=\"300\"}\n\n![](imagenes/barras1.webp){width=\"300\"}\n\n![](imagenes/2024-12-07-excel-tabla-frec-2.webp){width=\"300\"}\n\n![](imagenes/barras2.webp){width=\"300\"}\n:::\n\n## Histograma\n\nPara visualizar las variables continuas se utiliza el **histograma**, que es un diagrama que utiliza las barras rectangulares para hacer un gráfico de la distribución de valores continuos, previamente agrupados en intervalos (*bins* en inglés), tal como se ha hecho en la tabla de frecuencias.\n\n#### Componentes de un histograma\n\n1.  **Eje horizontal (X)**: Representa los intervalos de valores de la variable. Cada intervalo abarca un rango específico de valores.\n2.  **Eje vertical (Y)**: Muestra la frecuencia o el número de veces que los valores caen dentro de cada intervalo.\n3.  **Barras**: Cada barra en el histograma representa un intervalo. La altura de la barra indica la frecuencia de los valores dentro de ese intervalo.\n\n#### Cómo interpretar un histograma\n\n-   Si las barras son altas en un intervalo específico, significa que muchos valores del conjunto de datos caen dentro de ese rango.\n-   Un histograma puede ayudar a identificar patrones, como si los datos están distribuidos de manera simétrica, sesgada, o si hay picos y valles significativos.\n\n### Construcción de un histograma en Excel\n\nUsaremos el ejemplo de la altura en cm. de un grupo de alumnos.\n\nPodemos utilizar dos métodos para hacer un histograma en Excel\n\n#### Método 1: histograma directo\n\n-   Seleccionamos el rango de datos. Podemos hacerlo mediante un click en el encabezado de la columna de la variable `altura_cm`, en este caso, la columna `B`.\n-   En la opción de menú `Insertar`, seleccionamos el icono `Seleccionar gráficos de estadística`\n-   Seleccionamos `Histograma`\n\n![](imagenes/excel-histo-aula1.webp){fig-align=\"center\" width=\"75%\"}\n\nExcel calcula automáticamente la amplitud de los intervalos y el número de columnas; estas opciones pueden modificarse seleccionando con el botón derecho del ratón el elemento a modificar. En este caso, utilizamos estas opciones:\n\n-   Eliminamos título del gráfico\n-   Modificamos anchura de las barras seleccionando `Dar formato a serie de datos`, `Opciones de serie`, `Ancho del rango`= 50%\n-   Modificamos los intervalos seleccionando el eje X: `Dar formato al eje`, `Opciones de eje`, `Ancho del rango` = 10\n\nLa descripción de los intervalos utiliza los mismos símbolos que hemos visto en las tablas de frecuencias de `Python`.\n\nEn el momento de escribir este manual, Excel no permite hacer histogramas múltiples ni agrupados por otra variable, por lo que para diseños más complejos, no hay más remedio que recurrir a otras opciones como las tablas dinámicas de Excel o, mejor aún, `Python` o `R`.\n\n#### Método 2: utilizar una tabla dinámica\n\nLa tabla dinámica que hemos construido en Excel ha convertido nuestra variable continua, `altura_cm`, en una tabla de valores discretos, al agrupar los valores en intervalos. En Excel podemos representar las frecuencias absolutas de nuestra tabla gráficamente, insertando un gráfico de barras a partir de la tabla:\n\n-   Con el cursor dentro de la tabla, seleccionamos la opción de menú `Insertar`\n-   Insertamos un gráfico de barras\n\nOpcionalmente, aplicamos las siguientes opciones de formato:\n\n-   Hacemos click sobre uno de los botones del gráfico dinámico con el boton derecho del ratón, y seleccionamos la opción ocultar todos los botones del gráfico.\n-   Eliminamos el título del gráfico\n-   Abrimos el formato de la serie de datos, e introducimos en la opción `Ancho del rango` el valor $50\\%$ para ensanchar las barras.\n\n![](imagenes/aula1-diag-barras.webp){fig-align=\"center\" width=\"75%\"}\n\nAl utiizar la tabla dinámica para construir el gráfico, Excel utiliza las categorías de la tabla dinámica. Dado que estas categorías (los intervalos que ha formado la tabla dinámica) son discretas, Excel utiliza el resultado de la tabla dinámica para hacer el gráfico con un diagrama de barras. No es posible insertar un histograma a partir de una tabla dinámica.\n\n### Histograma en Python y R\n\nEn Python, las librerías `matplotlib` y `seaborn` son las herramientas estándar para crear gráficos.\n\n-   **matplotlib.pyplot (alias `plt`):** Es la base, una librería de bajo nivel que da un control muy granular sobre cada aspecto del gráfico.\n-   **seaborn (alias `sns`):** Construye sobre `matplotlib`, ofreciendo una interfaz de alto nivel para crear gráficos estadísticos complejos y estéticamente agradables con menos código. Es ideal para explorar distribuciones, relaciones entre variables y comparaciones entre grupos.\n\nSiempre importamos ambas, ya que `seaborn` a menudo usa funciones de `matplotlib` para mostrar y personalizar los gráficos (como `plt.title()` para el título o `plt.show()` para mostrar el gráfico).\n\nEn **R**, usaremos las funciones de base y la librería `ggplot2`.\n\nLas funciones de histograma de Python y R permiten construir el histograma directamente sin necesidad de hacer previamente una tabla de frecuencias (en realidad, la tabla de frecuencias se calcula internamente). Es mucho más sencillo utilizar estas funciones, ya que el código se simplifica mucho.\n\nVemos que los gráficos no son idénticos a pesar de provenir de los mismos datos, porque la construcción de los intervalos subyacente y el aspecto de las barras pueden ser ligeramente diferentes. Esto no debe preocuparnos, porque el aspecto general de la distribución de los datos es el mismo.\n\nEn la fase de exploración nos importa más entender estas propiedades de los datos (aspecto, forma de la distribución) que la precisión en la construcción del gráfico.\n\nComenzamos con el histograma de nuestros datos de altura:\n\n::: panel-tabset\n## Python (con `matplotlib`)\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport matplotlib.pyplot as plt\n\naltura_cm = [153,135,140,140,175,138,145,154,152,159,154]\n\nplt.hist(altura_cm)\nplt.title(\"Distribución de la altura de los alumnos\")\nplt.xlabel(\"Altura (cm)\")\nplt.ylabel(\"Frecuencia\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## Python (con `seaborn`)\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\naltura_cm = [153,135,140,140,175,138,145,154,152,159,154]\ndf_altura = pd.DataFrame({'altura_cm': altura_cm})\n\nsns.histplot(df_altura['altura_cm'])\nplt.title(\"Distribución de la altura de los alumnos\")\nplt.xlabel(\"Altura (cm)\")\nplt.ylabel(\"Frecuencia\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n:::\n\n\n## R base\n\n\n::: {.cell}\n\n```{.r .cell-code}\naltura_cm <- c(153,135,140,140,175,138,145,154,152,159,154)\n\nhist(altura_cm,\n     main = \"Distribución de la altura de los alumnos\",\n     xlab = \"Altura (cm)\",\n     ylab = \"Frecuencia\")\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-12-5.png){width=672}\n:::\n:::\n\n\n## R (con `ggplot`)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\naltura_cm <- c(153,135,140,140,175,138,145,154,152,159,154)\ndf_altura <- data.frame(altura_cm = altura_cm)\n\nggplot(df_altura, aes(x = altura_cm)) +\n  geom_histogram(bins = 6) +\n  labs(\n    title = \"Distribución de la altura de los alumnos\",\n    x = \"Altura (cm)\",\n    y = \"Frecuencia\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n:::\n\nCon solo 11 observaciones el histograma es poco informativo. Cuando tenemos más datos, el histograma muestra con mucha más claridad la forma de la distribución. Usaremos a partir de ahora el dataset `penguins`, que contiene medidas de 344 pingüinos de tres especies del archipiélago Palmer (Antártida).\n\n::: {.callout-note}\nPara usar el dataset `penguins` es necesario instalar la librería correspondiente la primera vez:\n\n- En Python: `pip install palmerpenguins`\n- En R: `install.packages(\"palmerpenguins\")`\n:::\n\n::: panel-tabset\n## Python (con `matplotlib`)\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\npenguins['flipper_length_mm'].dropna().hist()\nplt.title(\"Distribución de la longitud de aleta\")\nplt.xlabel(\"Longitud de aleta (mm)\")\nplt.ylabel(\"Frecuencia\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n## Python (con `seaborn`)\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.histplot(penguins['flipper_length_mm'].dropna())\nplt.title(\"Distribución de la longitud de aleta\")\nplt.xlabel(\"Longitud de aleta (mm)\")\nplt.ylabel(\"Frecuencia\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-15-3.png){width=672}\n:::\n:::\n\n\n## R base\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\n\nhist(penguins$flipper_length_mm,\n     main = \"Distribución de la longitud de aleta\",\n     xlab = \"Longitud de aleta (mm)\",\n     ylab = \"Frecuencia\")\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-16-5.png){width=672}\n:::\n:::\n\n\n## R (con `ggplot`)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\n\nggplot(penguins, aes(x = flipper_length_mm)) +\n  geom_histogram(bins = 20) +\n  labs(\n    title = \"Distribución de la longitud de aleta\",\n    x = \"Longitud de aleta (mm)\",\n    y = \"Frecuencia\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n:::\n\nCon 344 observaciones el histograma muestra una forma mucho más clara. En la sección siguiente aprenderemos a interpretar esta forma.\n\n## La forma de los datos\n\n¿Por qué es importante conocer la forma de los datos? Porque la forma nos dice si los datos son homogéneos o si hay grupos distintos mezclados, y eso cambia completamente la interpretación. Imaginemos que medimos la altura de los alumnos de un aula y obtenemos el histograma que ya conocemos: una distribución centrada en torno a 150 cm, aproximadamente simétrica. Ahora imaginemos que en esa misma aula hay tres alumnos de 16 años mezclados con alumnos de 12 años: el histograma mostraría dos grupos claramente separados, y la forma nos estaría diciendo que no estamos ante una población homogénea sino ante dos grupos distintos. Si no miramos la forma y nos quedamos solo con un número resumen, perderíamos esa información fundamental.\n\nLo mismo ocurre en la industria: si mezclamos en una tabla de datos la producción de dos líneas con ajustes diferentes, o de dos turnos con operarios distintos, o de dos épocas del año con materias primas diferentes, el histograma nos lo mostrará. La forma de los datos es la primera señal de que algo merece una investigación más profunda, antes de hacer ningún cálculo. En el capítulo 8 veremos un caso real de fabricación de queso camembert en el que la forma de los datos nos dará la primera pista sobre una desviación estacional que solo se explica cuando analizamos los datos en el tiempo.\n\n### Distribución simétrica\n\nCuando la mayoría de los valores se concentran en el centro y las frecuencias disminuyen de forma equilibrada hacia ambos lados, decimos que la distribución es **simétrica**. Es el caso más frecuente en medidas de procesos industriales controlados: pesos, temperaturas, extractos secos. El histograma de la longitud de aleta de los pingüinos que acabamos de ver es un buen ejemplo de distribución aproximadamente simétrica.\n\nEsta forma recuerda a una campana, y es la que en estadística se conoce como **distribución normal** o **campana de Gauss**. Volveremos sobre este concepto en el capítulo 7, cuando estudiemos la media y la desviación típica.\n\n### Distribución asimétrica\n\nNo todas las distribuciones son simétricas. Cuando la mayoría de los valores se concentran en un extremo y la frecuencia disminuye lentamente hacia el otro, decimos que la distribución es **asimétrica**. Un ejemplo muy claro es la distribución de goles por partido en La Liga. El dataset `laliga_resultados2425.csv` contiene los resultados de los 380 partidos de la temporada 2024-25 de la Primera División de fútbol española, con el marcador de cada equipo al final del partido. Se ha elegido este conjunto de datos por su familiaridad para cualquier alumno español y porque la distribución de goles por partido es un ejemplo clásico de asimetría positiva: la mayoría de los partidos terminan con pocos goles, pero ocasionalmente aparecen resultados muy abultados que forman una cola hacia la derecha.\n\nLos resultados proceden de los registros oficiales de [LaLiga](https://www.laliga.com).\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\nlaliga = pd.read_csv(\"datos/laliga_resultados2425.csv\", sep=';')\nlaliga['goles_totales'] = laliga['goles_local'] + laliga['goles_visitante']\n\nsns.histplot(laliga['goles_totales'], bins=10, discrete=True)\nplt.xlabel(\"Goles por partido\")\nplt.ylabel(\"Número de partidos\")\nplt.title(\"Distribución de goles por partido. La Liga 2024-25\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlaliga <- read.csv2(\"datos/laliga_resultados2425.csv\")\nlaliga$goles_totales <- laliga$goles_local + laliga$goles_visitante\n\nhist(laliga$goles_totales,\n     breaks = 10,\n     main = \"Distribución de goles por partido. La Liga 2024-25\",\n     xlab = \"Goles por partido\",\n     ylab = \"Número de partidos\")\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-19-3.png){width=672}\n:::\n:::\n\n:::\n\nLa mayoría de los partidos terminan con pocos goles, y los partidos con muchos goles son cada vez más raros. La distribución tiene una cola larga hacia la derecha: esto es lo que se conoce como **asimetría positiva** o **sesgo positivo**. El valor más frecuente (la **moda**) es más bajo que el valor central, y hay algunos partidos con resultados muy abultados que forman esa cola. En la industria alimentaria encontraremos distribuciones asimétricas positivas con frecuencia en variables como los recuentos de bacterias o los tiempos de avería de una máquina, donde la mayoría de los valores son bajos pero ocasionalmente aparecen valores muy altos.\n\n::: {.callout-note}\nCuando la cola es hacia la derecha (valores altos poco frecuentes) hablamos de **asimetría positiva**. Cuando la cola es hacia la izquierda (valores bajos poco frecuentes) hablamos de **asimetría negativa**. En la práctica industrial, la asimetría positiva es mucho más frecuente que la negativa.\n:::\n\n### Distribución bimodal\n\nEn ocasiones el histograma muestra **dos picos** claramente diferenciados en lugar de uno. Esto se conoce como **distribución bimodal** y suele indicar que los datos provienen de dos grupos distintos que se han mezclado. Si volvemos al histograma de la longitud de aleta de los pingüinos y coloreamos por especie, vemos que lo que parecía una distribución aproximadamente simétrica es en realidad la mezcla de dos grupos:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.histplot(\n    data=penguins,\n    x='flipper_length_mm',\n    hue='species',\n    bins=20\n)\nplt.xlabel(\"Longitud de aleta (mm)\")\nplt.ylabel(\"Frecuencia\")\nplt.title(\"Distribución de la longitud de aleta por especie\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\n\nggplot(penguins, aes(x = flipper_length_mm, fill = species)) +\n  geom_histogram(bins = 20, alpha = 0.6, position = \"identity\") +\n  labs(\n    title = \"Distribución de la longitud de aleta por especie\",\n    x = \"Longitud de aleta (mm)\",\n    y = \"Frecuencia\",\n    fill = \"Especie\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-21-3.png){width=672}\n:::\n:::\n\n:::\n\nCuando en un proceso industrial aparece una distribución bimodal, es casi siempre una señal de que hay dos condiciones de proceso distintas mezcladas en los datos: dos máquinas, dos turnos, dos proveedores de materia prima o dos épocas del año con comportamientos diferentes. Identificar y separar esos grupos es uno de los primeros pasos del análisis.\n\n### Valores extremos y su efecto en la forma\n\nYa hemos visto en la sección del stemplot que algunos valores se separan claramente del resto. Estos valores, que llamamos **valores atípicos** o ***outliers***, afectan a la forma del histograma añadiendo barras aisladas en los extremos. Son importantes porque pueden indicar errores en la toma de datos, condiciones excepcionales del proceso, o simplemente la variabilidad natural de algunos fenómenos.\n\n::: {.callout-note}\nLa presencia de valores extremos es uno de los motivos por los que la exploración gráfica siempre debe preceder al cálculo de estadísticos. Como veremos en el capítulo 7, los valores extremos tienen una influencia desproporcionada sobre la media y la desviación típica, y pueden llevar a conclusiones erróneas si no se han detectado previamente.\n:::\n\nEn el capítulo siguiente veremos cómo la forma de los datos se refleja también en el diagrama de caja, y cómo la elección del estadístico más adecuado depende precisamente de esta forma.\n\n## Diagrama de caja o *boxplot*\n\nEste gráfico fue creado por el estadístico John Tukey en 1977, y es una herramienta fundamental en la exploración de datos. Se basa en el conjunto de **cuartiles**: si dividimos un grupo de datos **ordenados** en cuatro partes iguales mediante **tres** puntos de corte, llamamos **primer cuartil** o $Q1$ al valor que se sitúa en el 25%, **segundo cuartil** o $Q2$ al valor que se sitúa en el centro (50%), y **tercer cuartil** o $Q3$ al punto que se sitúa en el 75% de los datos. A estos tres valores añadimos el **mínimo** y el **máximo**, y tenemos un conjunto de **cinco números** que nos permiten describir la forma de la distribución con cierta precisión. El segundo cuartil ($Q2$), que corresponde al 50% de los datos, se conoce habitualmente como **mediana**. El valor resultante de restar $Q3-Q1$ es lo que se conoce como **rango intercuartil** o $IQR$, y es una medida de la dispersión de la distribución.\n\nEl **diagrama de caja**, también conocido como *boxplot*, es un gráfico que permite resumir las características principales de un conjunto de datos utilizando estos cinco números. Sus ventajas son:\n\n-   Muestra la mediana y los cuartiles (Q1 y Q3) de los datos.\n-   Permite identificar la simetría de la distribución: si la mediana no está en el centro, la distribución no es simétrica.\n-   Permite detectar posibles valores atípicos, representando los *outliers* que están lejos del resto de los datos (un valor es atípico si está más allá de $(Q3 + 1{,}5 \\cdot IQR)$ o $(Q1 - 1{,}5 \\cdot IQR)$).\n\nLa construcción de un diagrama de caja es como sigue:\n\n![](imagenes/boxplot.svg)\n\nMicrosoft Excel no dispone de un diseño de gráficos de caja que sea práctico, por lo que recurriremos siempre a `Python` o `R` para realizarlos.\n\n### El boxplot con pocos datos\n\nEmpecemos con nuestros datos de altura. Con solo 11 observaciones, el boxplot nos da un resumen numérico correcto, pero oculta la estructura real de los datos:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\naltura_cm = [153,135,140,140,175,138,145,154,152,159,154]\ndf_altura = pd.DataFrame({'altura_cm': altura_cm})\n\nsns.boxplot(data=df_altura, y='altura_cm')\nplt.ylabel(\"Altura (cm)\")\nplt.title(\"Boxplot de la altura de los alumnos\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\naltura_cm <- c(153,135,140,140,175,138,145,154,152,159,154)\n\nboxplot(altura_cm,\n        ylab = \"Altura (cm)\",\n        main = \"Boxplot de la altura de los alumnos\")\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-23-3.png){width=672}\n:::\n:::\n\n:::\n\nEl boxplot nos indica que hay un valor alto que se separa del resto (175 cm), y que la distribución es ligeramente asimétrica. Pero con solo 11 valores, ¿podemos fiarnos de este resumen? La caja representa el 50% central de los datos, pero ese 50% son apenas 5 o 6 alumnos. En estos casos es mucho más informativo mostrar los puntos individuales directamente, usando un dotplot:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\naltura_cm = [153,135,140,140,175,138,145,154,152,159,154]\ndf_altura = pd.DataFrame({'altura_cm': altura_cm})\n\nsns.stripplot(data=df_altura, y='altura_cm', jitter=False, size=8)\nplt.ylabel(\"Altura (cm)\")\nplt.title(\"Dotplot de la altura de los alumnos\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\naltura_cm <- c(153,135,140,140,175,138,145,154,152,159,154)\n\nstripchart(altura_cm,\n           method = \"stack\",\n           vertical = TRUE,\n           pch = 19,\n           ylab = \"Altura (cm)\",\n           main = \"Dotplot de la altura de los alumnos\")\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-25-3.png){width=672}\n:::\n:::\n\n:::\n\nCon el dotplot vemos exactamente cuántos alumnos hay en cada valor y dónde se concentran, información que el boxplot comprimía en una caja. La regla práctica es sencilla: **con pocos datos, el dotplot es más informativo que el boxplot**; el boxplot cobra todo su sentido cuando tenemos muchas observaciones.\n\n### El boxplot con más datos: penguins\n\nCon un dataset más grande el boxplot muestra toda su utilidad. Usaremos la longitud de aleta del dataset `penguins`. Este *dataset*  fue recopilado por la bióloga Kristen Gorman junto al equipo de la estación de investigación Palmer, en la Antártida, entre 2007 y 2009, y publicado en un estudio sobre dimorfismo sexual en pingüinos del género Pygoscelis [@gorman2014]. Posteriormente, Allison Horst, Alison Hill y Kristen Gorman lo empaquetaron como dataset de referencia para la enseñanza de estadística y visualización de datos, como alternativa al histórico dataset iris de Ronald Fisher. Contiene medidas morfológicas (longitud y profundidad del pico, longitud de aleta y peso corporal) de 344 pingüinos de tres especies (Adelie, Chinstrap y Gentoo) recogidas en tres islas del archipiélago Palmer. Su tamaño moderado, la presencia de valores ausentes reales, la existencia de grupos naturales con solapamiento parcial y la riqueza de relaciones entre variables lo han convertido en uno de los datasets estándar tanto en Python como en R.\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.boxplot(data=penguins, y='flipper_length_mm')\nplt.ylabel(\"Longitud de aleta (mm)\")\nplt.title(\"Boxplot de la longitud de aleta\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\n\nboxplot(penguins$flipper_length_mm,\n        ylab = \"Longitud de aleta (mm)\",\n        main = \"Boxplot de la longitud de aleta\")\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-27-3.png){width=672}\n:::\n:::\n\n:::\n\n### La forma de los datos en el boxplot\n\nLa forma que vimos en el histograma se refleja directamente en el boxplot. En una distribución simétrica, la mediana está centrada dentro de la caja y los dos bigotes tienen una longitud similar. En una distribución asimétrica, la mediana se desplaza hacia uno de los extremos de la caja y los bigotes tienen longitudes desiguales.\n\nComparemos el boxplot de la longitud de aleta de penguins (distribución aproximadamente simétrica) con el boxplot de los goles por partido en La Liga (distribución asimétrica positiva):\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\nlaliga = pd.read_csv(\"datos/laliga_resultados2425.csv\", sep=';')\nlaliga['goles_totales'] = laliga['goles_local'] + laliga['goles_visitante']\n\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5))\n\nsns.boxplot(data=penguins, y='flipper_length_mm', ax=ax1)\nax1.set_title(\"Longitud de aleta (simétrica)\")\nax1.set_ylabel(\"mm\")\n\nsns.boxplot(data=laliga, y='goles_totales', ax=ax2)\nax2.set_title(\"Goles por partido (asimétrica positiva)\")\nax2.set_ylabel(\"Goles\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-28-1.png){width=960}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\n\nlaliga <- read.csv2(\"datos/laliga_resultados2425.csv\")\nlaliga$goles_totales <- laliga$goles_local + laliga$goles_visitante\n\npar(mfrow = c(1, 2))\n\nboxplot(penguins$flipper_length_mm,\n        main = \"Longitud de aleta (simétrica)\",\n        ylab = \"mm\")\n\nboxplot(laliga$goles_totales,\n        main = \"Goles por partido (asimétrica positiva)\",\n        ylab = \"Goles\")\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-29-3.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n:::\n\nEn el boxplot de los goles vemos claramente la asimetría positiva: la mediana está desplazada hacia la parte inferior de la caja, el bigote superior es mucho más largo que el inferior, y hay varios valores atípicos en la parte alta. En el capítulo 8 veremos cómo esta misma lectura del boxplot nos ayudará a interpretar la variabilidad estacional del extracto seco en la fabricación de queso camembert.\n\n### El boxplot por grupos\n\nUna de las aplicaciones más útiles del boxplot es la comparación de distribuciones entre grupos. Para ello simplemente indicamos a Python o R qué variable queremos usar como agrupación. Usamos penguins para comparar la longitud de aleta por especie:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.boxplot(data=penguins, x='species', y='flipper_length_mm')\nplt.xlabel(\"Especie\")\nplt.ylabel(\"Longitud de aleta (mm)\")\nplt.title(\"Longitud de aleta por especie\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\n\nboxplot(flipper_length_mm ~ species,\n        data = penguins,\n        xlab = \"Especie\",\n        ylab = \"Longitud de aleta (mm)\",\n        main = \"Longitud de aleta por especie\")\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-31-3.png){width=672}\n:::\n:::\n\n:::\n\nCuando la caja de un grupo se sitúa claramente por encima o por debajo de la caja de otro grupo, las diferencias entre ellos son visualmente significativas. En este caso, los pingüinos *Gentoo* tienen aletas notablemente más largas que los *Adelie* y los *Chinstrap*. En el capítulo 8 usaremos este mismo tipo de gráfico para comparar la composición del queso camembert mes a mes a lo largo del año.\n\n### Relación entre el *boxplot* y el histograma\n\nResulta muy útil comprender visualmente la relación entre el *boxplot* y el histograma para entender la distribución de los datos. La caja del boxplot se corresponde con el 50% central de los datos, y la línea media representa la mediana. En el gráfico siguiente mostramos ambas representaciones de forma simultánea para la longitud de aleta de penguins:\n\n\n::: {.cell}\n\n```{.python .cell-code  code-fold=\"true\" code-summary=\"Mostrar código\"}\nfrom palmerpenguins import load_penguins\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\npenguins = load_penguins()\n\nfig, (ax_hist, ax_box) = plt.subplots(\n    2, 1,\n    sharex=True,\n    gridspec_kw={\"height_ratios\": (.85, .15)},\n    figsize=(8, 6)\n)\n\nsns.histplot(\n    data=penguins,\n    x='flipper_length_mm',\n    bins=20,\n    edgecolor='black',\n    alpha=0.7,\n    kde=True,\n    ax=ax_hist\n)\nax_hist.set_title(\"Histograma y Boxplot: longitud de aleta (penguins)\", fontsize=14)\nax_hist.set_ylabel(\"Frecuencias\", fontsize=12)\nax_hist.set_xlabel('')\n\nsns.boxplot(\n    data=penguins,\n    x='flipper_length_mm',\n    color='darkgrey',\n    linewidth=1.5,\n    flierprops={'markerfacecolor': 'red', 'marker': 'o'},\n    ax=ax_box\n)\nax_box.set_xlabel('Longitud de aleta (mm)', fontsize=12)\nax_box.set_ylabel('')\nax_box.tick_params(left=False, labelleft=False)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-32-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Mostrar código\"}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\nlibrary(patchwork)\n\np_hist <- ggplot(penguins, aes(x = flipper_length_mm)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", alpha = 0.7, color = \"black\") +\n  geom_density(aes(y = after_stat(count)), color = \"darkblue\", linewidth = 1) +\n  labs(title = \"Histograma y Boxplot: longitud de aleta (penguins)\",\n       y = \"Frecuencias\") +\n  theme_bw() +\n  theme(axis.title.x = element_blank(), axis.text.x = element_blank())\n\np_box <- ggplot(penguins, aes(x = flipper_length_mm)) +\n  geom_boxplot(fill = \"darkgrey\", outlier.color = \"red\") +\n  labs(x = \"Longitud de aleta (mm)\") +\n  theme_bw() +\n  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(),\n        axis.title.y = element_blank())\n\np_hist / p_box + plot_layout(heights = c(5, 1))\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-33-3.png){width=768}\n:::\n:::\n\n\n## Alternativas al boxplot\n\n#### Beeswarm\n\nEl *boxplot* es muy útil para resumir grandes cantidades de información, pero cuando el número de puntos es bajo puede resultarnos más útil la visualización mediante gráficos que muestren los puntos individuales. Entre estas visualizaciones, el gráfico tipo *beeswarm* puede utilizarse en Python mediante la función `swarmplot()` de `seaborn`, o en R mediante la librería `ggbeeswarm`.\n\n::: panel-tabset\n## Python (con `seaborn`)\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.swarmplot(data=penguins, y='flipper_length_mm', size=3)\nplt.title('Beeswarm: longitud de aleta')\nplt.ylabel('Longitud de aleta (mm)')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n## R (con `ggbeeswarm`)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\nlibrary(ggbeeswarm)\n\nggplot(penguins, aes(x = \"\", y = flipper_length_mm)) +\n  geom_beeswarm(size = 1.5, color = \"darkblue\", cex = 1.5) +\n  labs(\n    title = \"Beeswarm: longitud de aleta\",\n    x = \"\",\n    y = \"Longitud de aleta (mm)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-35-3.png){width=672}\n:::\n:::\n\n:::\n\nEl *beeswarm* nos da una distribución aproximada de los valores individuales, colocándolos de forma que se eviten solapamientos.\n\n#### Stripplot o dotplot\n\nEl *stripplot* muestra los puntos en distribución vertical sobre las categorías; para evitar que los puntos con la misma coordenada se solapen, utilizamos la opción *jitter*, que introduce un pequeño ruido aleatorio horizontal.\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.stripplot(data=penguins, y='flipper_length_mm', jitter=True, size=3)\nplt.title('Dotplot con jitter: longitud de aleta')\nplt.ylabel(\"Longitud de aleta (mm)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\n\nggplot(penguins, aes(x = \"\", y = flipper_length_mm)) +\n  geom_jitter(width = 0.1, size = 1.5, color = \"darkblue\", alpha = 0.6) +\n  labs(\n    title = \"Longitud de aleta\",\n    subtitle = \"Dotplot con jitter\",\n    x = \"\",\n    y = \"Longitud de aleta (mm)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-37-3.png){width=672}\n:::\n:::\n\n:::\n\nEstos diagramas pueden superponerse al *boxplot*, lo que nos permite completar la visualización de los puntos y la interpretación que hace el *boxplot* de su distribución.\n\n::: panel-tabset\n## Python (beeswarm)\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.boxplot(data=penguins, y='flipper_length_mm', width=0.2, color='lightgray')\nsns.swarmplot(data=penguins, y='flipper_length_mm', size=2)\nplt.title('Boxplot + Beeswarm: longitud de aleta')\nplt.ylabel(\"Longitud de aleta (mm)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n## Python (stripplot)\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.boxplot(data=penguins, y='flipper_length_mm', color='lightgray', width=0.3, fliersize=0)\nsns.stripplot(data=penguins, y='flipper_length_mm', jitter=True, size=3, color='darkblue', alpha=0.5)\nplt.title('Boxplot + Stripplot: longitud de aleta')\nplt.ylabel(\"Longitud de aleta (mm)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-39-3.png){width=672}\n:::\n:::\n\n\n## R (beeswarm)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\nlibrary(ggbeeswarm)\n\nggplot(penguins, aes(x = \"\", y = flipper_length_mm)) +\n  geom_boxplot(width = 0.3, fill = \"lightgray\", outlier.shape = NA) +\n  geom_beeswarm(color = \"darkblue\", size = 1.5, cex = 1.5, alpha = 0.4) +\n  labs(\n    title = \"Boxplot + Beeswarm: longitud de aleta\",\n    x = \"\",\n    y = \"Longitud de aleta (mm)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-40-5.png){width=672}\n:::\n:::\n\n\n## R (stripplot)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\n\nggplot(penguins, aes(x = \"\", y = flipper_length_mm)) +\n  geom_boxplot(width = 0.3, fill = \"lightgray\", outlier.shape = NA) +\n  geom_jitter(width = 0.1, size = 1.5, color = \"darkblue\", alpha = 0.4) +\n  labs(\n    title = \"Longitud de aleta\",\n    subtitle = \"Boxplot + Dotplot con jitter\",\n    x = \"\",\n    y = \"Longitud de aleta (mm)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n:::\n\n## Gráficos de densidad\n\nUn gráfico de densidad es una representación visual suavizada de la distribución de un conjunto de datos. A diferencia de los histogramas, que dividen los datos en intervalos y cuentan las frecuencias, los gráficos de densidad utilizan técnicas estadísticas no paramétricas para estimar la función de densidad de probabilidad.\n\nExcel no permite la representación de los gráficos de densidad; en `Python` utilizamos `seaborn` y en `R` utilizamos `ggplot2`.\n\nLos gráficos de densidad son especialmente útiles cuando estamos comparando diferentes grupos de datos entre sí. En este caso comparamos la longitud de aleta de los pingüinos por especie:\n\n\n::: {.cell}\n\n```{.python .cell-code  code-fold=\"true\" code-summary=\"Mostrar código\"}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nplt.figure(figsize=(10, 6))\n\nsns.kdeplot(\n    data=penguins,\n    x='flipper_length_mm',\n    hue='species',\n    fill=True,\n    alpha=0.2,\n    linewidth=2\n)\n\nplt.title('Curva de densidad de la longitud de aleta por especie', fontsize=16)\nplt.xlabel('Longitud de aleta (mm)', fontsize=12)\nplt.ylabel('Densidad', fontsize=12)\nplt.grid(axis='y', linestyle='--', alpha=0.6)\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-42-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Mostrar código\"}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\n\nggplot(penguins, aes(x = flipper_length_mm, fill = species, color = species)) +\n  geom_density(alpha = 0.2, linewidth = 1, adjust = 1) +\n  labs(\n    title = \"Curva de densidad de la longitud de aleta por especie\",\n    x = \"Longitud de aleta (mm)\",\n    y = \"Densidad\",\n    fill = \"Especie\",\n    color = \"Especie\"\n  ) +\n  theme_minimal() +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-43-3.png){width=672}\n:::\n:::\n\n\nLos gráficos de densidad confirman la bimodalidad que observamos en el histograma: las especies *Adelie* y *Chinstrap* tienen distribuciones solapadas con aletas más cortas, mientras que *Gentoo* tiene aletas claramente más largas.\n\n### Otra alternativa al *boxplot*: el *violin plot*\n\nEl *violin plot* es una alternativa al *boxplot* que tiene la ventaja de mostrar la *densidad* de la distribución superpuesta al *boxplot*, lo que permite visualizar con más claridad la distribución de los datos:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.violinplot(y='flipper_length_mm', data=penguins)\nplt.title('Violin plot: longitud de aleta')\nplt.ylabel(\"Longitud de aleta (mm)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\n\nggplot(penguins, aes(x = \"\", y = flipper_length_mm)) +\n  geom_violin(fill = \"lightgray\", color = \"grey\") +\n  geom_boxplot(width = 0.1, fill = \"white\", color = \"black\", outlier.shape = NA) +\n  labs(\n    title = \"Violin plot: longitud de aleta\",\n    x = \"\",\n    y = \"Longitud de aleta (mm)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-45-3.png){width=672}\n:::\n:::\n\n:::\n\nTanto el *violin plot* como el *boxplot* se usan muy a menudo para comparar distribuciones de datos. El violin plot múltiple por especie muestra con claridad las diferencias que ya observamos en los gráficos de densidad:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.violinplot(x='species', y='flipper_length_mm', data=penguins, alpha=0.4)\nplt.title('Violin plot por especie: longitud de aleta')\nplt.xlabel(\"Especie\")\nplt.ylabel(\"Longitud de aleta (mm)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\n\nggplot(penguins, aes(x = species, y = flipper_length_mm, fill = species)) +\n  geom_violin(alpha = 0.4, color = \"black\") +\n  geom_boxplot(width = 0.1, fill = \"white\", outlier.shape = NA) +\n  labs(\n    title = \"Violin plot por especie: longitud de aleta\",\n    x = \"Especie\",\n    y = \"Longitud de aleta (mm)\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-47-3.png){width=672}\n:::\n:::\n\n:::\n\n## Gráficos de dispersión\n\nUn gráfico de dispersión, también conocido como diagrama de dispersión o *scatter plot*, es una representación gráfica que utiliza puntos para mostrar la relación entre dos variables numéricas. Cada punto en el gráfico representa una observación del conjunto de datos y se coloca en el plano cartesiano de acuerdo con sus valores en las dos variables que se están comparando.\n\nLos gráficos de dispersión son útiles para identificar varios aspectos de la relación entre las dos variables:\n\n-   Si los puntos tienden a agruparse a lo largo de una línea recta ascendente, esto indica una **correlación positiva** (a medida que una variable aumenta, la otra también lo hace).\n-   Si los puntos se agrupan a lo largo de una línea descendente, esto indica una **correlación negativa** (a medida que una variable aumenta, la otra disminuye).\n-   Si los puntos forman una curva en lugar de una línea recta, esto sugiere una **relación no lineal** entre las variables.\n-   La dispersión de los puntos puede indicar la variabilidad de los datos. Puntos que están muy lejos del patrón general pueden ser valores atípicos.\n\nRepresentamos la longitud de aleta y el peso corporal de los pingüinos del dataset `penguins`:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nsns.scatterplot(data=penguins, x='flipper_length_mm', y='body_mass_g')\nplt.title('Relación entre longitud de aleta y peso corporal')\nplt.xlabel('Longitud de aleta (mm)')\nplt.ylabel('Peso corporal (g)')\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\n\nggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +\n  geom_point(alpha = 0.7) +\n  labs(\n    title = \"Relación entre longitud de aleta y peso corporal\",\n    x = \"Longitud de aleta (mm)\",\n    y = \"Peso corporal (g)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-49-3.png){width=672}\n:::\n:::\n\n:::\n\nTanto Python como R nos permiten separar el diagrama de dispersión en función de una tercera variable, en este caso la especie:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom palmerpenguins import load_penguins\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npenguins = load_penguins()\n\nplt.figure(figsize=(9, 6))\nsns.scatterplot(data=penguins, x='flipper_length_mm', y='body_mass_g',\n                hue='species', s=60, alpha=0.7)\nplt.title('Relación entre longitud de aleta y peso corporal por especie')\nplt.xlabel('Longitud de aleta (mm)')\nplt.ylabel('Peso corporal (g)')\nplt.legend(title='Especie')\nplt.grid(True, linestyle='--', alpha=0.7)\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-50-1.png){width=864}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\n\nggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g, color = species)) +\n  geom_point(size = 2, alpha = 0.8) +\n  labs(\n    title = \"Relación entre longitud de aleta y peso corporal por especie\",\n    x = \"Longitud de aleta (mm)\",\n    y = \"Peso corporal (g)\",\n    color = \"Especie\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-51-3.png){width=672}\n:::\n:::\n\n:::\n\nLos gráficos de dispersión multiserie no son nativos en Microsoft Excel, pero pueden hacerse con algo de trabajo manual, un poco más complejo que el procedimiento en **Python** o **R** (ver el procedimiento [aquí](https://juanriera.github.io/blog/posts/excel-xy/) y [aquí](https://juanriera.github.io/blog/posts/excel-xy-pinguinos/), y un vídeo con el procedimiento detallado [aquí](https://www.youtube.com/watch?v=tD2P5wabb1k)).\n\nComo vemos, los gráficos de dispersión son una herramienta esencial en el análisis exploratorio de datos, ya que permiten visualizar relaciones y patrones, identificar correlaciones y detectar posibles anomalías.\n\n## Gráficos de series temporales\n\nHasta ahora hemos utilizado gráficos y tablas que describen la estructura y forma de una variable, o las relaciones entre dos variables. Hay otros gráficos que tienen en cuenta la forma en la que esos datos cambian con el tiempo. En este caso, será necesario que hayamos recogido en una variable de nuestra tabla los intervalos de tiempo en los que se han producido nuestros valores.\n\nAlgunos ejemplos:\n\n-   proceso de llenado de envases de queso crema: se llena una tarrina cada 15 segundos. Nuestros datos deben recoger el tiempo y el peso.\n-   el registro diario de temperatura en una cámara de maduración.\n-   el seguimiento mensual de la temperatura media exterior en una zona geográfica.\n\nEn un gráfico de series temporales:\n\n-   el eje horizontal (X) representa el tiempo. Los puntos de tiempo pueden ser minutos, horas, días, meses, años, etc.\n-   el eje vertical (Y) representa los valores de la variable que se está estudiando.\n-   los valores se conectan mediante una línea que muestra cómo cambia la variable a lo largo del tiempo.\n-   normalmente no suelen representarse los puntos individuales para facilitar la legibilidad del gráfico.\n\nCuando representamos valores en el tiempo, nunca usaremos el diagrama de barras, sino el gráfico de líneas.\n\nUsaremos el dataset de **temperatura media mensual de Oviedo entre 2020 y 2024**, que está en el fichero `oviedo_temperatura.csv`. Este *dataset* contiene la temperatura media mensual registrada en Oviedo entre 2020 y 2024, con un total de 60 observaciones. Los datos proceden de los registros de [AEMET (Agencia Estatal de Meteorología)](https://www.aemet.es) y se han utilizado por su proximidad geográfica y por ilustrar con claridad dos patrones habituales en las series temporales industriales: la estacionalidad regular (el ciclo anual de temperaturas) y la tendencia a largo plazo, en este caso un ligero incremento de las temperaturas medias a lo largo del período.\n\n### Cómo hacer los gráficos de series temporales en Excel\n\nPara hacer el gráfico en Excel, seleccionamos la columna `temperatura` e insertamos un gráfico de líneas. A continuación, con el cursor sobre el gráfico, pulsamos el botón derecho y seleccionamos la opción `Seleccionar datos`. Una vez abierto el cuadro de opciones, editamos las etiquetas del eje X y seleccionamos el rango de la variable `fecha` desde la fila 2 hasta la última. Aceptamos, y a continuación editamos el formato del eje Y para ajustar la escala a los valores de temperatura.\n\n### Gráficos de series temporales en `Python` utilizando `pandas`\n\nEn los procesos industriales, el manejo de datos que cambian con el tiempo (**series temporales**) es fundamental. Hablamos de registrar **temperaturas** en un proceso de cocción, el **pH** de una fermentación a lo largo de las horas o días, o la **evolución de inventarios** de productos perecederos.\n\nPara abordar este análisis de manera **eficiente y sencilla**, la biblioteca `pandas` de Python es la herramienta de referencia. Esto nos ofrece una serie de ventajas clave:\n\n1.  **Fácil Indexación Temporal:** Pandas permite que la fecha y hora sean el \"índice\" principal de los datos, simplificando el filtrado y la selección por rangos.\n2.  **Remuestreo (Resampling) Sencillo:** Pandas permite cambiar la frecuencia de los datos con una única función, lo que es vital para suavizar el \"ruido\" y ver la tendencia real del proceso.\n3.  **Ventanas Móviles (`rolling`):** Permite calcular promedios móviles o desviaciones estándar sobre un periodo de tiempo definido, crucial para el control de calidad.\n\n### Construyendo la serie temporal con `pandas`\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\ndf_temp = pd.read_csv(\"datos/oviedo_temperatura.csv\",\n                      sep=';',\n                      decimal=',')\n\ndf_temp['fecha'] = pd.to_datetime(\n    df_temp['fecha'],\n    format='%d/%m/%Y',\n    errors='coerce'\n)\n\ndf_temp.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 60 entries, 0 to 59\nData columns (total 2 columns):\n #   Column       Non-Null Count  Dtype         \n---  ------       --------------  -----         \n 0   fecha        60 non-null     datetime64[ns]\n 1   temperatura  60 non-null     float64       \ndtypes: datetime64[ns](1), float64(1)\nmemory usage: 1.1 KB\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf_temp.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fecha  temperatura\n0 2020-01-01          9.2\n1 2020-02-01          9.8\n2 2020-03-01         11.4\n3 2020-04-01         11.6\n4 2020-05-01         14.2\n```\n\n\n:::\n:::\n\n\nCreamos el índice temporal y representamos la serie:\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf_temp['fecha_index'] = pd.DatetimeIndex(df_temp.fecha).normalize()\ndf_temp.set_index('fecha_index', inplace=True)\ndf_temp.sort_index(inplace=True)\n\ndf_temp[\"temperatura\"].plot()\nplt.ylabel(\"Temperatura media (°C)\")\nplt.title(\"Temperatura media mensual en Oviedo 2020-2024\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\nEl gráfico muestra con claridad la **estacionalidad** anual: temperaturas bajas en invierno y altas en verano, con un patrón que se repite cada año. Además, si observamos con atención, podemos apreciar una ligera **tendencia creciente** a lo largo del período, que refleja el calentamiento registrado en los últimos años. Los gráficos de series temporales son capaces de mostrar simultáneamente estos dos patrones: la variación estacional a corto plazo y la tendencia a largo plazo.\n\nPodemos calcular y representar la media anual para visualizar mejor la tendencia:\n\n\n::: {.cell}\n\n```{.python .cell-code}\nplt.figure(figsize=(10.0, 3.0))\ndf_temp[\"temperatura\"].resample('YE').mean().plot(\n    title=\"Temperatura media anual en Oviedo 2020-2024\",\n    marker='o')\nplt.ylabel(\"Temperatura media (°C)\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-55-3.png){width=960}\n:::\n:::\n\n\nY podemos hacer zoom en un período concreto para analizar con más detalle:\n\n\n::: {.cell}\n\n```{.python .cell-code}\nplt.figure(figsize=(10.0, 3.0))\ndf_temp[\"temperatura\"][\"2022\":\"2023\"].plot(\n    title=\"Temperatura media mensual en Oviedo 2022-2023\")\nplt.ylabel(\"Temperatura media (°C)\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-56-5.png){width=960}\n:::\n:::\n\n\n::: {.callout-tip title=\"Sugerencia\"}\nSe recomienda copiar el código y pegarlo en ChatGPT o Gemini para explicarlo en detalle. Utiliza el [texto de la nota de aviso](#clr-instrucciones) que dimos al principio del capítulo para pedir que explique el código.\n:::\n\nA continuación, el gráfico realizado con R.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Mostrar código\"}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(lubridate)\n\ndf_temp <- read.csv2(\"datos/oviedo_temperatura.csv\",\n                     dec = \",\")\ndf_temp$fecha <- dmy(df_temp$fecha)\n\nggplot(df_temp, aes(x = fecha, y = temperatura)) +\n  geom_line(color = \"steelblue\", linewidth = 1) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\",\n              linetype = \"dashed\", linewidth = 0.8) +\n  labs(\n    title = \"Temperatura media mensual en Oviedo 2020-2024\",\n    subtitle = \"La línea roja muestra la tendencia general\",\n    x = \"Fecha\",\n    y = \"Temperatura media (°C)\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](060-exploracion_files/figure-html/unnamed-chunk-57-7.png){width=960}\n:::\n:::\n\n\n### Resumen\n\nLos gráficos de series temporales son la herramienta fundamental para el seguimiento y control de los procesos industriales. Permiten identificar tendencias a largo plazo, detectar estacionalidad (variaciones ligadas al ciclo productivo o a la época del año) y localizar anomalías puntuales que pueden indicar incidencias en el proceso o errores en la toma de datos. En la industria alimentaria, donde variables como temperatura, pH, extracto seco o rendimiento se registran de forma continua o periódica, la representación temporal es con frecuencia el primer paso del análisis antes de aplicar cualquier otra herramienta estadística.\n\n## Algunas sugerencias para la creación de gráficos\n\nAlgunos sitios tienen ejemplos de gráficos que puede resultar útil revisar:\n\n-   [Galería de `matplotlib`](https://matplotlib.org/stable/gallery/index.html), gran cantidad de ejemplos en Python\n-   [Galería de `seaborn`](https://seaborn.pydata.org/examples/index.html), una extensa galería de gráficos hechos con esta librería Python\n-   [Python Graph Gallery](https://python-graph-gallery.com/), otra extensa galería de gráficos en Python\n-   [The R Graph Gallery](https://r-graph-gallery.com/), una galería de gráficos hechos con R\n-   [R-charts](https://r-charts.com/) es una galería de gráficos R creada por un español, José Carlos Soage.\n-   [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/) para profundizar en ggplot2, el libro de referencia de Hadley Wickham, de acceso libre en web\n-   [R for Data Science, cap. Visualización](https://r4ds.hadley.nz/data-visualize), introducción práctica a ggplot2 en contexto de análisis de datos\n-   [Tidyplots](https://tidyplots.org/) utiliza la librería `tidyplots` en R para realizar de forma sencilla gran cantidad de gráficos, simplificando la sintaxis de ggplot2.\n\nUna de las guías más conocidas y seguidas para la creación de gráficos es el [vocabulario visual del Financial Times](https://raw.githubusercontent.com/ft-interactive/chart-doctor/master/visual-vocabulary/poster.webp)\n\nTambién esta guía proporciona información sobre el uso adecuado de cada tipo de gráfico, facilitando la elección según el objetivo perseguido\n\n![](imagenes/060/1740294003188.jpg) ![](imagenes/060/1740121283445.jpg)\n\n## Resumen del capítulo\n\nLa visualización gráfica es la herramienta más directa para explorar un conjunto de datos antes de aplicar cualquier análisis estadístico. El stemplot permite obtener una visión rápida de la distribución de datos pequeños manteniendo los valores originales, aunque su uso ha quedado desplazado por herramientas gráficas más potentes. Las tablas de distribución de frecuencias organizan los datos en intervalos y permiten calcular frecuencias absolutas, relativas y acumuladas; pueden construirse en Excel mediante tablas dinámicas, o en Python y R mediante código reproducible y auditable.\n\nEl histograma es el gráfico estándar para representar la distribución de variables continuas. La forma del histograma nos informa sobre la naturaleza de los datos: una distribución simétrica indica homogeneidad, una distribución asimétrica señala que los valores extremos son frecuentes en uno de los lados, y una distribución bimodal revela la presencia de dos grupos distintos mezclados en los datos. El diagrama de barras se reserva para variables discretas o categóricas. El boxplot resume la distribución mediante cinco números (mínimo, Q1, mediana, Q3, máximo), refleja la forma de la distribución a través de la posición de la mediana y la longitud de los bigotes, y señala automáticamente los valores atípicos; con pocos datos es preferible usar el dotplot, que muestra los valores individuales. Para conjuntos de datos mayores pueden utilizarse alternativas como el beeswarm, el stripplot o el violin plot, que combinan el resumen estadístico con la visualización de los puntos individuales.\n\nLos gráficos de densidad, disponibles en Python mediante seaborn y en R mediante ggplot2, ofrecen una representación suavizada de la distribución y resultan especialmente útiles para comparar grupos. Los gráficos de dispersión permiten visualizar la relación entre dos variables numéricas e identificar correlaciones, relaciones no lineales y valores atípicos; Python y R facilitan la segmentación por una tercera variable, lo que en Excel requiere un trabajo manual adicional. Los gráficos de series temporales representan la evolución de una variable en el tiempo y permiten identificar simultáneamente la estacionalidad y la tendencia a largo plazo; pandas en Python proporciona funciones de remuestreo que simplifican este análisis, con equivalentes en R mediante dplyr y lubridate. El capítulo concluye con referencias a galerías de ejemplos en Python y R y a guías de selección del tipo de gráfico según el objetivo del análisis.\n",
    "supporting": [
      "060-exploracion_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}