# Introducción a los rendimientos queseros

Supongamos que somos un fabricante de queso, fabricamos un producto determinado del que tenemos valores analíticos de producto terminado y de la materia en proceso.

Es un producto que, más o menos, siempre fabricaremos con los mismos pasos tecnológicos. Puesto que siempre hacemos el mismo producto, siempre fabricamos igual, con la variabilidad inherente a nuestro proceso.

Vamos a ir definiendo por pasos nuestra tecnología.

Los dos primeros pasos consisten en

1.  definir el producto, y

2.  la materia prima con la que lo hacemos.

En nuestro caso, supongamos que hacemos un queso que tiene una composición determinada, que caracterizamos mediante un análisis de extracto seco y una grasa butirométrica, en un punto determinado de nuestro proceso (por ejemplo, a la salida de la salmuera, después de escurrido) y mediante un muestreo repetible, de forma que nuestro análisis sea representativo.

Supongamos que este es el resultado analítico de nuestro producto:

| **Datos del producto**  |        |
| ----------------------- | ------ |
| EST a salida de sal (%) | 55,00% |
| MG a salida de sal (%)  | 28,00% |

Para hacer este producto, estamos trabajando con una leche cuya composición es:

| **Datos de materia prima**  |       |
| --------------------------- | ----- |
| **Composición leche (g/L)** |       |
| MG                          | 33,37 |
| MP                          | 31,13 |

## Densidad y conversión entre porcentajes

Estamos expresando la composición de nuestra leche en gramos por litro (g/L). Podemos expresarla también en porcentaje, es decir, cuántos gramos de grasa y de proteína tenemos en 100 ml o en 100 g de leche.

Para expresar esta cantidad en gramos/100 ml no tenemos más que dividir por 1000 y multiplicar por 100, para expresar la cantidad en %:

| **Datos de  materia prima**  | **g/L** | **%   peso/volumen** |
| ---------------------------- | ------- | -------------------- |
| **Composición  leche (g/L)** |         |                      |
| MG                           | 33,37   | 3,34%                |
| MP                           | 31,13   | 3,11%                |

Para expresar las cantidades en g/100 g de leche necesitamos un parámetro adicional que nos define cuál es el peso de nuestros 100 ml de leche: la densidad.

La densidad aproximada de la leche de vaca es 1,030. Esto quiere decir que 1 L de leche entera pesa aproximadamente 1,030 k

$$
\frac{3.34\ \text{g grasa}}{100\ \text{ml leche}} \cdot \frac{1\ \text{ml leche}}{1.030\ \text{g leche}} = \frac{3.34}{1.030} \cdot \frac{\text{g grasa}}{100\ \text{g leche}} = 3.24\% \text{ en peso}
$$
Esto quiere decir que si 100 ml de leche pesan 103,0 gramos, 100 gramos de leche ocuparán un volumen que será un poco menos de 100 ml, exactamente:

$$
\frac{100\ g*100\ ml}{103\ ,0\ g} = 97.08\ ml
$$

Luego, la cantidad de materia grasa en 100 ml de leche siempre será algo superior a la cantidad en 100 g de leche.

Por último, a título de curiosidad, podemos recuperar la densidad de la leche a partir de los porcentajes, como es lógico:
$$
\frac{3,34\ g\ grasa}{100\ ml\ leche}*\ \frac{100\ g\ leche}{3,24\ g\ grasa} = 1,030\ \frac{g}{ml}\ leche
$$

De esta forma, nuestra tabla de valores analíticos de la leche, expresada en las diferentes unidades que hemos visto, quedaría de la siguiente forma:

| **Datos  de materia prima**  | **g/L** | **%   peso/volumen** | **%    peso/peso** |
| ---------------------------- | ------- | -------------------- | ------------------ |
| **Composición  leche (g/L)** |         |                      |                    |
| MG                           | 33,37   | 3,337%               | 3,240%             |
| MP                           | 31,13   | 3,113%               | 3,022%             |

Conociendo estas conversiones, y para evitar dudas y posibles errores, utilizaremos siempre los gramos por litro (g/L) para expresar la cantidad de grasa y proteína en la leche.

## Cálculo de la cantidad de leche necesaria para fabricar 1 kg de queso

Sabemos que nuestro proceso de fabricación quesera consiste en la coagulación de la caseína y expulsión de suero, y que la materia grasa queda retenida en la red de caseína.

Este concepto es la base fundamental de la comprensión de la tecnología quesera: es el rendimiento en la recuperación de la proteína el que nos va a definir todo el proceso, la materia grasa “acompañará” de forma estática (aunque tendrá influencia en el desuerado)

Por esta razón, el principal elemento del rendimiento en la definición de la tecnología es el porcentaje de recuperación de proteína en el extracto seco magro (aislamos el efecto la grasa)

Hemos definido nuestro producto mediante los análisis de EST y MG; necesitamos saber el resto de parámetros, en concreto el extracto seco magro que estamos definiendo para nuestro producto:

| **Análisis salida sal** (g/100g) |        |
| -------------------------------- | :----: |
| EST %                            | 55,00% |
| MG                               | 28,00% |
| G/ES %                           | 50,91% |
| HFD                              | 62,50% |
| ESM                              | 27,00% |

Estos análisis están definidos en porcentajes peso/peso, ya que en el queso no analizamos volumen sino peso. Por lo tanto, 100 gramos de nuestro queso tendrán 27 gramos de extracto seco magro.

En el capítulo siguiente calcularemos el porcentaje de recuperación de la proteína de la leche en el extracto seco magro a partir de nuestros datos analíticos de un conjunto de fabricaciones; en nuestro ejemplo actual, vamos a suponer que es de 94,65%. La hoja Excel siguiente muestra los cálculos precisos.

[Descargar hoja Excel de rendimientos](https://raw.githubusercontent.com/juanriera/master-queseria/master/datos/2025-11-06-ejemplo-std-tecnico.xlsx){target="_blank" rel="noopener noreferrer"}

Como sabemos la cantidad de proteína que tenemos en la leche, 31,13 g/L, sabemos que con 1 L de leche vamos a obtener en el queso

$$
\frac{31,13\ g\ proteína}{1\ L\ leche}*\ \frac{0.9465\ g\ ESM}{1\ g\ proteína} = 29,46\ g\ ESM\ en\ el\ queso\ por\ litro\ de\ leche
$$

Esta es la conversión clave de nuestra tecnología, y es conocida como ***coeficiente G*** en honor a su autor, Antoine M Guérault, que lo introdujo formalmente por primera vez por en su libro *La fromagerie devant les techniques nouvelles,* en 1966; desde entonces sigue utilizándose con plena validez. Inicialmente, el factor de conversión relaciona el ESM obtenido con el ESM puesto en fabricación, por lo tanto es simplemente el coeficiente de recuperación de ESM en nuestro queso; como para una tecnología concreta, normalmente la cantidad de sal incluida en el salado y las pérdidas de ESM son aproximadamente las mismas (salvo accidentes de fabricación), usamos la proteína de la leche en vez del ESM. Esto lleva a una pequeña diferencia en el valor del coeficiente, que  se mantiene constante para la misma tecnología.

Como sabemos la cantidad de ESM que vamos a obtener de 1 L de leche, podemos calcular los litros de leche que necesitamos para obtener 1 kg de queso mediante una regla de tres simple: si para obtener 100 g de queso con 29,46 g de ESM necesitamos 1 L de leche, para obtener 1 kg de queso con el mismo ESM necesitaremos X litros de leche. A este valor lo llamaremos *litraje unitario*.

$$
\text{Litraje unitario} = \frac{27\ g\ ESM}{100\ g\ queso\ }*\ \frac{1000\ g\ queso}{1\ kg\ queso}*\ \frac{1\ L\ leche}{29,46\ g\ ESM} = 9,165\ L\ leche\ para\ hacer\ 1\ kg\ de\ queso
$$

Es necesario insistir en que este litraje sólo es válido en nuestras condiciones precisas:

- con la composición en ESM de nuestro queso

- con la composición de proteína de nuestra leche

- con la tasa de recuperación de la proteína de la leche en el ESM del queso de nuestro específico proceso de fabricación.

Es un valor teórico que utilizamos como valor objetivo, y que puede variar a medida que adaptemos o variemos nuestra tecnología. Para cualquier otro producto, otra composición de leche y/u otro proceso de fabricación, deberemos recalcular nuestro litraje por kilo.

Sabemos que, en nuestras condiciones, 9,165 L de leche deben darnos 1 kg de queso. Si obtenemos más o menos queso querrá decir que nuestras hipótesis de partida no se han cumplido, y analizando los tres elementos básicos, sabremos la razón de la desviación:

- Nuestra leche tiene una composición diferente

- Nuestro queso tiene una composición diferente

- Nuestra recuperación de proteína no ha sido la adecuada, o ha sido diferente.

Si disponemos de la analítica correspondiente, podremos tomar las decisiones correctas; no es lo mismo actuar ante un problema de composición de leche que ante un problema de composición de queso o un problema de tecnología quesera (el extracto seco magro del queso es consecuencia de la tecnología quesera). Otros factores pueden influir directamente en el coeficiente de recuperación de proteína, por ejemplo, la cantidad de proteína coagulable (caseína) frente a la proteína total analizada puede variar a lo largo del año, y el análisis de proteína total no nos da una indicación de esta ratio.

## La materia grasa

Hasta aquí hemos hablado de proteína y ESM, pero ¿y la materia grasa?

En nuestro análisis de rendimiento hemos calculado también un % de recuperación de MG. Sin embargo, no utilizaremos este % para calcular el litraje, lo haremos tal como hemos visto, con la transformación de la proteína en ESM. La razón es que *la tecnología quesera nos permite actuar sobre el ESM del queso, pero la MG depende de la estandarización*, como veremos a continuación.

Como el coef G nos da los litros de leche que necesitamos para hacer 1 kg de queso, y tenemos una composición de nuestra leche, podemos saber la cantidad de MG que tenemos en esa leche. Por otra parte, sabemos la MG que hemos definido en nuestro queso de forma empírica, es decir, en la práctica: mediante un promedio de los diferentes análisis de nuestro producto que hemos ido obteniendo.

Según el coef G, necesitamos 9,165 L leche para hacer 1 kg de queso.

Según nuestra composición de leche, 1 L de leche tiene 31,13 g de MG, luego los 9,165 L de leche tendrán

$$
9,165\ L\ leche*\ \frac{33.37\ g\ MG}{1\ L\ leche} = 305.8361\ g\ MG
$$

Es decir, para fabricar 1 kg de queso necesitamos 9,165 L leche, que según su composición tienen 305.8361 g MG

Sin embargo, la analítica de nuestro queso nos dice que en 1 kg de queso tenemos un 28% de MG, es decir 280 g de MG po kilo de queso.

¿A qué se debe esta diferencia? La respuesta es: *a las pérdidas de MG en el proceso*, es decir, *a nuestro porcentaje de recuperación de MG.*

Podemos calcular este porcentaje mediante la fracción

$$
\frac{MG\ en\ el\ queso}{MG\ en\ la\ leche\ de\ fabricación}\ =\ \frac{280\ g\ MG/kg\ en\ el\ queso}{305.8361\ g\ MG/kg\ en\ la\ leche\ de\ fabricación} = 0,9155
$$

Es decir, nuestra recuperación teórica de MG es del 91,55%

¿Por qué *recuperación teórica*? Porque es la que resulta de hacer los cálculos según nuestros datos de composición de leche, composición del queso y recuperación de proteína.

De la misma forma que en el caso de la recuperación de proteína, si nuestra recuperación de MG es diferente de la calculada teóricamente, debemos encontrar la explicación en los mismos factores:

- Composición real de la leche

- Composición real del queso

- Variaciones en la tecnología

Estas variaciones implicarán una mayor pérdida de MG, que se irá en el suero de quesería, y que en parte puede recuperarse mediante un desnatado del suero.

## El estándar de fabricación

El razonamiento y cálculos que hemos ido realizando, se suelen recoger en lo que se llama un *estándar técnico de fabricación*. Este documento recoge los valores estándar de nuestra tecnología dada una composición media de nuestro queso obtenido (o un objetivo a obtener) y una composición de leche de partida

Un estándar técnico de fabricación tiene este aspecto:

| **ESTANDAR TECNICO**                             |        |
| ------------------------------------------------ | ------ |
| **Análisis salida sal**                          |        |
| EST %                                            | 55,00% |
| MG                                               | 28,00% |
| G/ES %                                           | 50,91% |
| HFD                                              | 62,50% |
| ESM                                              | 27,00% |
|                                                  |        |
| MP en cuba (g/L)                                 | 31,13  |
| Ratio recuperación MP (Rendimiento MP %)         | 94,65% |
| Coef G (ESM queso obtenido a partir de MP leche) | 29,46  |
| Litraje unitario                                 | 9,164  |
| Ratio recuperación MG (%)                        | 91,57% |
| MG teórica en la cuba (g/L)                      | 30,56  |
| MG Pérdidas brutas suero (g/L)                   | 2,814  |
| MG Pérdidas brutas suero (%)                     | 8,43%  |
| MG estándar en la mezcla (g/L)                   | 33,37  |

Llamamos MG estándar en la mezcla a la cantidad de MG que tendremos en la cuba, es decir, en nuestros 9,164 L de leche a fabricar. Esta MG puede provenir de la leche de partida o del resultado de añadir nata a la leche para conseguir la cantidad necesaria.

De la misma forma, llamamos MP en cuba a la cantidad de MP que hemos puesto en cuba, ya sea la de la leche de partida o del resultado de haber añadido proteínas a esta leche.

## El estándar técnico final

Como hemos visto, la construcción del estándar técnico y el seguimiento de la tecnología quesera no se hacen siguiendo el consumo de *litros de leche*, sino de la cantidad de proteína y grasa utilizadas. Por esta razón, la construcción del estándar debe proporcionar las cantidades de MG y MP necesarias para obtener 1 kg de queso, y no sólo el litraje en cuba

| **ESTANDAR TECNICO**                             |            |
| ------------------------------------------------ | ---------- |
| **Análisis salida sal**                          |            |
| EST %                                            | 55,00%     |
| MG                                               | 28,00%     |
| G/ES %                                           | 50,91%     |
| HFD                                              | 62,50%     |
| ESM                                              | 27,00%     |
|                                                  |            |
| MP en cuba (g/L)                                 | 31,13      |
| Ratio recuperación MP (Rendimiento MP %)         | 94,65%     |
| Coef G (ESM queso obtenido a partir de MP leche) | 29,46      |
| Litraje unitario                                 | 9,164      |
| Ratio recuperación MG (%)                        | 91,57%     |
| MG teórica en la cuba (g/L)                      | 30,56      |
| MG Pérdidas brutas suero (g/L)                   | 2,814      |
| MG Pérdidas brutas suero (%)                     | 8,43%      |
| MG estándar en la mezcla (g/L)                   | 33,37      |
| **Consumo MG total leche en cuba**               | **305,79** |
| **Consumo MP total leche en cuba**               | **285,26** |
| MG suero en cuba (g/L)                           | 0,00       |
| MG Pérddas suero neta (g/L)                      | 2,81       |
| MG Pérddas suero neta (%)                        | 8,43%      |
| MG STD sin nata de suero (g/L)                   | 33,37      |
| **Consumo MG (sólo MG comprada) (g/K queso)**    | **305,79** |
| **Consumo MP (sólo MP comprada) (g/K queso)**    | **285,26** |

En este caso, vemos un proceso de fabricación que *no* está recuperando la materia grasa del suero; las diferencias entre la MG en cuba y la MG en el queso se consideran pérdidas de proceso.

## La importancia de la estandarización de la leche

Como hemos visto, la tecnología quesera se construye para obtener un coeficiente de recuperación de proteína, y la materia grasa se retiene de forma más o menos pasiva en la matriz proteica.

Cuando la cantidad de MG en la leche es *superior* a lo que hemos definido en nuestro proceso, ocurrirán dos cosas:

- Una parte de este exceso de MG quedará retenida en la matriz proteica, subiendo la cantidad de MG en el queso, y, por tanto, variando la composición

- Otra parte de la MG se perderá en el suero, porque siempre están en relación con la cantidad total de MG de partida. Es decir, aumentarán nuestras pérdidas de MG en el suero.

Desgraciadamente, no es fácil calcular teóricamente cuánta MG vamos a retener en el queso y cuánta MG vamos a perder en el suero, porque estas cantidades no siguen una función conocida. Lo que sí sabemos es que

- Aumentaremos las perdidas

- Variaremos la composición del queso, lo que implica cambios en la textura y en el valor nutricional que podemos tener declarado

- Modificaremos la expulsión de suero de la matriz proteica, lo que implicará cambios en la cantidad de lactosa retenida en la cuajada, y en consecuencia, en las curvas de acidificación, extracto seco, etc

Cuando la MG es *inferior* a lo definido, estos cambios se producirán en sentido inverso, afectando a la composición del queso, pero también al comportamiento tecnológico.

La forma de minimizar las variaciones, manteniendo el producto con una composición constante, es:

- Procurar trabajar con leche que tenga el mismo contenido en MG y MP. Como la composición de la leche tiene una componente estacional, esto implica estandarizar la leche en MG y MP, *manteniendo constante la relación MG/MP*.

- Adaptar la tecnología estacionalmente, porque la variación estacional no sólo afecta al factor MG/MP sino a la proporción de caseína coagulable en el total de proteínas

Es muy importante recordar lo que hemos comentado antes al preparar el estándar técnico: *la tecnología nos va a permitir modificar el ESM del queso, pero la MG va a depender de la cantidad presente en la leche de fabricación*. **No podemos modificar la cantidad de grasa en el queso mediante la tecnología quesera en la cuba,** necesitamos preparar la leche con la cantidad de grasa necesaria para lo que se va a retener en el queso más las perdidas esperadas.

En la medida en la que no podamos realizar estas adaptaciones, tendremos que aceptar una variabilidad mayor en el producto, con dos consecuencias:

- Irregularidad en el producto final, que impacta en la aceptación por el consumidor

- Variación en el coste del producto, que puede llevarnos a situaciones de pérdidas no prevista

Por estas razones, es imprescindible hacer un seguimiento detallado de las desviaciones tecnológicas, de manera que podamos entender mejor nuestra tecnología y actuar de manera efectiva sobre sus causas, estableciendo los planes correctores oportunos.

Añado una tabla con un supuesto teórico y real, para ver cómo comparan los diferentes valores. El real se hace con una fabricación hipotética de 1000 kg de queso; el teórico se construye a partir del estándar teórico, aplicando los diferentes coeficientes a esta cantidad real, lo que nos da los diferentes valores teóricos que deberíamos haber tenido según nuestro estándar.

Las explicaciones deben hacerse a partir de estas desviaciones y el conocimiento de la tecnología, y a partir de esto, establecer los planes correctivos necesarios.

Conociendo el coste de la MG y de la MP pagada, se puede calcular el valor en euros de cada desviación, de forma que se pueda priorizar el plan de acción sobre las desviaciones con mayor impacto económico.

Hay una hoja Excel con todos los cálculos.

| **Análisis de desviaciones**                         | **Teórico** | **Real** |
| ---------------------------------------------------- | ----------- | -------: |
| Fabricación, KG                                      |             |    1.000 |
| EST                                                  | 55,00%      |   54,00% |
| MG                                                   | 28,00%      |   27,50% |
| ESM                                                  | 27,00%      |   26,50% |
| HFD                                                  | 62,50%      |   63,45% |
| G/ES                                                 | 50,91%      |   50,93% |
| Litros leche puestos en fab (cuba)                   | 9.164       |    8.780 |
| Composición leche en cuba MG (g/L)                   | 33,37       |    39,66 |
| Composición leche en cuba MP (g/L)                   | 31,13       |    31,15 |
| KMG puestos en fabricacion (cuba)                    | 306         |      348 |
| KMP puestos en fabricacion (cuba)                    | 285         |      274 |
| KMG Nata suero recuperada puesta en fab              | 0           |        0 |
| factor MG/MP leche cubas                             | 1,072       |    1,273 |
| g MP/L leche en cuba                                 | 31,130      |   31,150 |
| g MG/L leche en cuba                                 | 33,370      |   39,658 |
| MG teórica en cuba g/L                               | 30,556      |   31,321 |
| Litraje unitario (L/Kg)                              | 9,164       |    8,780 |
| Recup MG                                             | 91,57%      |   78,98% |
| Recup MP                                             | 94,65%      |   96,89% |
| gr MG queso/kg queso                                 | 280,000     |  275,000 |
| g ESM queso/kg queso                                 | 270,000     |  265,000 |
| factor MG/MP queso                                   | 1,037       |    1,038 |
| MG pérdida bruta (g/L)                               | 2,814       |    8,337 |
| MG pérdida bruta %                                   | 8,43%       |   21,02% |
| MG suero recuperada puesta en fab g/L                | 0,000       |    0,000 |
| MG pérdida neta g/L                                  | 2,814       |    8,337 |
| MG pérdida neta %                                    | 8,43%       |   21,02% |
|                                                      |             |          |
| Consumo técnico MG/kg queso (total cuba)             | 305,79      |   348,20 |
| Consumo técnico MP/kg queso                          | 285,26      |   273,50 |

