project:
  type: book
  output-dir: docs
execute:
  enabled: true

jupyter: python3

book:
  title: "Análisis de datos industriales usando Excel y Python"
  subtitle: "Notas para el master de FP en tecnología quesera"
  author: "Juan Riera"
  date: 2025-10-27
  date-format: short
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - 020-estad-entorno.qmd
    - 030-herramientas.qmd
    - 040-organizacion.qmd
    - 050-intro-python.ipynb  
    - 060-exploracion.ipynb
    - 070-estad-simple.qmd    
    - 080-caso1-camembert.ipynb 
    - 090-indice_dataframes.ipynb
    #- 060-forma-de-los-datos.qmd
    #- 070-relacion-xy.qmd
    #- 080-comunicacion.qmd
    #- 120-control-proc.qmd
    #- 130-sistema-medicion.qmd
    #- 140-mejora-procesos.qmd
    
  appendices: 
    - 150-media-centro-gravedad.qmd
    - 160-bibliografia.qmd

language:
  section-title-appendices: "Anexos"
  section-title-bibliography: "Bibliografía"

number-depth: 2

bibliography: bibliografia.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: book

author-title: AUTOR
published-title: PUBLICADO
