project:
  type: book
  output-dir: docs
execute:
  enabled: true

jupyter: python3

book:
  title: "Análisis de datos industriales usando Excel y Python"
  subtitle: "Notas para el master de FP en tecnología quesera"
  author: "Juan Riera"
  date: 2025-10-27
  date-format: short
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Herramientas y técnicas básicas"
      chapters: 
      - 020-estad-entorno.qmd
      - 030-herramientas.qmd
      - 040-organizacion.qmd
      - 050-intro-python.ipynb  
      - 060-exploracion.ipynb
      - 070-estad-simple.qmd    
      - 080-pract01-camembert.ipynb 
    #- part: "Análisis cuantitativo de la producción quesera"
    #  chapters: 
    #  - 085-intro-balance-materia.ipynb
    #  - 090-balance-materia.ipynb
    #  - 100-rendimientos.ipynb
    #  - 105-valoracion-bmat.ipynb
    #  - 110-pract02-rendimientos.ipynb 
    #  - 115-ficha-didáctica-cálculo-rend- con.python.ipynb 
    #- part: "Otras aplicaciones prácticas"
    #- chapters: 
    #  - 200-pract03-cueva.ypnb
    #  - 210-pract04-control-peso.ipynb
    #  - 220-control-proc.ipynb
    #  - 230-sistema-medicion.ipynb
    #  - 240-mejora-procesos.ipynb
    #  - 250-comunicacion.ipynb
  appendices: 
    - 800-media-centro-gravedad.qmd
    - 810-bibliografia.qmd
    - 900-indice_dataframes.ipynb
    
language:
  section-title-appendices: "Anexos"
  section-title-bibliography: "Bibliografía"

number-depth: 2

bibliography: bibliografia.bib

format:
   html:
     theme: cosmo
     link-external-newtab: true
 # pdf:
 #  documentclass: book

author-title: AUTOR
published-title: PUBLICADO
