project:
  type: book
  output-dir: docs
execute:
  enabled: true
jupyter: python3
book:
  title: "Análisis de datos industriales usando Excel y Python"
  subtitle: "Notas para el master de FP en tecnología quesera"
  author: "Juan Riera"
  date: 2025-10-27
  date-format: short
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Herramientas y técnicas básicas"
      chapters: 
      - 020-estad-entorno.qmd
      - 030-herramientas.qmd
      - 040-organizacion.qmd
      - 050-intro-python.ipynb  
      - 060-exploracion.ipynb
      - 070-estad-simple.qmd    
      - 080-pract01-camembert.ipynb 
    - part: "Aplicaciones practicas: Análisis cuantitativo de la producción quesera"
      chapters: 
      - 100-precio-leche.ipynb
      - 110-balance-materia.ipynb
    #  - 120-rendimientos.ipynb
    #  - 160-pract02-rendimientos.ipynb 
    #  - 170-ficha-didáctica-cálculo-rend- con.python.ipynb 
    #- part: "Otras aplicaciones prácticas"
    #- chapters: 
    #  - 200-pract03-cueva.ypnb
    #  - 210-pract04-control-peso.ipynb
    #  - 220-control-proc.ipynb
    #  - 230-sistema-medicion.ipynb
    #  - 240-mejora-procesos.ipynb
    #  - 250-comunicacion.ipynb
  appendices: 
    - 200-media-centro-gravedad.qmd
    - 210-simulacion-datos-fab.ipynb
    - 240-indice_dataframes.ipynb    
    - 300-bibliografia.qmd
language:
  section-title-appendices: "Apéndices"
  section-title-bibliography: "Bibliografía"
  label:
    appendix: "Apéndice"
number-depth: 2
format:
   html:
     theme: cosmo
     link-external-newtab: true
 # pdf:
 #  documentclass: book

bibliography: bibliografia.bib  
csl: estilos/ieee.csl
citeproc: true

author-title: AUTOR
published-title: PUBLICADO
