project:
  type: book
  output-dir: docs
execute:
  enabled: true

jupyter: python3

book:
  title: "Notas para el master de quesería"
  subtitle: ""
  author: "Juan Riera"
  date: 2025-10-22
  date-format: short
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - 001-intro.qmd
    - 005-herramientas.qmd
    - 010-introduccion-a-python.ipynb
    - 020-intro-colab.ipynb 
    - 030-organizacion.qmd  
    - 040-exploracion.qmd
    - 050-estad-simple.qmd
    - 060-forma-de-los-datos.qmd
    - 070-relacion-xy.qmd
    - 080-comunicacion.qmd
    - 120-control-proc.qmd
    - 130-sistema-medicion.qmd
    - 140-mejora-procesos.qmd
  appendices: 
    - 160-bibliografia.qmd

language:
  section-title-appendices: "Anexos"
  section-title-bibliography: "Bibliografía"

number-depth: 2

bibliography: bibliografia.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: book

author-title: AUTOR
published-title: PUBLICADO
