project:
  type: book
  output-dir: docs
execute:
  enabled: true
<<<<<<< HEAD
  freeze: auto
jupyter: python3
book:
  title: "La mejora continua en la producción quesera"
  subtitle: "Análisis de datos industriales usando Excel, Python y R"
=======
jupyter: python3
book:
  title: "Introducción al análisis de datos industriales usando Excel, Python y R"
  subtitle: "Notas para el master de FP en tecnología quesera"
>>>>>>> 508126e9fb31336481e7210747cee01fbc3147da
  author: "Juan Riera"
  date: 2025-10-27
  date-format: short
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Herramientas y técnicas básicas"
      chapters: 
      - 020-estad-entorno.qmd
      - 030-herramientas.qmd
      - 040-organizacion.qmd
<<<<<<< HEAD
      - 060-exploracion.qmd
      - 070-estad-basica.qmd    
      - 075-distribuciones.qmd      
      - 080-correlacion-regresion.qmd
      - 085-control-proc.qmd
      - 090-disexp.qmd
      - 095-comunicacion.qmd
    - part: "Aplicaciones en producción quesera"
      chapters: 
      - 100-camembert.qmd 
      - 105-precio-leche.qmd
      - 110-balance-materia.qmd
      - 120-rendimientos.qmd
    - part: "Otras aplicaciones"
      chapters: 
      - 160-sistema-medicion.qmd
    #  - 170-rd-contenido-efectivo.qmd      
    #  - 175-rd-contenido-efectivo.qmd
    #  - 190-panel-cata.qmd
    - part: "La metodología para la mejora continua"
      chapters: 
      - 250-variabilidad.qmd
      - 260-mejora-continua.qmd
  appendices: 
    - 300-apendice-entorno.qmd
    - 320-simulacion-datos-fab.qmd
    - 340-sistema-medicion-grr-simulador.qmd
    - 360-media-centro-gravedad.qmd
    - 380-indice_dataframes.qmd    
    - 400-bibliografia.qmd
=======
      - 050-intro-python.ipynb  
      - 060-exploracion.qmd
      - 070-estad-simple.qmd    
      - 080-pract01-camembert.ipynb 
    - part: "Aplicaciones practicas: Análisis cuantitativo de la producción quesera"
      chapters: 
      - 100-precio-leche.ipynb
      - 110-balance-materia.ipynb
      - 120-rendimientos.ipynb
    #  - 160-pract02-rendimientos.ipynb 
    #  - 170-ficha-didáctica-cálculo-rend- con.python.ipynb 
    #- part: "Otras aplicaciones prácticas"
    #- chapters: 
    #  - 200-pract03-cueva.ypnb
    #  - 210-pract04-control-peso.ipynb
    #  - 220-control-proc.ipynb
    #  - 230-sistema-medicion.ipynb
    #  - 240-mejora-procesos.ipynb
    #  - 250-comunicacion.ipynb
  appendices: 
    - 200-media-centro-gravedad.qmd
    - 210-simulacion-datos-fab.ipynb
    - 240-indice_dataframes.ipynb    
    - 300-bibliografia.qmd
>>>>>>> 508126e9fb31336481e7210747cee01fbc3147da
language:
  section-title-appendices: "Apéndices"
  section-title-bibliography: "Bibliografía"
  label:
    appendix: "Apéndice"
number-depth: 2
format:
   html:
     theme: cosmo
     link-external-newtab: true
<<<<<<< HEAD
=======
 # pdf:
 #  documentclass: book
>>>>>>> 508126e9fb31336481e7210747cee01fbc3147da

bibliography: bibliografia.bib  
csl: estilos/ieee.csl
citeproc: true

author-title: AUTOR
published-title: PUBLICADO
