format:
  pdf:
    documentclass: scrbook
    echo: false
    lang: es
    default-image-extension: png
    include-in-header:
      text: |
        \newenvironment{abstract}{}{}
        \usepackage{graphicx}
    filters:
      - webp-to-png.lua