{
  "hash": "13a1cb061946c185f67606fc5a9361b8",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlang: es\ndate-modified: '2026-03-12'\ntitle: Práctica 1a. Análisis exploratorio de una fabricación de queso camembert.\nabstract-title: Últimos cambios\nabstract: Reescritura completa del capítulo. Análisis de todas las variables del dataset. Añadido código R en pestañas alternativas. Análisis de coliformes como ejemplo de asimetría positiva. Cuaderno Colab disponible como práctica adicional.\nformat:\n  html:\n    code-fold: true\n    code-summary: Mostrar código\nengine: knitr\n---\n\n\n\n::: callout-note\n## Objetivos de aprendizaje\n\nAl finalizar este capítulo, el alumno será capaz de:\n\n- Aplicar el flujo de trabajo completo del análisis de datos (importar, limpiar, visualizar, comunicar) a un caso real de fabricación de queso camembert.\n- Detectar e interpretar errores en los datos mediante la inspección visual y estadística de cada variable.\n- Relacionar la forma de un histograma y un boxplot con las características del proceso que los genera, conectando lo aprendido en los capítulos 6 y 7.\n- Identificar y analizar la estacionalidad y la tendencia en una serie temporal de datos de fabricación.\n- Calcular y analizar una variable derivada (`hqd`) a partir de variables medidas, y relacionar su evolución temporal con las causas tecnológicas del proceso.\n- Interpretar la distribución asimétrica positiva de recuentos microbiológicos y extraer conclusiones sobre la higiene del proceso.\n- Formular hipótesis de trabajo a partir del análisis gráfico y contrastarlas con el conocimiento tecnológico y la experiencia del equipo.\n- Comunicar los resultados del análisis mediante un informe estructurado y un plan de acción priorizado.\n\nConceptos clave: **análisis exploratorio, flujo de trabajo, dato atípico, error de entrada, estacionalidad, tendencia, variable derivada, humedad del queso desnatado (hqd), distribución asimétrica positiva, recuento microbiológico, hipótesis de trabajo, plan de acción**.\n:::\n\n::: {.callout-tip}\n## Versión interactiva en Google Colab\n\nEste capítulo tiene una versión en formato cuaderno Jupyter con solo código Python que puedes abrir y ejecutar directamente en Google Colab, sin necesidad de instalar nada en tu ordenador:\n\n[Abrir versión sólo Python en Google Colab](https://colab.research.google.com/github/juanriera/master-queseria/blob/master/090-pract01-colab-camembert.ipynb)\n:::\n\nEn los capítulos anteriores hemos aprendido a describir datos mediante gráficos y estadísticos. Ahora vamos a aplicar todo lo aprendido a un caso real: el análisis exploratorio de una temporada completa de fabricación de queso camembert. Los datos corresponden a los análisis de control de calidad realizados durante el año 2020 en una quesería, con una o dos fabricaciones diarias a lo largo de los días laborables. El dataset contiene 211 observaciones y seis variables:\n\n- `est`: extracto seco total (%)\n- `mg`: materia grasa (%)\n- `ph`: pH del queso\n- `cloruros`: contenido en cloruros (%)\n- `coliformes`: recuento de bacterias coliformes (ufc/g)\n- `fabricacion`: número de fabricación del día (1 o 2)\n\n[Descargar los datos `camembert.csv`](https://raw.githubusercontent.com/juanriera/master-queseria/master/datos/camembert.csv)\n\n## Flujo de trabajo\n\nComo vimos en el capítulo 2, es muy conveniente establecer un flujo de trabajo regular, de forma que cada etapa del análisis se apoye en las anteriores:\n\n![Modelo de flujo de trabajo en la ciencia de datos, según Wickham](imagenes/080/data-science-explore.svg)\n\nVamos a ir desarrollando este flujo paso a paso.\n\n## Importar los datos\n\nCargamos el fichero desde GitHub. Si has descargado el fichero en tu ordenador, puedes adaptar la ruta de lectura según vimos en el capítulo anterior.\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nurl_datos = (\n    \"https://raw.githubusercontent.com/\"\n    \"juanriera/master-queseria/master/\"\n    \"datos/camembert.csv\"\n)\n\ntry:\n    df = pd.read_csv(url_datos,\n                     decimal=\",\",\n                     sep=';',\n                     encoding='ISO-8859-1')\n    print(\"Archivo cargado correctamente.\")\n    print(f\"Dimensiones: {df.shape}\")\nexcept Exception as e:\n    print(f\"Error al cargar el archivo: {e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArchivo cargado correctamente.\nDimensiones: (211, 7)\n```\n\n\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lubridate)\n\nurl_datos <- paste0(\n    \"https://raw.githubusercontent.com/\",\n    \"juanriera/master-queseria/master/\",\n    \"datos/camembert.csv\"\n)\n\ndf <- read_csv2(url_datos, locale = locale(decimal_mark = \",\"))\ncat(\"Dimensiones:\", nrow(df), \"x\", ncol(df), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDimensiones: 211 x 7 \n```\n\n\n:::\n:::\n\n:::\n\nInspeccionamos las primeras filas y la estructura del dataframe:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        fecha  fabricacion    est    mg    ph  cloruros  coliformes\n0  11/01/2020            1  46.68  24.0  4.85      1.50        80.0\n1  12/01/2020            1  48.09  25.0  4.67      1.61         0.0\n2  13/01/2020            1  45.97  24.0  4.71      1.48      9200.0\n3  14/01/2020            1  46.24  23.5  4.78      1.69        20.0\n4  15/01/2020            1  45.81  23.0  4.77      1.56       150.0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 211 entries, 0 to 210\nData columns (total 7 columns):\n #   Column       Non-Null Count  Dtype  \n---  ------       --------------  -----  \n 0   fecha        211 non-null    object \n 1   fabricacion  211 non-null    int64  \n 2   est          211 non-null    float64\n 3   mg           211 non-null    float64\n 4   ph           211 non-null    float64\n 5   cloruros     211 non-null    float64\n 6   coliformes   210 non-null    float64\ndtypes: float64(5), int64(1), object(1)\nmemory usage: 11.7+ KB\n```\n\n\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  fecha      fabricacion   est    mg    ph cloruros coliformes\n  <chr>            <dbl> <dbl> <dbl> <dbl>    <dbl>      <dbl>\n1 11/01/2020           1  46.7  24    4.85     1.5          80\n2 12/01/2020           1  48.1  25    4.67     1.61          0\n3 13/01/2020           1  46.0  24    4.71     1.48       9200\n4 14/01/2020           1  46.2  23.5  4.78     1.69         20\n5 15/01/2020           1  45.8  23    4.77     1.56        150\n6 18/01/2020           1  46    24    4.67     1.56         60\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 211\nColumns: 7\n$ fecha       <chr> \"11/01/2020\", \"12/01/2020\", \"13/01/2020\", \"14/01/2020\", \"1…\n$ fabricacion <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2…\n$ est         <dbl> 46.68, 48.09, 45.97, 46.24, 45.81, 46.00, 44.83, 45.82, 47…\n$ mg          <dbl> 24.0, 25.0, 24.0, 23.5, 23.0, 24.0, 23.5, 25.0, 24.0, 24.0…\n$ ph          <dbl> 4.85, 4.67, 4.71, 4.78, 4.77, 4.67, 4.73, 4.68, 4.75, 4.85…\n$ cloruros    <dbl> 1.50, 1.61, 1.48, 1.69, 1.56, 1.56, 1.39, 1.60, 1.54, 1.62…\n$ coliformes  <dbl> 80, 0, 9200, 20, 150, 60, 40, 40, 175, 340, 0, 0, 0, 0, 5,…\n```\n\n\n:::\n:::\n\n:::\n\nLa columna `fecha` aparece como tipo texto. La convertimos a formato fecha:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf['fecha'] = pd.to_datetime(\n    df['fecha'],\n    format='%d/%m/%Y',\n    errors='coerce'\n).values.astype('datetime64[D]')\n\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 211 entries, 0 to 210\nData columns (total 7 columns):\n #   Column       Non-Null Count  Dtype        \n---  ------       --------------  -----        \n 0   fecha        211 non-null    datetime64[s]\n 1   fabricacion  211 non-null    int64        \n 2   est          211 non-null    float64      \n 3   mg           211 non-null    float64      \n 4   ph           211 non-null    float64      \n 5   cloruros     211 non-null    float64      \n 6   coliformes   210 non-null    float64      \ndtypes: datetime64[s](1), float64(5), int64(1)\nmemory usage: 11.7 KB\n```\n\n\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> mutate(fecha = dmy(fecha))\nglimpse(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 211\nColumns: 7\n$ fecha       <date> 2020-01-11, 2020-01-12, 2020-01-13, 2020-01-14, 2020-01-1…\n$ fabricacion <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2…\n$ est         <dbl> 46.68, 48.09, 45.97, 46.24, 45.81, 46.00, 44.83, 45.82, 47…\n$ mg          <dbl> 24.0, 25.0, 24.0, 23.5, 23.0, 24.0, 23.5, 25.0, 24.0, 24.0…\n$ ph          <dbl> 4.85, 4.67, 4.71, 4.78, 4.77, 4.67, 4.73, 4.68, 4.75, 4.85…\n$ cloruros    <dbl> 1.50, 1.61, 1.48, 1.69, 1.56, 1.56, 1.39, 1.60, 1.54, 1.62…\n$ coliformes  <dbl> 80, 0, 9200, 20, 150, 60, 40, 40, 175, 340, 0, 0, 0, 0, 5,…\n```\n\n\n:::\n:::\n\n:::\n\n## Verificar los datos\n\nAntes de analizar, verificamos que los valores son plausibles. Calculamos un resumen estadístico de todas las variables:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf.describe().round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     fecha  fabricacion     est  ...      ph  cloruros  coliformes\ncount                  211       211.00  211.00  ...  211.00    211.00      210.00\nmean   2020-06-30 14:06:15         1.05   46.64  ...    4.68      1.45      650.88\nmin    2020-01-11 00:00:00         1.00   42.92  ...    4.35     -1.00        0.00\n25%    2020-03-21 12:00:00         1.00   45.61  ...    4.63      1.35        0.00\n50%    2020-07-04 00:00:00         1.00   46.60  ...    4.68      1.46       10.00\n75%    2020-10-05 12:00:00         1.00   47.47  ...    4.74      1.56      190.00\nmax    2020-12-29 00:00:00         2.00   52.61  ...    4.99      1.89    20200.00\nstd                    NaN         0.22    1.45  ...    0.08      0.23     2194.15\n\n[8 rows x 7 columns]\n```\n\n\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     fecha             fabricacion         est              mg       \n Min.   :2020-01-11   Min.   :1.000   Min.   :42.92   Min.   :21.50  \n 1st Qu.:2020-03-21   1st Qu.:1.000   1st Qu.:45.62   1st Qu.:23.00  \n Median :2020-07-04   Median :1.000   Median :46.60   Median :23.50  \n Mean   :2020-06-30   Mean   :1.052   Mean   :46.64   Mean   :23.73  \n 3rd Qu.:2020-10-05   3rd Qu.:1.000   3rd Qu.:47.47   3rd Qu.:24.50  \n Max.   :2020-12-29   Max.   :2.000   Max.   :52.61   Max.   :28.00  \n                                                                     \n       ph           cloruros        coliformes     \n Min.   :4.350   Min.   :-1.000   Min.   :    0.0  \n 1st Qu.:4.630   1st Qu.: 1.350   1st Qu.:    0.0  \n Median :4.680   Median : 1.460   Median :   10.0  \n Mean   :4.685   Mean   : 1.453   Mean   :  650.9  \n 3rd Qu.:4.735   3rd Qu.: 1.560   3rd Qu.:  190.0  \n Max.   :4.990   Max.   : 1.890   Max.   :20200.0  \n                                  NA's   :1        \n```\n\n\n:::\n:::\n\n:::\n\nYa en este primer resumen aparecen varias señales que merecen atención: el mínimo de `cloruros` es -1, lo que es físicamente imposible; el máximo de `est` es 52,61, claramente alejado del resto; y el rango de `coliformes` va de 0 a 20.200, con una dispersión enorme. Analizaremos cada variable con detalle en la sección siguiente.\n\n## Análisis variable a variable\n\n### Extracto seco total (`est`)\n\nComenzamos con la variable principal. En el capítulo 6 usamos el histograma y el boxplot para estudiar la forma de los datos; aquí los aplicamos directamente al caso real.\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['est'], kde=True, ax=ax1)\nax1.set_title(\"Histograma del extracto seco total\")\nax1.set_xlabel(\"EST (%)\")\n\nsns.boxplot(y=df['est'], ax=ax2)\nax2.set_title(\"Boxplot del extracto seco total\")\nax2.set_ylabel(\"EST (%)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-11-1.png){width=960}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\n\np1 <- ggplot(df, aes(x = est)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", alpha = 0.7) +\n  geom_density(aes(y = after_stat(count)), color = \"darkblue\") +\n  labs(title = \"Histograma del extracto seco total\",\n       x = \"EST (%)\", y = \"Frecuencia\") +\n  theme_bw()\n\np2 <- ggplot(df, aes(y = est)) +\n  geom_boxplot(fill = \"steelblue\", alpha = 0.7) +\n  labs(title = \"Boxplot del extracto seco total\",\n       y = \"EST (%)\") +\n  theme_bw()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-12-3.png){width=672}\n:::\n:::\n\n:::\n\nEl histograma muestra una distribución aproximadamente simétrica en torno a 46-47%, pero con una cola hacia la derecha y una barra aislada en torno a 52%. La curva de densidad muestra una pequeña elevación en ese extremo que no debería estar ahí si la distribución fuese una campana de Gauss limpia. El boxplot confirma la presencia de varios valores atípicos por encima de 50%.\n\n¿Son errores o valores reales? Para responderlo necesitamos contexto temporal.\n\n### Serie temporal del extracto seco\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf['fecha_index'] = pd.DatetimeIndex(df.fecha).normalize()\ndf.set_index('fecha_index', inplace=True)\ndf.sort_index(inplace=True)\n\nsns.lineplot(data=df, x='fecha', y='est')\nplt.title(\"Evolución anual del extracto seco total\")\nplt.xlabel(\"Fecha\")\nplt.ylabel(\"EST (%)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-13-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = fecha, y = est)) +\n  geom_line(color = \"steelblue\") +\n  labs(title = \"Evolución anual del extracto seco total\",\n       x = \"Fecha\", y = \"EST (%)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-14-3.png){width=672}\n:::\n:::\n\n:::\n\nLa serie temporal revela lo que el histograma no podía mostrar: los valores altos se concentran en los meses de verano, especialmente julio y agosto. El valor máximo de 52,61% corresponde al 21 de julio. Esto cambia completamente la interpretación: los valores por encima de 50% no son errores aislados sino parte de una desviación estacional sostenida durante varias semanas. La forma del histograma que parecía simplemente asimétrica era en realidad la mezcla de dos momentos del año con comportamientos distintos: exactamente el caso de distribución bimodal que estudiamos en el capítulo 6.\n\nVisualizamos la media semanal y su dispersión para ver la evolución con más claridad:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmedia_semanal = df[\"est\"].resample(\n    'W-MON', label='left', closed='left').mean()\ndt_semanal = df[\"est\"].resample(\n    'W-MON', label='left', closed='left').std()\n\nfig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 5), sharex=True)\n\nax1.plot(media_semanal, color='tab:blue')\nax1.set_title(\"Media y desviación típica semanal del extracto seco total\")\nax1.set_ylabel(\"Media EST (%)\")\nax1.grid(True, linestyle='--', alpha=0.6)\nax1.tick_params(labelbottom=False)\n\nax2.plot(dt_semanal, color='tab:orange')\nax2.set_ylabel(\"D. Típica EST\")\nax2.grid(True, linestyle='--', alpha=0.6)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-15-1.png){width=960}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lubridate)\n\ndf_semanal_est <- df |>\n  mutate(semana = floor_date(fecha, \"week\", week_start = 1)) |>\n  group_by(semana) |>\n  summarise(media = mean(est, na.rm = TRUE),\n            dt = sd(est, na.rm = TRUE))\n\np1 <- ggplot(df_semanal_est, aes(x = semana, y = media)) +\n  geom_line(color = \"steelblue\") +\n  labs(title = \"Media y desviación típica semanal del extracto seco total\",\n       y = \"Media EST (%)\") +\n  theme_bw() +\n  theme(axis.title.x = element_blank(), axis.text.x = element_blank())\n\np2 <- ggplot(df_semanal_est, aes(x = semana, y = dt)) +\n  geom_line(color = \"darkorange\") +\n  labs(x = \"Fecha\", y = \"D. Típica EST\") +\n  theme_bw()\n\np1 / p2\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-16-3.png){width=672}\n:::\n:::\n\n:::\n\n### Boxplot mensual del extracto seco\n\nEl boxplot por meses permite ver si los valores de julio son atípicos dentro de su propio contexto mensual:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport calendar\ndf_plot_est = df.copy()\ndf_plot_est['mes_abreviado'] = df_plot_est['fecha'].dt.strftime('%b')\nmeses_orden = [calendar.month_abbr[i] for i in range(1, 13)]\ndf_plot_est['mes_abreviado'] = pd.Categorical(\n    df_plot_est['mes_abreviado'],\n    categories=meses_orden,\n    ordered=True\n)\n\nsns.boxplot(x='mes_abreviado', y='est', data=df_plot_est)\nplt.title(\"Extracto seco total por mes\")\nplt.xlabel(\"Mes\")\nplt.ylabel(\"EST (%)\")\nplt.grid(axis='y', linestyle='--', alpha=0.7)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-17-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  mutate(mes = factor(month(fecha, label = TRUE))) |>\n  ggplot(aes(x = mes, y = est)) +\n  geom_boxplot(fill = \"steelblue\", alpha = 0.6) +\n  labs(title = \"Extracto seco total por mes\",\n       x = \"Mes\", y = \"EST (%)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-18-3.png){width=672}\n:::\n:::\n\n:::\n\nAhora la imagen es completamente distinta. En julio prácticamente todos los valores son altos: la mediana mensual de julio es la más alta del año, y el valor de 52,61% no es tan extremo dentro de ese mes. En cambio, en mayo aparece una dispersión muy baja seguida de un salto brusco en junio, que merece atención. Los meses de otoño e invierno muestran una distribución mucho más estable y centrada.\n\n### Materia grasa (`mg`)\n\nAplicamos el mismo análisis a la materia grasa:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['mg'], kde=True, ax=ax1)\nax1.set_title(\"Histograma de la materia grasa\")\nax1.set_xlabel(\"MG (%)\")\n\nsns.boxplot(y=df['mg'], ax=ax2)\nax2.set_title(\"Boxplot de la materia grasa\")\nax2.set_ylabel(\"MG (%)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-19-1.png){width=960}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(df, aes(x = mg)) +\n  geom_histogram(bins = 15, fill = \"steelblue\", alpha = 0.7) +\n  geom_density(aes(y = after_stat(count)), color = \"darkblue\") +\n  labs(title = \"Histograma de la materia grasa\",\n       x = \"MG (%)\", y = \"Frecuencia\") +\n  theme_bw()\n\np2 <- ggplot(df, aes(y = mg)) +\n  geom_boxplot(fill = \"steelblue\", alpha = 0.7) +\n  labs(title = \"Boxplot de la materia grasa\",\n       y = \"MG (%)\") +\n  theme_bw()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-20-3.png){width=672}\n:::\n:::\n\n:::\n\nEl histograma de la materia grasa muestra una distribución aproximadamente simétrica centrada en torno a 23,5%, pero el boxplot señala un valor atípico alto claramente separado del resto. Ese valor es 28%, registrado el 26 de enero, y es el único por encima de 27%. Puede ser un error de estandarización en el arranque del año, cuando la composición de la leche de invierno es más rica en grasa. Lo analizamos en la serie temporal:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsns.lineplot(data=df, x='fecha', y='mg')\nplt.title(\"Evolución anual de la materia grasa\")\nplt.xlabel(\"Fecha\")\nplt.ylabel(\"MG (%)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-21-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = fecha, y = mg)) +\n  geom_line(color = \"steelblue\") +\n  labs(title = \"Evolución anual de la materia grasa\",\n       x = \"Fecha\", y = \"MG (%)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-22-3.png){width=672}\n:::\n:::\n\n:::\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport calendar\ndf_plot2 = df.copy()\ndf_plot2['mes_abreviado'] = df_plot2['fecha'].dt.strftime('%b')\nmeses_orden = [calendar.month_abbr[i] for i in range(1, 13)]\ndf_plot2['mes_abreviado'] = pd.Categorical(\n    df_plot2['mes_abreviado'],\n    categories=meses_orden,\n    ordered=True\n)\n\nsns.boxplot(x='mes_abreviado', y='mg', data=df_plot2)\nplt.title(\"Materia grasa por mes\")\nplt.xlabel(\"Mes\")\nplt.ylabel(\"MG (%)\")\nplt.grid(axis='y', linestyle='--', alpha=0.7)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-23-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  mutate(mes = factor(month(fecha, label = TRUE))) |>\n  ggplot(aes(x = mes, y = mg)) +\n  geom_boxplot(fill = \"steelblue\", alpha = 0.6) +\n  labs(title = \"Materia grasa por mes\",\n       x = \"Mes\", y = \"MG (%)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-24-3.png){width=672}\n:::\n:::\n\n:::\nEl boxplot mensual de la materia grasa no muestra la misma estacionalidad pronunciada que el extracto seco. El valor de 28% de enero es claramente atípico respecto a su mes, pero el resto del año la materia grasa se mantiene en un rango bastante estable entre 22 y 26%. A partir de febrero se observa una tendencia moderada al alza hasta el verano, que se corrige progresivamente en el segundo semestre.\n\n### Análisis conjunto: gráfico de dispersión `est` vs `mg`\n\nHasta ahora hemos analizado cada variable por separado. El gráfico de dispersión nos permite ver si existe relación entre el extracto seco y la materia grasa:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\nsns.scatterplot(data=df, x='mg', y='est')\nplt.title(\"Relación entre materia grasa y extracto seco total\")\nplt.xlabel(\"Materia grasa (%)\")\nplt.ylabel(\"Extracto seco total (%)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-25-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lubridate)\n\nggplot(df, aes(x = mg, y = est)) +\n  geom_point(alpha = 0.5) +\n  labs(title = \"Relación entre materia grasa y extracto seco total\",\n       x = \"Materia grasa (%)\",\n       y = \"Extracto seco total (%)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-26-3.png){width=672}\n:::\n:::\n\n:::\n\nLa nube de puntos muestra una correlación positiva moderada: en general, cuando la materia grasa sube, el extracto seco también sube. Pero hay tres puntos que se separan claramente del conjunto: son los valores con `est` muy alto (en torno a 50-52%) combinados con `mg` normal o incluso baja. Estos puntos corresponden al período de verano que ya identificamos. El punto aislado con `mg` = 28% y `est` normal también destaca. Estos tres puntos anómalos son los que discutiremos con el equipo en la fase de conclusiones.\n\nColoreamos por trimestre para ver mejor la estructura estacional con una paleta legible:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf_plot = df.copy()\ndf_plot['trimestre'] = df_plot['fecha'].dt.quarter.map(\n    {1: 'T1 (Ene-Mar)', 2: 'T2 (Abr-Jun)',\n     3: 'T3 (Jul-Sep)', 4: 'T4 (Oct-Dic)'}\n)\n\nsns.scatterplot(data=df_plot, x='mg', y='est',\n                hue='trimestre',\n                palette=['steelblue','green','red','orange'],\n                s=50, alpha=0.7)\nplt.title(\"EST vs MG coloreado por trimestre\")\nplt.xlabel(\"Materia grasa (%)\")\nplt.ylabel(\"Extracto seco total (%)\")\nplt.legend(title='Trimestre', bbox_to_anchor=(1.05, 1))\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-27-1.png){width=672}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  mutate(trimestre = paste0(\"T\", quarter(fecha))) |>\n  ggplot(aes(x = mg, y = est, color = trimestre)) +\n  geom_point(alpha = 0.7, size = 2) +\n  scale_color_manual(\n    values = c(\"T1\" = \"steelblue\", \"T2\" = \"green4\",\n               \"T3\" = \"red\",       \"T4\" = \"orange\"),\n    name = \"Trimestre\"\n  ) +\n  labs(title = \"EST vs MG coloreado por trimestre\",\n       x = \"Materia grasa (%)\",\n       y = \"Extracto seco total (%)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-28-3.png){width=672}\n:::\n:::\n\n:::\n\nLos puntos del tercer trimestre (julio-septiembre) se sitúan claramente en la parte superior del gráfico, confirmando que la desviación de verano afecta a ambas variables simultáneamente, aunque con mayor intensidad en el extracto seco.\n\n### Variable derivada: humedad del queso desnatado (`hqd`)\n\nComo tecnólogos queseros, sabemos que un factor crítico de la textura del queso, y en consecuencia de su calidad, es la humedad del extracto seco desnatado. Este parámetro se calcula a partir del extracto seco y la materia grasa:\n\n$$\\text{hqd} = \\frac{(100 - \\text{est\\%})}{(100 - \\text{mg\\%})} \\times 100$$\n\nCreamos la nueva columna y analizamos su evolución:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf['hqd'] = ((100 - df['est']) / (100 - df['mg'])) * 100\n\nmedia_semanal = df[\"hqd\"].resample(\n    'W-MON', label='left', closed='left').mean()\ndt_semanal = df[\"hqd\"].resample(\n    'W-MON', label='left', closed='left').std()\n\nfig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 5), sharex=True)\n\nax1.plot(media_semanal, color='tab:blue')\nax1.set_title(\"Media y desviación típica semanal de la HQD\")\nax1.set_ylabel(\"Media HQD (%)\")\nax1.grid(True, linestyle='--', alpha=0.6)\nax1.tick_params(labelbottom=False)\n\nax2.plot(dt_semanal, color='tab:orange')\nax2.set_ylabel(\"D. Típica HQD\")\nax2.grid(True, linestyle='--', alpha=0.6)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-29-1.png){width=960}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\n\ndf <- df |> mutate(hqd = ((100 - est) / (100 - mg)) * 100)\n\ndf_semanal_hqd <- df |>\n  mutate(semana = floor_date(fecha, \"week\", week_start = 1)) |>\n  group_by(semana) |>\n  summarise(media = mean(hqd, na.rm = TRUE),\n            dt = sd(hqd, na.rm = TRUE))\n\np1 <- ggplot(df_semanal_hqd, aes(x = semana, y = media)) +\n  geom_line(color = \"steelblue\") +\n  labs(title = \"Media y desviación típica semanal de la HQD\",\n       y = \"Media HQD (%)\") +\n  theme_bw() +\n  theme(axis.title.x = element_blank(), axis.text.x = element_blank())\n\np2 <- ggplot(df_semanal_hqd, aes(x = semana, y = dt)) +\n  geom_line(color = \"darkorange\") +\n  labs(x = \"Fecha\", y = \"D. Típica HQD\") +\n  theme_bw()\n\np1 / p2\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-30-3.png){width=672}\n:::\n:::\n\n:::\n\nLa `hqd` muestra el patrón más revelador de todo el análisis. El fabricante mantiene la humedad razonablemente estable en torno al 70-71% durante la primera mitad del año, con algunos ajustes menores. En julio se produce una caída brusca hasta valores de 61-63%, la peor semana corresponde al 21 de julio con una `hqd` de 61,15%. Esta desviación de casi 10 puntos es muy significativa para la textura del camembert y explica las reclamaciones de queso demasiado seco que se recibieron en ese período.\n\n## Análisis de otras variables\n\n### pH\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['ph'], kde=True, ax=ax1)\nax1.set_title(\"Histograma del pH\")\nax1.set_xlabel(\"pH\")\n\nsns.boxplot(y=df['ph'], ax=ax2)\nax2.set_title(\"Boxplot del pH\")\nax2.set_ylabel(\"pH\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-31-1.png){width=960}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(df, aes(x = ph)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", alpha = 0.7) +\n  labs(title = \"Histograma del pH\", x = \"pH\", y = \"Frecuencia\") +\n  theme_bw()\n\np2 <- ggplot(df, aes(y = ph)) +\n  geom_boxplot(fill = \"steelblue\", alpha = 0.7) +\n  labs(title = \"Boxplot del pH\", y = \"pH\") +\n  theme_bw()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-32-3.png){width=672}\n:::\n:::\n\n:::\n\nEl pH muestra una distribución aproximadamente simétrica centrada en 4,68, con un rango habitual entre 4,5 y 4,9. El boxplot señala dos valores atípicos: el mínimo de 4,35 (18 de abril) y el máximo de 4,99 (25 de enero). El valor de 4,35 merece atención porque se aleja bastante del rango habitual; puede indicar una acidificación excesiva en esa fabricación o un error analítico. El pH y los cloruros se proponen como ejercicio de análisis completo al final del capítulo.\n\n### Cloruros\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['cloruros'], kde=True, ax=ax1)\nax1.set_title(\"Histograma de cloruros\")\nax1.set_xlabel(\"Cloruros (%)\")\n\nsns.boxplot(y=df['cloruros'], ax=ax2)\nax2.set_title(\"Boxplot de cloruros\")\nax2.set_ylabel(\"Cloruros (%)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-33-1.png){width=960}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(df, aes(x = cloruros)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", alpha = 0.7) +\n  labs(title = \"Histograma de cloruros\",\n       x = \"Cloruros (%)\", y = \"Frecuencia\") +\n  theme_bw()\n\np2 <- ggplot(df, aes(y = cloruros)) +\n  geom_boxplot(fill = \"steelblue\", alpha = 0.7) +\n  labs(title = \"Boxplot de cloruros\", y = \"Cloruros (%)\") +\n  theme_bw()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-34-3.png){width=672}\n:::\n:::\n\n:::\n\nEl histograma de cloruros muestra una distribución aproximadamente simétrica en torno a 1,45-1,50%, con un rango habitual entre 1,1 y 1,9%. El boxplot señala un único valor atípico muy llamativo: -1%, registrado el 11 de febrero. Un contenido en cloruros negativo es físicamente imposible, por lo que se trata sin duda de un error de entrada de datos: probablemente se introdujo el valor con el signo menos por error. Este valor debe tratarse como un dato ausente (`NaN`) antes de cualquier análisis posterior.\n\n### Coliformes: un ejemplo de distribución asimétrica positiva\n\nLos recuentos de bacterias coliformes merecen un análisis específico porque su distribución es radicalmente distinta a la del resto de variables. Antes de hacer el histograma, veamos los estadísticos básicos:\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(df['coliformes'].describe().round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncount      210.0\nmean       650.9\nstd       2194.1\nmin          0.0\n25%          0.0\n50%         10.0\n75%        190.0\nmax      20200.0\nName: coliformes, dtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"\\nValores = 0: {(df['coliformes']==0).sum()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nValores = 0: 89\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Valores > 1000: {(df['coliformes']>1000).sum()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValores > 1000: 28\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Valores > 5000: {(df['coliformes']>5000).sum()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValores > 5000: 9\n```\n\n\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  summarise(\n    n = sum(!is.na(coliformes)),\n    media = mean(coliformes, na.rm = TRUE),\n    mediana = median(coliformes, na.rm = TRUE),\n    dt = sd(coliformes, na.rm = TRUE),\n    min = min(coliformes, na.rm = TRUE),\n    max = max(coliformes, na.rm = TRUE),\n    ceros = sum(coliformes == 0, na.rm = TRUE),\n    mayor_1000 = sum(coliformes > 1000, na.rm = TRUE),\n    mayor_5000 = sum(coliformes > 5000, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 9\n      n media mediana    dt   min   max ceros mayor_1000 mayor_5000\n  <int> <dbl>   <dbl> <dbl> <dbl> <dbl> <int>      <int>      <int>\n1   210  651.      10 2194.     0 20200    89         28          9\n```\n\n\n:::\n:::\n\n:::\n\nLa mediana es 10 ufc/g pero la media es 651 ufc/g, casi 65 veces mayor. El 42% de los valores son exactamente cero, y hay 9 valores por encima de 5.000 ufc/g, con un máximo de 20.200 ufc/g el 12 de agosto. Esta diferencia enorme entre la mediana y la media es la señal característica de una distribución muy asimétrica positiva.\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['coliformes'].dropna(), bins=30, ax=ax1)\nax1.set_title(\"Histograma de coliformes (escala lineal)\")\nax1.set_xlabel(\"Coliformes (ufc/g)\")\n\n# escala logarítmica para ver mejor la distribución\ncol_nozero = df['coliformes'][df['coliformes'] > 0].dropna()\nsns.histplot(col_nozero, log_scale=True, bins=20, ax=ax2)\nax2.set_title(\"Histograma de coliformes (escala log)\")\nax2.set_xlabel(\"Coliformes (ufc/g, escala log)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-37-1.png){width=960}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(df, aes(x = coliformes)) +\n  geom_histogram(bins = 30, fill = \"steelblue\", alpha = 0.7) +\n  labs(title = \"Histograma de coliformes (escala lineal)\",\n       x = \"Coliformes (ufc/g)\", y = \"Frecuencia\") +\n  theme_bw()\n\np2 <- df |>\n  filter(coliformes > 0) |>\n  ggplot(aes(x = coliformes)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", alpha = 0.7) +\n  scale_x_log10() +\n  labs(title = \"Histograma de coliformes (escala log)\",\n       x = \"Coliformes (ufc/g, escala log)\", y = \"Frecuencia\") +\n  theme_bw()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-38-3.png){width=672}\n:::\n:::\n\n:::\n\nEn escala lineal, el histograma muestra una barra altísima en los valores bajos y una larga cola hacia la derecha: es la asimetría positiva extrema que veíamos en el capítulo 6 con los goles por partido, pero mucho más pronunciada. En escala logarítmica la distribución se hace visible con más detalle: la mayoría de los recuentos positivos están entre 10 y 1.000 ufc/g, y los valores muy altos son escasos pero existen.\n\n::: {.callout-note}\nEn microbiología alimentaria, los recuentos siempre siguen distribuciones asimétricas positivas: la mayoría de las muestras tienen recuentos bajos o nulos, pero ocasionalmente aparecen recuentos muy altos que reflejan episodios de contaminación. Por este motivo, en microbiología es habitual trabajar con la transformación logarítmica de los recuentos, que convierte la distribución asimétrica en una distribución más simétrica y más fácil de analizar. La media aritmética de los recuentos tiene muy poco sentido; es más informativo trabajar con la mediana o con la media geométrica (la media de los logaritmos).\n:::\n\nEste efecto es el mismo que el de un peso situado lejos del fulcro de una balanza: aunque sea un solo valor extremo, su distancia al centro multiplica su influencia sobre la media de forma desproporcionada. Por eso en variables con distribución muy asimétrica la media no es un buen descriptor del conjunto.\n\nVeamos la distribución mensual mediante un boxplot con los puntos individuales superpuestos. Como el logaritmo de cero no está definido, excluimos las muestras con recuento nulo: estas muestras no aportan información sobre la magnitud de la contaminación, y su inclusión aplastaría el gráfico hacia el cero haciendo ilegible el resto de la distribución. El alumno debe tener en cuenta que los meses con muchos ceros tendrán menos puntos representados, lo que también es información relevante sobre la higiene del proceso.\n\n::: panel-tabset\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport calendar\nimport numpy as np\ndf = df.reset_index(drop=True)\ndf_plot_col = df[df['coliformes'] > 0].copy()\ndf_plot_col['log_coliformes'] = np.log10(df_plot_col['coliformes'])\ndf_plot_col['mes_abreviado'] = df_plot_col['fecha'].dt.strftime('%b')\nmeses_orden = [calendar.month_abbr[i] for i in range(1, 13)]\ndf_plot_col['mes_abreviado'] = pd.Categorical(\n    df_plot_col['mes_abreviado'],\n    categories=meses_orden,\n    ordered=True\n)\n\nfig, ax = plt.subplots(figsize=(12, 5))\nsns.boxplot(data=df_plot_col, x='mes_abreviado', y='log_coliformes',\n            fliersize=0, color='lightgray', ax=ax)\nsns.stripplot(data=df_plot_col, x='mes_abreviado', y='log_coliformes',\n              jitter=True, size=3, alpha=0.5, ax=ax)\nax.set_title(\"Coliformes por mes: boxplot con puntos individuales (log₁₀)\")\nax.set_xlabel(\"Mes\")\nax.set_ylabel(\"log₁₀ Coliformes (ufc/g)\")\nax.grid(axis='y', linestyle='--', alpha=0.6)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-39-1.png){width=1152}\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  filter(coliformes > 0) |>\n  mutate(\n    log_coliformes = log10(coliformes),\n    mes = factor(month(fecha, label = TRUE))\n  ) |>\n  ggplot(aes(x = mes, y = log_coliformes)) +\n  geom_boxplot(fill = \"lightgray\", outlier.shape = NA) +\n  geom_jitter(width = 0.2, size = 1.5, alpha = 0.4,\n              color = \"darkblue\") +\n  labs(title = \"Coliformes por mes: boxplot con puntos individuales (log₁₀)\",\n       x = \"Mes\", y = expression(log[10]~\"Coliformes (ufc/g)\")) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](100-pract01-camembert_files/figure-html/bloque-40-3.png){width=672}\n:::\n:::\n\n:::\n\nEl gráfico muestra picos puntuales dispersos a lo largo del año, sin un patrón estacional claro y sostenido. La mediana de los valores se incrementa desde abril hasta julio, donde hay un máximo que parece significativo, ya que la caja del boxplot no se solapa con las anteriores. De manera coherente con la información agregada, los valores individuales se concentran en primavera y verano, coincidiendo con las temperaturas ambientales más altas y el período de sustituciones de personal en vacaciones. El valor máximo de 20.200 ufc/g del 12 de agosto es el más llamativo. En invierno los recuentos son en general más bajos y más homogéneos.\n\n## Conclusiones y plan de acción\n\n### Análisis de resultados\n\nUna vez explorados los datos de todas las variables, podemos formular las hipótesis de trabajo:\n\n1. A principio de año hay un valor anómalo de materia grasa (28%, 26 de enero) que puede haberse debido a un error en la estandarización coincidiendo con una leche de invierno más rica en grasa. A pesar de esto, la `hqd` se mantuvo estable, lo que indica que el fabricante corrigió el extracto seco para compensar.\n\n2. Hay un claro error de entrada en cloruros: el valor -1% del 11 de febrero es físicamente imposible y debe tratarse como dato ausente.\n\n3. El pH de 4,35 del 18 de abril se aleja significativamente del rango habitual y merece verificación con el laboratorio.\n\n4. La desviación más importante del año es el aumento sostenido del extracto seco en julio, con un máximo de 52,61% el 21 de julio, que produjo una caída de la `hqd` hasta 61,15%. Esta bajada de casi 10 puntos respecto al objetivo habitual de 70-71% es la causa directa de las reclamaciones por queso demasiado seco recibidas en ese período.\n\n5. Los recuentos de coliformes no muestran una tendencia estacional clara, pero los valores más altos se concentran en verano, coincidiendo con el período de aumento de temperatura ambiente que incrementa el riesgo de crecimiento bacteriano. Hay que tener en cuenta también las sustituciones de personal en vacaciones, que pueden añadir más variabilidad a los resultados analíticos como consecuencia de la menor experiencia analítica de las personas temporales.\n\n6. Hay tres puntos en el gráfico de dispersión `est` vs `mg` que se separan claramente del conjunto: son candidatos a revisión analítica antes de repetir el análisis definitivo.\n\n### Comunicar: discusión en equipo\n\nHemos presentado el análisis al equipo de fabricación, laboratorio y producción. Las conclusiones de la reunión son:\n\n- El responsable de fabricación confirma que hace ajustes estacionales en la estandarización a lo largo del año para mantener la `hqd` constante. En verano, debido a las temperaturas más altas en las zonas de distribución, la práctica habitual es bajar moderadamente la `hqd` para evitar una proteólisis excesiva durante el ciclo de comercialización.\n- Este año el quesero fue sustituido durante vacaciones por una persona con menos experiencia, que forzó el extracto seco más de lo debido. Las reclamaciones de los clientes por queso demasiado seco en agosto confirman esta hipótesis.\n- El laboratorio confirma que los tres valores anómalos del gráfico de dispersión pueden corresponder a análisis incorrectos, y recomienda no tenerlos en cuenta en el análisis definitivo.\n- El valor negativo de cloruros es claramente un error de entrada de datos.\n\n### Plan de acción\n\nA la vista del análisis, el equipo propone las siguientes acciones:\n\n1. Revisar diariamente la composición de la leche para evitar errores de estandarización, especialmente en los cambios de estación.\n2. Mejorar la formación de las personas que cubren los puntos clave (quesero, analistas) en períodos de vacaciones o enfermedad, anticipando los ciclos de formación.\n3. Revisar los métodos analíticos con el laboratorio y valorar un estudio de precisión, incluyendo la variabilidad entre analistas.\n4. Establecer un sistema de seguimiento ágil de la `hqd` en tiempo real, para detectar desviaciones antes de que afecten al producto en el punto de venta.\n5. Valorar si los problemas de proteólisis en verano son generales o se concentran en clientes específicos con peores condiciones de conservación, ajustando el objetivo de `hqd` de verano de forma más precisa.\n6. Repetir el análisis eliminando los valores erróneos identificados, para verificar que las conclusiones se mantienen.\n\nDado que la capacidad del equipo es limitada, en sucesivas reuniones se priorizarán las acciones de mayor impacto y se establecerán indicadores que se publicarán semanalmente en paneles de planta.\n\n## Resumen del capítulo\n\nEn este capítulo hemos aplicado el flujo de trabajo completo del análisis de datos a una fabricación real de queso camembert. El análisis variable a variable ha permitido identificar errores de entrada (el valor negativo de cloruros), valores atípicos que requieren verificación (el pH de 4,35 en abril, el valor de materia grasa de 28% en enero) y la desviación estacional más importante del año: el aumento sostenido del extracto seco en julio, que produjo una caída de la humedad del queso desnatado de casi 10 puntos y originó reclamaciones de los clientes.\n\nLa serie temporal ha sido la herramienta clave para interpretar correctamente lo que el histograma mostraba como una simple distribución asimétrica: lo que parecía un valor atípico aislado era en realidad parte de una desviación estacional sostenida durante varias semanas. El análisis de los coliformes ha ilustrado con datos reales el concepto de distribución asimétrica positiva extrema, característica de los recuentos microbiológicos, y la razón por la que la mediana es más informativa que la media en este tipo de variables.\n\nEl capítulo concluye con una fase de comunicación en equipo que transforma el análisis estadístico en hipótesis de trabajo contrastadas con el conocimiento tecnológico y en un plan de acción priorizado. En el capítulo siguiente nos enfrentaremos al análisis de las entradas de leche en una gran fábrica de queso.\n\n## Ejercicios propuestos\n\n### Ejercicio 1: análisis completo de pH y cloruros\n\nRealiza el análisis exploratorio completo de las variables `ph` y `cloruros`, siguiendo la misma metodología aplicada a `est` y `mg` en este capítulo:\n\n- Histograma y boxplot\n- Serie temporal anual\n- Boxplot mensual\n- Interpretación de los valores atípicos detectados\n\nPara los cloruros, filtra previamente el valor negativo convirtiéndolo en `NaN` antes de representar los gráficos.\n\n### Ejercicio 2: repetir el análisis sin los valores erróneos\n\nEl laboratorio ha confirmado que los tres puntos anómalos del gráfico de dispersión `est` vs `mg` son probablemente errores analíticos. Utiliza Python o R para filtrarlos y repite el análisis completo con el dataset corregido. ¿Cambian las conclusiones?\n\nComo referencia, los criterios de filtrado son: valores de `mg` superiores a 27%, valores de `est` superiores a 52%, y valores con `mg` inferior a 22% y `est` superior a 48% de forma simultánea.\n\n### Ejercicio 3 (avanzado): transformación logarítmica de coliformes\n\nLos recuentos microbiológicos se analizan habitualmente en escala logarítmica. Crea una nueva columna `log_coliformes` con el logaritmo en base 10 de los recuentos (excluyendo los ceros), y compara el histograma de la escala lineal con el de la escala logarítmica. ¿Cómo cambia la forma de la distribución? ¿Qué valores de la escala logarítmica corresponden a los límites microbiológicos habituales en queso camembert?\n\n## Práctica en Google Colab\nEn este enlace se proporciona acceso a los datos de este capítulo en un cuaderno de Google Colab, para practicar de forma interactiva el código Python desde ese entorno.\n\n[Abrir este cuaderno en Google Colab](https://colab.research.google.com/github/juanriera/master-queseria/blob/master/090-pract01-colab-camembert.ipynb)",
    "supporting": [
      "100-pract01-camembert_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}