{
  "hash": "57ffcff5dbe56eaebfa8ce2dfdcc5478",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlang: es\ndate-modified: '2026-03-14'\ntitle: \"Proceso de dosificación y control de peso en el envasado.\"\nsubtitle: \"Aplicación práctica del RD 1801/2008 de contenido efectivo\"\nengine: knitr\n---\n\n::: callout-note\n## Objetivos de aprendizaje\n\nAl finalizar este capítulo, el alumno será capaz de:\n\n- Identificar los conceptos clave del RD 1801/2008: peso nominal, error máximo tolerado, límites T1 y T2.\n- Explicar la relación entre la dispersión del proceso de llenado y la necesidad de sobredosificación para cumplir la legislación.\n- Calcular la proporción de envases defectuosos a partir de los parámetros de la distribución normal.\n- Determinar el peso medio óptimo de llenado en función de la dispersión del proceso.\n- Cuantificar el coste económico de la sobredosificación y el beneficio de reducir la variabilidad.\n\nConceptos clave: **contenido efectivo, peso nominal, error máximo tolerado (EMDT), límite T1, límite T2, sobredosificación, capacidad de proceso**.\n:::\n\n::: {.callout-warning}\n## Conocimientos requeridos para este capítulo\nEl contenido que se presenta a continuación requiere una buena comprensión previa de los capítulos 6 (Medidas centrales y medidas de dispersión: la media y la varianza), 7 (Distribuciones de probabilidad y la distribución normal) y 9 (Control estadístico de procesos).\n:::\n\n::: {.callout-tip}\n## Sobre el código de este capítulo\nLos bloques de código que generan gráficos complejos aparecen **ocultos por defecto**. Puedes mostrarlos haciendo clic en \"Mostrar código\". Si quieres entender qué hace un bloque, cópialo y pégalo en un asistente de IA como Gemini, ChatGPT o Claude y pregúntale: *\"Explícame este código línea a línea, en lenguaje sencillo\"*.\n:::\n\n## Introducción\n\nEn la industria alimentaria es frecuente que, con el fin de facilitar el acto de compra y el consumo, el fabricante ofrezca sus productos envasados en envases individuales (por ejemplo, yogures), o dividiendo productos más grandes (por ejemplo, mediante porcionado de queso en cuñas).\n\nCuando un fabricante comercializa un producto envasado o porcionado, puede hacerlo de dos formas:\n\n- **A peso variable**: El consumidor adquiere una cantidad que se pesa en el momento de la venta (por ejemplo, queso al corte o jamón en lonchas en el mostrador). El precio final depende del peso real entregado, el cual se indica en una etiqueta impresa tras el pesaje.\n\n- **A peso fijo**: El envase se presenta cerrado y etiquetado por el fabricante con un **peso nominal declarado** (como un yogur de 125 g o un queso fresco de 500 g). El contenido físico del envase se denomina **peso real** o **contenido efectivo**. Este es el escenario regulado por el RD 1801/2008, conocido como la **normativa de contenido efectivo**.\n\n## El RD 1801/2008: qué regula y a quién afecta\n\nEl Real Decreto 1801/2008, de 3 de noviembre, establece las normas relativas a las cantidades nominales y al control del contenido efectivo en España. Esta normativa transpone la Directiva europea 2007/45/CE y es de aplicación obligatoria para cualquier empresa que comercialice productos con un peso o volumen nominal indicado en el envase.\n\nEn la industria láctea, esta norma afecta directamente a productos como yogures, quesos frescos, leche o nata. Ya sea un yogur de 125 g, un bote de nata de 200 ml o un queso de 500 g, todos están sujetos a estas disposiciones.\n\nLa norma parte de un principio de protección: el consumidor tiene derecho a recibir la cantidad indicada; sin embargo, reconoce una realidad técnica: ningún proceso de llenado industrial es perfecto. Siempre existirá una dispersión natural alrededor del valor objetivo. Por ello, el RD no exige que cada envase pese exactamente lo mismo, sino que define unas tolerancias estadísticas que el fabricante debe gestionar mediante el **control de procesos**.\n\nLa legislación garantiza el rigor del fabricante al declarar el peso para evitar fraudes al consumidor. Las autoridades competentes son las responsables de supervisar que las empresas cumplan con estos estándares. Para ello, se realizan inspecciones aleatorias tanto en los puntos de venta como en las propias plantas de envasado, verificando que los lotes de producción respetan las tolerancias permitidas por la ley.\n\n## Declaración del peso en el envase\n\nExisten dos modalidades para que un fabricante declare el peso de sus productos:\n\n- **Sin signo de estimación**: El fabricante declara el peso nominal pero no se acoge al sistema de control estadístico de la Unión Europea. En este caso, debe garantizar que todos y cada uno de sus envases cumplen estrictamente con el contenido declarado. Al no seguir el protocolo específico de promedios y tolerancias del RD, no puede mostrar la letra \"e\" en su etiquetado.\n\n- **Bajo la norma de contenido efectivo (Signo <img src=\"imagenes/signo-e.svg\" width=\"24\"> )**: El fabricante realiza controles estadísticos de peso en cada lote para demostrar que cumple con las tolerancias legales. Este sistema le permite imprimir el **signo de estimación** (una letra **e** minúscula) en el etiquetado. Este símbolo funciona como un \"pasaporte\" que garantiza que el producto cumple con los estándares europeos, facilitando su comercialización en todo el mercado común.\n\n![Signo de estimacion que indica que el proceso de envasado está bajo control estadístico y se ajusta al RD 1801/2008 ](imagenes/signo-e.svg){.column-margin}\n\n## Los conceptos clave\n\n### Peso nominal ($Q_n$)\n\nEs el peso o volumen declarado en el envase por el fabricante.\n\n### Los límites de tolerancia: Error máximo por defecto tolerado (EMDT)\n Para gestionar la dispersión inevitable del envasado, el RD 1801/2008 define el **Error Máximo por Defecto Tolerado (EMDT)**. Este valor es la diferencia máxima por defecto permitida entre el peso nominal etiquetado y el contenido real del envase (peso de menos).\n\nLa siguiente tabla del RD nos indica cuál es el **EMDT** para envases de diferentes pesos o volúmenes nominales:\n\n![Tabla con los EMDT para el control no destructivo](imagenes/tabla1.png)\n\nLa norma establece también que cuando el tamaño del lote sea inferior a 100 envases, el control no destructivo se realizará sobre la totalidad del mismo.\n \nVemos que el EMDT no es un valor fijo para todos los productos; se calcula en función del peso nominal ($Q_n$) siguiendo una escala establecida por la ley. Por ejemplo:\n\n- Para un envase de 150 g, el EMDT es el 4,5 % del peso (6,75 g).\n- Para un envase de 500 g, el EMDT es de 15 g (un valor fijo en ese tramo).\n\nA partir de este valor, la normativa establece dos umbrales críticos de control que todo fabricante debe monitorizar en sus gráficos:\n\n- **Umbral de Tolerancia** ($Q_n - \\text{EMDT}$): Los envases que pesan menos de este valor se consideran **deficientes**. Solo se permite un máximo del 2,5 % de estos envases en cada lote.\n- **Umbral de Defecto Crítico** ($Q_n - 2 \\times \\text{EMDT}$): Es el **límite de rechazo**. Ningún envase puede pesar menos de este valor; de lo contrario, el lote es rechazado automáticamente y no puede ser comercializado.\n\nLa norma define también el tamaño de muestra necesario para hacer el control según el tamaño del lote, y los criterios de aceptación o rechazo.\n\n![Criterios de rechazo](imagenes/tabla.png)\n\nPara facilitar el control, la norma establece un muestreo en dos etapas: en una primera etapa tomamos una muestra que es la mitad de la muestra máxima, y verificamos el resultado. Si los criterios de aceptación no se cumplen, tomamos una segunda muestra y acumulamos los valores de ambas para determinar la aceptación o rechazo. El muestreo en dos etapas funciona como una \"segunda oportunidad\": si con la primera muestra el resultado es dudoso, la ley nos obliga a ampliar la inspección antes de decidir si rechazamos todo el lote.\n\nEn resumen, entregar menos peso de lo permitido por la norma constituye un **fraude** y es sancionable. Entregar peso por encima del peso nominal tiene un coste económico: estamos *regalando* producto. \n\n::: callout-tip\n## Las tres reglas del envasador\n\nPara que un lote de productos de peso fijo se considere conforme a la ley, el fabricante debe garantizar que su proceso de envasado cumple simultáneamente tres requisitos estadísticos:\n\n- **Criterio de la Media**: El contenido efectivo (peso real) medio de los envases del lote no debe ser inferior al contenido nominal ($Q_n$) marcado en la etiqueta. Es decir, el promedio de lo que entregas al mercado debe ser, como mínimo, lo que prometes.\n- **Criterio de Tolerancia Individual ($EMDT$)**: La proporción de envases que presentan un error negativo superior al Error Máximo por Defecto Tolerado ($EMDT$) debe ser lo suficientemente pequeña (menos del 2,5 % del lote) para que sea aceptable en una inspección por muestreo.\n- **Criterio de Defecto Crítico**: No se permite la comercialización de ningún envase que tenga un error negativo superior al doble del error máximo tolerado ($2 \\times EMDT$). Estos envases se consideran defectuosos de forma individual y deben ser retirados de la cadena.\n:::\n\n![Los diferentes conceptos del RD 1801/2008 sobre la curva normal ](imagenes/rd-1801.svg)\n\n## Ejemplo práctico: el caso de un proceso de envasado de yogur\n\nSupongamos una linea de envasado de yogures de 150 g, con una cadencia de llenado de un envase cada 3 segundos.\n\nSegún la tabla anterior, para productos entre 100 g y 200 g, el EMDT es el **4,5%** del peso nominal:\n$$\n\\text{EMDT} = 4{,}5\\% \\times 150 = 6{,}75 \\text{ g} \n$$\n\n### Límite T1: envase defectuoso\n\nUn envase se considera **defectuoso** cuando su contenido es inferior a $Q_n - \\text{EMDT}$:\n\n$$T_1 = 150 - 6{,}75 = 143{,}25 \\text{ g}$$\n\nLa norma permite un máximo del **2,5%** de envases defectuosos (por debajo de T1) en un lote.\n\n### Límite T2: envase no conforme\n\nUn envase se considera **no conforme** (prohibido comercializar) cuando su contenido es inferior a $Q_n - 2 \\times \\text{EMDT}$:\n\n$$T_2 = 150 - 2 \\times 6{,}75 = 136{,}5 \\text{ g}$$\n\nLa norma **no permite ningún envase** por debajo de T2. Un solo envase no conforme en una inspección puede dar lugar a sanción.\n\n::: {.callout-note}\n## Resumen de límites para yogur de 150 g\n\n| Concepto | Valor |\n|----------|-------|\n| Peso nominal ($Q_n$) | 150,0 g |\n| Error máximo tolerado (EMDT) | 6,75 g |\n| Umbral de tolerancia (límite T1) (defectuoso) | 143,25 g |\n| Umbral crítico (límite T2) | 136,5 g |\n| Máximo de envases bajo T1 | 2,5% del lote |\n| Envases bajo T2 | 0 (ninguno permitido) |\n:::\n\n### El procedimiento de muestreo del RD\n\nLa norma no evalúa el cumplimiento envase a envase sino mediante un **muestreo estadístico** del lote. Para un lote de producción de hasta 10.000 unidades (el caso habitual en una línea de yogures), el procedimiento es el siguiente:\n\n**Primera etapa:** se toman **80 envases** al azar del lote y se pesan individualmente. El lote se **acepta** en esta etapa si:\n\n- Ningún envase tiene un peso inferior a T2 (136,5 g), **y**\n- 3 o menos envases tienen un peso inferior a T1 (143,25 g)\n\nEl lote se **rechaza** directamente si:\n\n- Algún envase tiene un peso inferior a T2, **o**\n- 7 o más envases tienen un peso inferior a T1\n\nSi el número de envases bajo T1 está es superir a 3 e inferior a 7, se pasa a la segunda etapa.\n\n**Segunda etapa:** se toman **otros 80 envases** y se acumulan con los de la primera (160 en total). \n\n- El lote se acepta si no hay ningún envase bajo T2 y hay 8 o menos bajo T1. \n- El lote se rechaza si hay alguno bajo T2 o 9 o más bajo T1.\n\n::: {.callout-note}\n## Rechazo: cualquiera de las dos condiciones; aceptación: las dos a la vez\nPara **rechazar** el lote basta con que se cumpla **cualquiera** de las dos condiciones de rechazo. Para **aceptar** el lote deben cumplirse **las dos** condiciones de aceptación simultáneamente. Es un criterio conservador que protege al consumidor.\n:::\n\n### Control mediante muestra consolidada (n = 160)\nEn líneas de producción de alto rendimiento, es frecuente optar por un muestreo consolidado en lugar de las dos etapas. En este caso, se extrae directamente una muestra de 160 unidades (equivalente a la suma de las dos etapas legales) para tomar una decisión única sobre el lote. Bajo esta modalidad, los criterios de decisión para un lote de 9.600 unidades son directos:\n\n- **Rechazo por defecto crítico**: El lote se rechaza inmediatamente si aparece 1 solo envase con un peso inferior a 136,5 g ($Q_n - 2 \\times EMDT$).\n- **Rechazo por envases deficientes**: El lote se rechaza si se contabilizan 9 o más envases con un peso inferior a 143,25 g ($Q_n - EMDT$).\n- **Aceptación del lote**: El lote se acepta únicamente si no hay ningún envase crítico y el número de envases deficientes es 8 o inferior.\n\n## El problema estadístico: dispersión y sobredosificación\n\nAquí es donde entra la distribución normal que estudiamos en el capítulo dedicado a las distribuciones de probabilidad. Si el proceso de llenado sigue una distribución normal con media $\\mu$ y desviación típica $\\sigma$, la proporción de envases por debajo de T1 es el área bajo la curva a la izquierda de T1:\n\n$$P(\\text{peso} < T_1) = P\\left(Z < \\frac{T_1 - \\mu}{\\sigma}\\right)$$\n\nPara cumplir la norma, esa proporción debe ser inferior al 2,5%. En una distribución normal, el 2,5% en la cola izquierda corresponde a $Z = -1{,}96$. Esto significa que T1 debe estar al menos 1,96 desviaciones típicas por debajo de la media:\n\n$$\\mu \\geq T_1 + 1{,}96 \\times \\sigma = 145{,}5 + 1{,}96 \\times \\sigma$$\n\nSi $\\sigma = 1{,}5$ g (proceso preciso): $\\mu \\geq 145{,}5 + 2{,}94 = 148{,}44$ g\n\nSi $\\sigma = 3{,}0$ g (proceso impreciso): $\\mu \\geq 145{,}5 + 5{,}88 = 151{,}38$ g\n\nLa diferencia es enorme: con un proceso impreciso hay que dosificar casi 3 gramos más por envase solo para cumplir la norma. Esto es la **sobredosificación**: producto que se entrega al consumidor por encima del peso nominal sin cobrar por ello.\n\nEn el capítulo dedicado al control estadístico de procesos vimos cómo medir y seguir la variabilidad de un proceso de llenado mediante gráficos de control, y cómo los índices de capacidad $C_p$ y $C_{pk}$ cuantifican la relación entre la variabilidad natural del proceso y los límites de especificación. En este capítulo aplicamos esos conceptos al caso concreto del RD 1801/2008: el límite T1 es el límite de especificación inferior, y la capacidad del proceso determina directamente cuánta sobredosificación es necesaria para cumplirlo.\n\nPara este ajuste, usaremos el **Peso Nominal ($Q_n$) de 150 g**. \n\nComo vimos antes, para este tramo (100 a 200 g), el **EMDT es el 4,5%**, lo que equivale a **6,75 g**. \n\n* El primer límite (antes llamado T1) es $150 - 6,75 = \\mathbf{143,25\\ g}$.\n* El segundo límite o \"Defecto Crítico\" (antes T2) es $150 - (2 \\times 6,75) = \\mathbf{136,5\\ g}$.\n\n### Procedimiento de Control de Lote ($Q_n = 150\\ g$)\n\nEn nuestro caso, consideramos **lote** la producción realizada en un día, que es de **9.600 unidades**. Al ser un lote superior a 3.201 unidades, la norma establece que cada etapa de muestreo debe ser de **80 unidades**. Nuestro **EMDT** es **6,75 gramos**, luego:\n\n* **Envase deficiente:** Aquel que tiene un peso inferior a **143,25 g**.\n* **Límite Crítico ($2 \\times EMDT$):** No puede aparecer **ningún** envase con peso inferior a **136,5 g**.\n\nEl procedimiento que seguimos es el siguiente:\n\n**Rechazamos** el lote si en la primera muestra de **80 unidades** nos aparecen:\n* **1** o más envases con un peso inferior a **136,5 g**, o\n* **7** o más envases con un peso inferior a **143,25 g** (envases deficientes).\n\n**Aceptamos** el lote si en la primera muestra de **80 unidades** nos aparecen:\n* **Ningún** envase con un peso inferior a **136,5 g**, y\n* **3** o menos envases con un peso inferior a **143,25 g** (envases deficientes).\n\nSi en la primera muestra aparecen **entre 4 y 6 envases deficientes** (la zona de duda entre el $Ac=3$ y el $Re=7$), tomamos una segunda muestra de **80 unidades** y acumulamos los resultados.\n\n**Rechazamos** el lote si en el total de las dos muestras (**160 unidades**) nos aparecen:\n* **1** o más envases con un peso inferior a **136,5 g**, o\n* **9** o más envases con un peso inferior a **143,25 g** (envases deficientes).\n\n**Aceptamos** el lote si en el total de las dos muestras (**160 unidades**) nos aparecen:\n* **Ningún** envase con un peso inferior a **136,5 g**, y\n* **8** o menos envases con un peso inferior a **143,25 g** (envases deficientes).\n\nEs importante recordar que el lote se rechaza si se incumple **cualquiera** de las dos condiciones (ya sea por encontrar un solo envase crítico o por exceder el número de deficientes).\n\n---\n\n### Resumen de Criterios (Tabla del RD para Lote > 3.200)\n\n| Etapa | Muestra | Ac (Aceptación) | Re (Rechazo) |\n| :--- | :--- | :--- | :--- |\n| **1ª Etapa** | 80 uds | **3** deficientes | **7** deficientes |\n| **Total (1ª+2ª)** | 160 uds | **8** deficientes | **9** deficientes |\n| **Cualquier etapa** | - | **0** críticos ($< 136,5$) | **1** crítico ($< 136,5$) |\n\nEs importante insistir en que **rechazamos** el lote si se cumple **una cualquiera** de las dos condiciones de rechazo; y que para **aceptar** el lote, deben darse **las dos** condiciones de aceptación.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read.csv(\"datos/simulacion_envasado_yogur.csv\")\n```\n:::\n\n\n\nComo siempre, lo primero que hacemos es un resumen de los datos:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n hora_envasado          peso_g     \n Length:9600        Min.   :135.8  \n Class :character   1st Qu.:149.8  \n Mode  :character   Median :151.8  \n                    Mean   :151.6  \n                    3rd Qu.:153.7  \n                    Max.   :162.8  \n```\n\n\n:::\n:::\n\n\nEl peso medio es $151,6 g$, con un mínimo de $135.8 g$ y un máximo de $162,8 g$.\n\nLa desviación típica es:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(df$peso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.19631\n```\n\n\n:::\n:::\n\n\nVerificamos la distribución mediante el histograma y el diagrama de caja:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,2))\nhist(df$peso)\nboxplot(df$peso)\n```\n\n::: {.cell-output-display}\n![](175-rd-contenido-efectivo_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\nLos datos son aproximadamente simétricos y el aspecto del histograma es el de la distribucón normal, lo cual nos indica que la utilización de la media y la desviación típica como descriptores de la distribución parece correcta. $R$ tiene métodos precisos para hacer estas comprobaciones, que podremos ver en detalle en otro momento.\n\n## Comprobación de la adecuación de nuestros datos de peso a la normativa legal\n\nLa norma nos indica las cantidades en dos muestras sucesivas de $50$ unidades, haciendo un total de 100. Podemos ponernos en el caso más desfavorable y calcular una muestra de $100$ unidades a partir de nuestras $9.600$ observaciones de peso.\n\nPara calcular una muestra, podemos utilizar la función `sample()`, que extrae una muestra aleatoria de un vector; indicamos el vector y el tamaño de la muestra:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmuestra <- sample(df$peso, 100)\n```\n:::\n\n\nUna vez que hemos importado los datos y hecho nuestra muestra, el cálculo de los criterios de rechazo y la comparación con la norma es ya muy sencillo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(muestra < 232)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(muestra < 241)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n:::\n\n\nNuestra muestra tiene 100 elementos por debajo del criterio de rechazo del valor nominal menos dos veces el EMDT (`232`). Por lo tanto, según este criterio, **rechazamos** el lote como válido.\n\nAdemás tiene 100 envases deficientes, lo que es  superior o igual al criterio de rechazo de  `7`envases deficientes; por lo tanto, según este criterio, **rechazamos** el lote como válido. \n\n## El trabajo de mejora\n\nHasta aquí hemos conseguido determinar la validez de un lote de producto envasado de acuerdo con la ley de contenido efectivo. Si nos quedásemos aquí, habríamos hecho razonablemente bien el papel de inspector o inspectora del Ministerio de Consumo, pero de nosotros se espera algo más. Si el lote no es válido, ¿qué podemos hacer para que en el futuro nos ajustemos a la ley? ¿Cuál es el sobrepeso que estamos entregando y cuánto cuesta a la empresa? ¿Podemos conseguir algún ahorro en el proceso de dosificación manteniendo el proceso dentro de las especificaciones legales? ¿Cómo estableceríamos las etapas básicas de la mejora? Este es el papel que la empresa espera que desempeñemos, ¡no el de un mero fiscalizador!\n\nPara entrar en esta parte apasionante de nuestro trabajo, neesitamos repasar algunos conceptos y descubrir algunas nuevas herramientas, ¡no muchas!\n\n## Cómo determinamos los límites de  tolerancia de un proceso\n\nHemos visto que, en determinadas condiciones, una distribución de frecuencias puede ser descrita de forma aproximada mediante una distribución normal, que utiliza como parámetros $\\mu$  y $\\sigma$ la media $\\overline{x}$ y la [desviación típica](https://es.wikipedia.org/wiki/Desviaci%C3%B3n_t%C3%ADpica) $s$ de la distribución. La *aproximación normal* nos permite usar una propiedad de la *curva normal*, que ya hemos visto: el porcentaje de casos que esperamos encontrar en los intervalos definidos por la desviación típica:\n\n![Fuente: Wikipedia](imagenes/Standard_deviation_diagram.svg)\n\n\nRecordemos que, en una distribución concreta, \n\n- en el intervalo $\\mu\\pm1\\text{ }\\sigma$ encontraremos el $68,2\\%$ de los datos\n- en el intervalo $\\mu\\pm2\\text{ }\\sigma$ encontraremos el $95,4\\%$ de los datos\n- en el intervalo $\\mu\\pm3\\text{ }\\sigma$ encontraremos el $99,6\\%$ de los datos\n\nLa magnitud de la desviación típica nos define la amplitud de la dispersión, es decir, el aspecto más o menos aplanado de la distribución:\n\n![Fuente: Wikipedia](imagenes/Comparison_standard_deviations.svg)\n\nLa gráfica anterior nos representa dos procesos con valor medio $100$ y con dos valores distintos de desviación típica. La distribución representada en rojo tiene una $s_1=10$, mientras que la distrobución representada en azul tiene una $s_2=50$\n\nSi ambas gráficas representasen dos procesos de llenado de envases de 100 gramos, el primer proceso tendría el 99,6% de los casos en el intervalo $\\overline{x_1}\\pm3*s_1=(70, 130)$. Sin embargo, el segundo proceso tendría en este intervalo $(70,130)$ solamente en torno al 70% (aproximadamente) de los datos, ya que el intervalo de $\\overline{x_2}\\pm1*s_2=(50, 150)$\n\nSupongamos ahora que la especificación de calidad del proceso de envasado tuviese como límite inferior de peso los 50 gramos. En el primer caso, estaríamos prácticamente seguros de que ninguno de nuestros envases estaría por debajo de ese peso, y por tanto cumpliríamos la especificación sin ningún problema. En el segundo caso, en cambio, $50$ es el límite inferior de *una* desviación típica, por lo que, según lo que vemos en nuestra curva normal, el $(13,6\\% + 2,1\\% + 0,1\\%)$ de los casos estarían por debajo de esta cantidad, es decir, tendríamos un $15,7%$ fuera de la especificación.\n\nEsto tiene dos lecturas diferentes:\n\n- Para construir los límites de nuestro proceso, necesitamos conocer su desviación típica, con ella podemos construir los intervalos dentro de los cuales debe mantenerse el proceso.\n- Si nuestro proceso debe ajustarse a una especificación externa, ya sea una especificación del cliente o una normativa legal, podremos hacerlo solamente si la desviación típica se ajusta a lo que se nos exige. \n\nEn un proceso de envasado, no hay límite legal superior al peso que entregamos, sólo límite inferior. Por eso, cuando no somos capaces de reducir nuestra variabiidad, nos vemos obligados a subir el peso dosificado para que el límite inferior esté dentro de la especificación.\n\n\n### Introducción a la capacidad de un proceso\n\nCuando un proceso se ajusta a los límites especificados, se dice que es un **proceso capaz**. Si nuestro proceso **no es capaz**, nuestro trabajo consiste en reducir la variabilidad hasta que el proceso *entre* en la especificación. La reducción de la variabilidad es uno de los principales objetivos de los procesos **Seis Sigma**.\n\nExisten medidas concretas para definir la [capacidad del proceso](https://es.wikipedia.org/wiki/Capacidad_del_proceso), que pueden revisarse en la bibliografía; no las veremos aquí por el momento.\n\n$R$ proporciona gráficos específicos para analizar la capacidad de un proceso, y para hacer el seguimiento de un proceso y analizar sus desviaciones.\n\nVamos a analizar la primera de ellas, estudiando la capacidad de nuestro proceso de envasado de acuerdo con la normativa legal.\n\nUtilizaremos dos funciónes de la [librería `qcc`](https://cran.r-project.org/web/packages/qcc/vignettes/qcc_a_quick_tour.html), la propia función `qcc()` y la función   `process.capability()`\n\nLa primera función nos calcula un gráfico de control, como hemos visto en la introducción. En este caso analizaremos el proceso completo de envasado que hemos realizado en el día, y que consta de 9.600 envases. PAra evitar colapsar el gráfico y además obtener intervalos de control, agrupamos los datos por intervalos de 3 minutos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(lubridate)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'lubridate'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    date, intersect, setdiff, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(qicharts2)\n\n# Convertir la columna de texto a formato Fecha-Hora real\ndf <- df %>%\n  mutate(\n    hora_envasado = ymd_hms(hora_envasado) \n  )\n# intervalo de muestreo\ndf$intervalo <- lubridate::floor_date(df$hora_envasado, \"3 minutes\")\nqic(peso_g, \n    x          = intervalo, \n    data       = df, \n    chart      = \"xbar\",\n    point.size = 0.9,\n    title      = \"Control de Peso (Media cada 3 min)\",\n    ylab       = \"Gramos (g)\",\n    xlab       = \"Hora de Envasado\")\n```\n\n::: {.cell-output-display}\n![](175-rd-contenido-efectivo_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqic(peso_g, \n    x          = intervalo, \n    data       = df, \n    chart      = \"s\",\n    point.size = 0.9,\n    title      = \"Control de Peso (DEsviación típica cada 3 min)\",\n    ylab       = \"Gramos (g)\",\n    xlab       = \"Hora de Envasado\")\n```\n\n::: {.cell-output-display}\n![](175-rd-contenido-efectivo_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nLa [función `process.capability()`](https://luca-scr.github.io/qcc/reference/process.capability.html) utiliza la información almacenada en esta estructura para hacer sus cálculos. Veamos el gráfico de capacidad de proceso:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(lubridate)\nlibrary(qcc)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPackage 'qcc' version 2.7\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nType 'citation(\"qcc\")' for citing this R package in publications.\n```\n\n\n:::\n\n```{.r .cell-code}\n# 1. Conversión y creación de grupos de 5 min\ndf_preparado <- df %>%\n  mutate(\n    hora_envasado = ymd_hms(hora_envasado),\n    intervalo = floor_date(hora_envasado, \"5 minutes\")\n  ) %>%\n  group_by(intervalo) %>%\n  # Creamos un índice dentro de cada grupo para poder ensanchar la tabla\n  mutate(obs_id = row_number()) %>% \n  ungroup()\n\n# 2. Transformar a formato Matriz (Ancho)\n# Cada fila será un intervalo de 5 min, cada columna una observación\ndatos_matriz <- df_preparado %>%\n  select(intervalo, obs_id, peso_g) %>%\n  tidyr::pivot_wider(names_from = obs_id, values_from = peso_g) %>%\n  select(-intervalo) %>% # Quitamos la columna de tiempo para la matriz\n  as.matrix()\n\n# Creamos el objeto xbar (si no lo tienes ya)\nobj_xbar <- qcc(datos_matriz, type = \"xbar\", plot = FALSE)\n# Calculamos y dibujamos la capacidad\ncapacidad <- process.capability(obj_xbar, \n                                spec.limits = c(143.25, 156,75), \n                                target = 150)\n```\n\n::: {.cell-output-display}\n![](175-rd-contenido-efectivo_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nEste gráfico nos presenta un histograma con los valores de peso de la muestra, una curva normal ajustada a estos valores (construida a partir de la media y la desviación típica de la muestra). Si proporcionamos los límites superior (*upper specification limit*) e inferior (*lower specification limit*), el gráfico nos dibuja estos límites, lo que nos permite una comparación visual muy conveniente.\n\nHemos suministrado a la función como límites del proceso los de la media $\\overline{x}\\pm2*EMDT$; sabemos que no podemos tener ningún peso por debajo del límite inferior de este intervalo ($232$).\n\nEL gráfico nos imprime además otros valores estadísticos, de los cuales por el momento sólo utilizaremos:\n\n- Center: es el valor promedio de la muestra ($250,00$)\n- StdDev: es la desviación típica de la muestra ($8,11$)\n- Obs<LSL: el porcentaje de casos por debajo del límite inferior de la especificación que hemos indicado, en este caso $\\overline{x}-2*EMDT=232$, que es el límite de rechazo.\n- Obs>USL: el porcentaje de casos por encima del límite superior de la especificación que hemos indicado, en este caso, $\\overline{x}+2*EMDT=268$.\n\nEn nuestro caso, no deberíamos encontrar ningún valor por debajo del LSL. Sin embargo tenemos un $1,3\\%$ de valores en esta zona. Esto quiere decir que nuestro proceso *no es capaz* de mantenerse dentro de los límites de la especificación.\n\nPodemos repetir el gráfico, esta vez utilizando los valores de $\\overline{x}\\pm1*EMDT=(241, 259)$ como límites de especificación La ley de contenido efectivo nos dice que con nuestro tamaño de lote, rechazamos el lote si en nuestra muestra de 100 tenemos 7 o más valores por debajo de este límite, lo que es lo mismo, debemos tener una cantidad de valores por debajo de $241$ que debe ser **menor** de 7 casos en 100, es decir, del $7\\%$ de los casos.\n\n\nNuestro gráfico de capacidad de proceso, con los nuevos límites, nos dice que tenemos un $13\\%$ de casos por debajo del valor límite, lo que de nuevo nos sitúa fuera de la especificación: debemos rechazar el lote.\n\n## Plan de mejora: dispersión objetivo y peso a dosificar\n\nComo hemos visto, nuestro proceso no está dentro de las especificaciones que nos exige la normativa legal. tenemos dos opciones para corregir esta situación:\n\n1. Subir el peso medio dosificado, lo lo que nos llevará a sobredosificar, y esto aumentará nuestros costes de producción. Si no podemos aumentar el precio de venta, sobredosoficar nos ocasionará *pérdidas no previstas*.\n2. Reducir la variabilidad (la desviación típica), de manera que nuestro proceso *sea capaz* de entrar en la especificación\n\nDe forma inmediata no podemos asegurar una reducción de la variabilidad porque todavía no conocemos las condiciones que han producido la desviación típica de $s=7,5$ entre las 14:00 y las 15:00 horas.\n\nLo que sí podemos (y tenemos) que hacer de manera inmediata para cumplir la ley es aumentar el peso dosificado, y, una vez dentro de la ley, pondremos en marcha nuestro plan de mejora. Haremos todo esto en varias etapas:\n\n1. Subiremos lo necesario para evitar los pesos por debajo de $232\\text{ }g$\n2. Verificaremos si con el nuevo peso, se reduce el número de envases deficientes (por debajo de $241\\text{ }g$) hasta situarnos en los límites de tolerancia.\n3.  En caso de que la subida de peso no consiga el efecto que buscamos en el punto 2, procederemos a una nueva subida del peso medio hasta que cumplamos con ambas especificaciones.\n4. Sólo entonces, una vez dentro de la ley, pondremos en marcha un plan de mejora de la variabilidad con el objetivo de alcanzar una desviación típica de $7,5$ o inferior. Esto nos permitirá recorrer el camino inverso, es decir, bajar el peso medio de nuevo hasta el límite que sea posible sin incumplir la norma.\n\nUna vez que hayamos dado los tres primeros pasos, nos encontraremos en una situación de **sobredosificación**. Calcularemos el sobrepeso real que estamos entregando y su coste, de forma que podamos estableer un objetivo económico para el punto 4º.\n\nPuesto que no debemos tener ningún valor por debajo de $232\\text{ }g$, y nuestro valor mínimo es de 135.76, debemos aumentar la dosificación en más de 96.24 gramos. Simularemos el proceso en $R$ simplemente sumando a los valores originales este aumento de dosificación; guardaremos los pesos modificados en una nueva columna de nuestro *dataframe* que llamaremos `peso2`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# incremento_peso <- 232 - min(df$peso) + 1 # añadimos un margen de confianza como seguridad\n# df$peso2 <- df$peso + incremento_peso\n```\n:::\n\n\nMás adelante veremos cómo construir un nuevo vector de peso de forma diferente, mediante una simulación probabilística,\n\n\n::: {.cell}\n\n:::\n\n\nHemos aumentado nuestro peso en `X` gramos. Veamos la media y desviación típica de nuestro nuevo peso simulado, y el sumario de $R$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#mean(df$peso2)\n#sd(df$peso2)\n#summary(df$peso2)\n```\n:::\n\n\nComo vemos, la desviación típica no se ha modificado.\n\nComparemos la distribución de pesos original con la que hemos modificado mediante un diagrama de caja de las dos columnas. En este caso, utilizamos la función básica `boxplot()` \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#boxplot(df$peso, df$peso2)\n```\n:::\n\n\nEl diagrama de caja nos permite comprobar el aumento de peso que hemos aplicado a la nueva variable `peso2`.\n\nLa comparación de los histogramas de las dos distribuciones no puede hacerse con la función básica `hist()` porque no puede imprimir dos histogramas solapados, necesitamos utilizar `ggplot()`, y también cambiar el formato de nuestro dataframe a formato ordenado, Si verificamos el *dataframe*. vemos que ahora la medida de peso no está en una columna única, sino en dos:\n\n::: {.cell}\n\n```{.r .cell-code}\n#head(df)\n```\n:::\n\n\nLa estructura de *datos ordenados* nos exige que cada tipo de variable (en este caso el peso) esté en una sola columna. Para modificar la tabla, necesitamos *pivotar\" las medidas de peso a una sola columna, y colocar las descripciones en una nueva columna que llamaremos $caso$. Lo hacemos con la [función `pivot_longer()`](https://tidyr.tidyverse.org/reference/pivot_longer.html) de la librería `dplyr`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df |>\n    # pivot_longer(cols = c(peso,peso2), names_to = \"caso\", values_to = \"peso\") |>\n    # head()\n```\n:::\n\n\nCon esta estructura, `ggplot` nos permite varias alternativas para nuestro histograma. No necesitamos hacer permanente la estructura del *dataframe*. podemos pasarla a `ggplot`mediante un `pipe` sin guardarla en un dataframe, los cálculos se hacen instantáneamente. veamos en primer lugar el diagrama de caja en versión `ggplot`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df |>\n#     pivot_longer(cols = c(peso,peso2), names_to = \"caso\", values_to = \"peso\") |>\n#     ggplot(aes(x = caso, y = peso))+\n#       geom_boxplot()\n```\n:::\n\n\n\nAhora podemos hacer la comparación de los histogramas, añadiendo un poco de color para diferenciarlos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df |>\n#     pivot_longer(cols = c(peso,peso2), names_to = \"caso\", values_to = \"peso\") |>\n#     ggplot(aes(x = peso, colour= caso,  fill = caso))+\n#       geom_histogram(position = \"identity\", alpha = 0.4) \n```\n:::\n\n\nA título informativo, otra presentación que puede tener interés en otras situaciones es la presentación de los gráficos clasificados lado a lado:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df |>\n#     pivot_longer(cols = c(peso,peso2), names_to = \"caso\", values_to = \"peso\") |>\n#     ggplot(aes(x = peso, colour = caso,  fill = caso))+\n#       geom_histogram(alpha = 0.4) +\n#       facet_wrap(~caso)\n```\n:::\n\n\nVolviendo a nuestro caso, \n\nSi nuestros cálculos han sido correctos, los pesos de la nueva columna no deben tener valores por debajo de 232:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sum(df$peso2<=232)\n```\n:::\n\n\nVeamos cuántos valores tenemos por debajo del límite que define los envases deficientes:\n\n::: {.cell}\n\n```{.r .cell-code}\n# sum(df$peso2 <= 241)\n```\n:::\n\n\nLa ley nos dice que en una muestra de 100 debemos tener menos de 7 envases deficientes. Verificamos que el porcentaje de envases deficientes es inferior al 7%:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pct_deficientes <- sum(df$peso2 < 241) / length(df$peso2) *100\n# pct_deficientes\n```\n:::\n\n\nEl porcentaje de unidades defectuosas es del `X`%, con lo que podemos estar razonablemente seguros de que el número de defectuosos en cualquier muestra que podamos tomar no excederá las 7 unidades defectuosas de cada 100.\n\n### Análisis económico\n\nCon la sobredosificación hemos conseguido que nuestro lote esté dentro de la ley.\n¿Cuál es el coste de la decisión?\n\nNo tenemos más que calcular el peso real que hemos dosificado y el peso calculado en la simulación:\n\n¿Qué peso real total en kilos hemos dosificado inicialmente?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# peso_real <- sum(df$peso) /1000\n# peso_real\n```\n:::\n\n\n¿Qué peso total teórico en kilos habríamos dosificado con la propuesta de subir el peso en r round(incremento_peso, 2) g por envase?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# peso_simul <- sum(df$peso2) /1000\n# peso_simul\n```\n:::\n\n\nEs decir, la decisión de incrementar el peso dosificado en r round(incremento_peso, 2) g nos hará dosificar r round((peso_simul - peso_real), 2) kg más. Suponiendo que el coste de producción de 1 kg sea de 0,85 euros, el coste del sobrepeso es de \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# peso_mas <- peso_simul - peso_real\n# coste_unitario <- 0.85\n# coste_total2 <- peso_mas * coste_unitario\n# coste_total2\n```\n:::\n\n\n\nEn resumen, nuestra decisión de aumentar la dosificación en r round(incremento_peso,2) g por envase para que el peso medio de nuestro lote de 3000 unidades cumpla con la normativa de contenido efectivo ha aumentado el coste del producto que entregamos como sobrepeso (gratuitamente) en r round(coste_total2,2) euros por cada lote de 3000 unidades. Si envasamos diariamente durante un año, y suponiendo 250 días útiles, el coste anual que estaríamos asumiendo con esta decisión sería de r round(coste_total2 * 250, 2) euros.\n\n## Un plan de ahorro\n\nSi fuésemos capaces de reducir la dispersión de peso, reduciendo la desviación típica de r round(sd(df$peso),2) a 6, mejorando ligeramente la mejor situación actual, podríamos bajar el peso medio, teniendo como límite el marcado por el peso mínimo de 232 g, lo que nos permitiría obtener un ahorro sobre esta cantidad.\n\n\nPara simular esta nueva columna, con una desviación típica más reducida, utilizaremos una *función de probabilidad*\n\nPara entender su uso, volvamos al histograma.\n\nHemos visto que cuando construimos un histograma, agrupamos el número de observaciones en lo que hemos llamado intervalos de frecuencia. la función básica de histograma de R hace estos cálculos automáticamente y los guarda dentro de la estructura del histograma, presentándonos sólo el gráfico. Podemos repasar la [construcción básica de un histograma](https://www.r-bloggers.com/2015/03/how-to-make-a-histogram-with-basic-r/) [aquí](https://www.r-bloggers.com/2015/03/how-to-make-a-histogram-with-basic-r/)\n\nNosotros podemos recuperar estos datos guardando el *objeto+ histograma en una variable e inspeccionando su estructura, cmomo hemos hecho otra veces:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n # h <- hist(df$peso)\n```\n:::\n\n\nHemos \"guardado\" nuestro histograma en un *objeto $R$*, que podemos reusar para ver la gráfica\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot(h)\n```\n:::\n\n\nVeamos su estructura:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# str(h)\n```\n:::\n\n\nLa variable `breaks` contiene los límites de los intervalos, mientras que la variable `mids`contiene los puntos medios de esos mismos intervalos. Podemos acceder a estos elementos del histograma usando la notación habitual de $R$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# h$breaks \n# h$mids\n```\n:::\n\nPodríamos utilizar las opciones de la función `hist()`para definir los intervalos que nos interesan, y recuperarlos utilizando estas variables (queda como ejercicio voluntario).\n\nComo alternativa, vamos a utilizar las funciones de la biblioteca `dplyr`para hacer el cálculo de una tabla de frecuencias. Para ello, vamos a agrupar los valores originales de peso en grupos definidos por la parte entera del peso, y calcularemos el número de valores en cada clase:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df |>\n#   mutate (intervalo = cut(peso, c(0,232,241,250,max(peso)))) |>\n#   group_by(intervalo) |>\n#   summarize (frecuencia = n()) |>\n#   mutate(frecuencia_relativa = round(frecuencia/ sum(frecuencia) * 100,2))\n```\n:::\n\n\nLa notación $(a,b]$ significa $>a\\text{ }$ y $\\text{ }<=b$ (intervalo abierto a la izquierda y cerrado a la derecha): el primer intervalo, (0,232], incluye todos los valores mayores que cero y menores o iguales que 232, y así sucesivamente.\n\n\n::: {.cell}\n\n:::\n\n\nLa tabla nos dice que en el peso original (columna `peso`) tenemos \n\n- un r pct_rechazos`% de valores iguales o menores que 232 (criterio de rechazo), y \n- un r pct_deficientes`% de valores iguales o menores que 241 (criterio para envases deficientes). \n\nAmbos valores están fuera de los límites de aceptación del lote,  es decir, el lote está fuera de la norma, como hemos visto antes.\n\nEn nuestra nueva columna, con el peso modificado, la distribución de frecuencias es la siguiente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df |>\n#   mutate (intervalo = cut(peso2, c(0,232,241,250,max(peso)))) |>\n#   group_by(intervalo) |>\n#   summarize (frecuencia = n()) |>\n#   mutate(frecuencia_relativa = round(frecuencia/ sum(frecuencia) * 100,2))\n```\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\nLa nueva tabla nos dice que en el peso modificado (columna `peso2`) tenemos \n\n- un r pct_rechazos`% de valores iguales o menores que 232 (criterio de rechazo), y \n- un r pct_deficientes`% de valores iguales o menores que 241 (criterio para envases deficientes). \n\n## La distribución normal y el cálculo de probabilidad: introducción\n\nPara hacer los cálculos anteriores, hemos utilizado la distribución de frecuencias de las dos columnas de peso. \n\nSi suponemos que nuestra distribución de pesos se ajusta a una *distribución normal*, que ya conocemos, podemos construir una *curva normal* que se ajuste a nuestros datos:\n\n\n::: {.cell}\n\n:::\n\n\nEsta [curva o distribución normal](https://es.wikipedia.org/wiki/Distribuci%C3%B3n_normal) es una distribución de probabilidad que se construye utilizando la media y la desviación típica; el área bajo la curva nos da la probabilidad de ocurrencia de un suceso. No entraremos en los aspectos estadísticos de la construcción de la función de probabilidad y el cálculo de probabilidades, sólo necesitamos saber que $R$ tiene dos funciones que nos son útiles:\n\n- [La función `rnorm()`](https://www.rdocumentation.org/packages/compositions/versions/1.40-3/topics/rnorm) permite construir un conjunto de valores que se ajusta a una distribución normal\n- [La función `pnorm()`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Normal) calcula la probabilidad de que en una muestra podamos encontrar un valor determinado.\n\nVeamos el uso de cada función, empezando por la segunda: \n\nSi la media de nuestro conjunto de valores de $peso$ es de $\\overline x=$ r round(mean(df$peso),2)` y la desviación típica $s=$ r round(sd(df$peso),2)`, podemos calcular la probabilidad de que encontremos un valor inferior o igual a $232$:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# p1 <- pnorm(232, mean(df$peso), sd(df$peso))\n# p1\n```\n:::\n\n\naproximadamente,  r round(p1*100,0)`$\\%$.\n\nLa probabilidad de encontrar envases deficientes, con un peso inferior o igual a $241$ es de\n\n::: {.cell}\n\n```{.r .cell-code}\n# p2 <- pnorm(241, mean(df$peso), sd(df$peso))\n# p2\n```\n:::\n\n\nAproximadamente, del r round(p2*100,0)`$\\%$.\n\nEs decir, según el cálculo de probabilidad, en una muestra de 100 unidades, cabe esperar que encontremos r round(p1*length(df$peso),0) envases por debajo del límite de rechazo 232 g y r round(p2*length(df$peso),0)` envases deficientes. Comparemos con el resultado de la tabla de frecuencias, más arriba.\n\nVeamos ahora la situación en nuestra columna de peso modificada:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# p1 <- pnorm(232, mean(df$peso2), sd(df$peso2))\n# p2 <- pnorm(241, mean(df$peso2), sd(df$peso2))\n```\n:::\n\n\nEn una muestra de 100 unidades, esperamos encontrar r round(p1*length(df$peso2),0)` envases por debajo del límite de rechazo 232 g y r round(p2*length(df$peso2),0)` envases deficientes.\n, lo que coincide bastante aproximadamente en ambos casos con los cálculos que habíamos realizado sobre la tabla de frecuencias, de forma mucho más sencilla.\n\nLa **suposición de normalidad** nos ha simplificado enormemente nuestros cálculos, y en vez de la engorrosa tabla de frecuencias, sólo tenemos que utilizar una simple fórmula.\n\nLa distribución normal tiene otra utiidad poderosa: podemos construir una distribución de valores que se ajuste a una distribución normal, dada la media y la desviación típica.\n\nEn nuestro ejemplo, intentamos encontrar los ahorros que se pueden deducir de una reducción de la variabilidad. Vamos a suponer que reducimos nuestra desviación típica de 8 a 6.\n\nConstruyamos un nuevo conjunto de datos con el peso medio de nuestra distribución de peso modificada y la nueva desviación típica:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df$peso3 <- rnorm (3000, mean(df$peso2), 6)\n# \n```\n:::\n\n\nComparemos las distribuciones de las tres columnas de peso, la original, $peso$, la modificada que hemos obtenido sumando un peso fijo, $peso2$, y la tercera que hemos calculado mediante la función de distribución normal, $peso3$, utilizando la función de densidad:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df |>\n#     pivot_longer(cols = c(peso,peso2, peso3), names_to = \"caso\", values_to = \"peso\") |>\n#     ggplot(aes(x = peso, colour= caso,  fill = caso))+\n#       geom_density(alpha = 0.3) \n```\n:::\n\n\ny el diagrama de caja:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df |>\n#     pivot_longer(cols = c(peso,peso2, peso3), names_to = \"caso\", values_to = \"peso\") |>\n#     ggplot(aes(y = peso, x= caso, colour = caso))+\n#       geom_boxplot() \n```\n:::\n\n\nCon alguna instrucción adicional, podemos mostrar las curvas de densidad y los diagramas de caja lado a lado:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df2 <- df |>\n#     select(peso,peso2, peso3) |>\n#     pivot_longer(cols = c(peso,peso2,peso3), names_to = \"caso\", values_to = \"peso\")\n# \n# graf1 <- ggplot(df2, aes(x = peso, colour = caso, fill = caso)) +\n#         geom_density(alpha=0.3)\n# \n# df2 <- df |>\n#     select(peso,peso2, peso3) |>\n#     pivot_longer(cols = c(peso,peso2, peso3), names_to = \"caso\", values_to = \"peso\")\n# \n# graf2 <- ggplot(df2, aes(x = caso, y = peso, colour = caso)) +\n#         geom_boxplot()\n# \n# gridExtra::grid.arrange(graf1, graf2, ncol=2)\n```\n:::\n\n\nLa distribución de $peso3$ es más estrecha, como corresponde a la reducción de variabilidad. Ahora el valor mínimo está alejado del valor de rechazo $232$, por lo que podemos bajar el peso medio\n\nRepetimos la simulación, creando nuestro conjunto de peso $peso3$ con una media de peso con 4 gramos menos que $peso2$ y una desviación típica de 6:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df$peso3 <- rnorm (3000, mean(df$peso2)-4, 6)\n```\n:::\n\n\nVeamos el número de envases por debajo del valor de rechazo en el total del lote. Debe ser cero; si encontramos algún valor, debemos revisar la propuesta de recuperación de 4 g y reducirla un poco (lo comparamos conla funcion de probabilidad):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sum(df$peso3 <= 232)\n# pnorm(232, mean(df$peso3), 6 )\n```\n:::\n\n\nEn ambos casos, el resultado es aproximadamente cero.\n\nY ahora el número de envases deficientes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sum(df$peso3 <= 241)\n# pnorm(241, mean(df$peso3), 6 ) * length(df$peso3)\n```\n:::\n\n\n(el número de envases deficientes esperado es igual a la probabilidad de tener un envase deficiente por el número total de envases)`\n\nAmbos valores coinciden aproximadamente (lo que no es extraño puesto que hemos construido nuestro ejemplo de la distribución de pesos a partir de la función normal, por supuesto)\n\nComparando las tres columnas de peso, \n\n::: {.cell}\n\n```{.r .cell-code}\n# df |>\n#   select(peso,peso2, peso3) |>\n#   pivot_longer(cols = c(peso,peso2,peso3), names_to = \"caso\", values_to = \"peso\") |>\n#   group_by(caso) |>\n#   summarize (peso_medio = mean(peso), desv_t = sd(peso))\n```\n:::\n\nAhora calcularemos el ahorro conseguido:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# peso_simul2 <- sum(df$peso3) /1000\n# peso_mas <- abs(peso_simul2 - peso_simul)\n# coste_unitario <- 0.85\n# coste_total3 <- peso_mas * coste_unitario\n# coste_total3\n```\n:::\n\n\nLa reducción de la variabilidad a una $s=6$ nos permitiría reducir en 4 gramos el valor de sobrepeso dosificado, con lo cual obtendríamos una mejora de r round(coste_total3, 2)` euros por lote, o lo que es lo mismo, una recuperación de r round(coste_total3 * 250, 0)` euros anuales frente a nuestra pérdida anterior.\n\nVeamos la distribución de pesos con los diagramas de densidad y de caja, incluyendo la nueva simulación:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# df2 <- df |>\n#     select(peso,peso2, peso3) |>\n#     pivot_longer(cols = c(peso,peso2,peso3), names_to = \"caso\", values_to = \"peso\")\n# \n# graf1 <- ggplot(df2, aes(x = peso, colour = caso, fill = caso)) +\n#         geom_density(alpha=0.3)\n# \n# df2 <- df |>\n#     select(peso,peso2, peso3) |>\n#     pivot_longer(cols = c(peso,peso2, peso3), names_to = \"caso\", values_to = \"peso\")\n# \n# graf2 <- ggplot(df2, aes(x = caso, y = peso, colour = caso)) +\n#         geom_boxplot()\n# \n# gridExtra::grid.arrange(graf1, graf2, ncol=2)\n```\n:::\n\n\nVemos claramente la reducción de la variabilidad en nuestra hipótesis 3 y cómo hemos podido reducir el peso medio manteniendo nuestra distribucion de pesos dentro de la norma.\n\nEn un artículo posterior veremos cómo optimizar aún más este ahorro mediante la correcta utilización de un *discriminador de peso*, que es un sistema de peso en continuo y un expulsor que nos permite apartar envases bajos de peso en función del criterio de configuracion que establezcamos. $R$ nos permite también optimizar este sistema.\n\nLas acciones para reducir la variabilidad en el proceso constituyen uno de los objetivos de los proyectos Seis Sigma, e incluyen técnicas diversas que incluyen las gráficas de control de proceso y otras herramientas.\n\n## Resumen del capítulo\n\nEl RD 1801/2008 establece que la proporción de envases con contenido inferior al límite T1 ($Q_n - \\text{EMDT}$) no puede superar el 2,5% del lote, y que ningún envase puede estar por debajo del límite T2 ($Q_n - 2 \\times \\text{EMDT}$). El cumplimiento de estos límites no depende solo del peso medio de llenado sino fundamentalmente de la dispersión del proceso.\n\nLa distribución normal permite calcular con precisión el peso medio mínimo necesario para cumplir la norma en función de σ: a mayor dispersión, mayor sobredosificación necesaria y mayor coste económico. En el dataset del turno de producción hemos visto que el cumplimiento global puede ocultar incumplimientos en períodos concretos, lo que subraya la importancia del seguimiento continuo del proceso en lugar del análisis puntual.\n\nLa conclusión práctica es que invertir en reducir la variabilidad del proceso de llenado tiene un retorno económico directo y cuantificable, independientemente de cualquier otra consideración de calidad.\n",
    "supporting": [
      "175-rd-contenido-efectivo_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}