{
  "hash": "02a3bd156c574a1de8e9706a17b801e0",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nlang: es\ntitle: Práctica 1b. Análisis exploratorio de una fabricación de queso camembert en Google Colab\ndate-modified: '2026-03-12'\nformat:\n  html:\n    code-fold: true\n    code-summary: Mostrar código\njupyter: python3\n---\n\nEste cuaderno es la versión interactiva del capítulo 7 del libro, y está orientada a Colab. Contiene únicamente el código Python; para las explicaciones teóricas y el código R consulta el libro en:\n\n[https://juanriera.github.io/master-queseria/](https://juanriera.github.io/master-queseria/)\n\n[Abrir este cuaderno en Google Colab](https://colab.research.google.com/github/juanriera/master-queseria/blob/master/090-pract01-colab-camembert.ipynb)\n\nPara utilizar los datos que se utilizan en el cuaderno, descarga el CSV de ejemplo y súbelo al espacio de trabajo de Colab.\n\n[Descargar los datos `camembert.csv`](https://raw.githubusercontent.com/juanriera/master-queseria/master/datos/camembert.csv)\n\nEn los capítulos anteriores hemos aprendido a describir datos mediante gráficos y estadísticos. Ahora vamos a aplicar todo lo aprendido a un caso real: el análisis exploratorio de una temporada completa de fabricación de queso camembert. Los datos corresponden a los análisis de control de calidad realizados durante el año 2020 en una quesería, con una o dos fabricaciones diarias a lo largo de los días laborables. El dataset contiene 211 observaciones y seis variables:\n\n- `est`: extracto seco total (%)\n- `mg`: materia grasa (%)\n- `ph`: pH del queso\n- `cloruros`: contenido en cloruros (%)\n- `coliformes`: recuento de bacterias coliformes (ufc/g)\n- `fabricacion`: número de fabricación del día (1 o 2)\n\n[Descargar los datos `camembert.csv`](https://raw.githubusercontent.com/juanriera/master-queseria/master/datos/camembert.csv)\n\n## Flujo de trabajo\n\nComo vimos en el capítulo 2, es muy conveniente establecer un flujo de trabajo regular, de forma que cada etapa del análisis se apoye en las anteriores:\n\n![](imagenes/080/data-science-explore.svg)\n\nVamos a ir desarrollando este flujo paso a paso.\n\n## Importar los datos\n\nCargamos el fichero desde GitHub. Si has descargado el fichero en tu ordenador, puedes adaptar la ruta de lectura según vimos en el capítulo anterior.\n\n::: {#c6015d0a .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nurl_datos = (\n    \"https://raw.githubusercontent.com/\"\n    \"juanriera/master-queseria/master/\"\n    \"datos/camembert.csv\"\n)\n\ntry:\n    df = pd.read_csv(url_datos,\n                     decimal=\",\",\n                     sep=';',\n                     encoding='ISO-8859-1')\n    print(\"Archivo cargado correctamente.\")\n    print(f\"Dimensiones: {df.shape}\")\nexcept Exception as e:\n    print(f\"Error al cargar el archivo: {e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nArchivo cargado correctamente.\nDimensiones: (211, 7)\n```\n:::\n:::\n\n\nInspeccionamos las primeras filas y la estructura del dataframe:\n\n::: {#74cab798 .cell execution_count=2}\n``` {.python .cell-code}\ndf.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>fecha</th>\n      <th>fabricacion</th>\n      <th>est</th>\n      <th>mg</th>\n      <th>ph</th>\n      <th>cloruros</th>\n      <th>coliformes</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>11/01/2020</td>\n      <td>1</td>\n      <td>46.68</td>\n      <td>24.0</td>\n      <td>4.85</td>\n      <td>1.50</td>\n      <td>80.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>12/01/2020</td>\n      <td>1</td>\n      <td>48.09</td>\n      <td>25.0</td>\n      <td>4.67</td>\n      <td>1.61</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>13/01/2020</td>\n      <td>1</td>\n      <td>45.97</td>\n      <td>24.0</td>\n      <td>4.71</td>\n      <td>1.48</td>\n      <td>9200.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>14/01/2020</td>\n      <td>1</td>\n      <td>46.24</td>\n      <td>23.5</td>\n      <td>4.78</td>\n      <td>1.69</td>\n      <td>20.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>15/01/2020</td>\n      <td>1</td>\n      <td>45.81</td>\n      <td>23.0</td>\n      <td>4.77</td>\n      <td>1.56</td>\n      <td>150.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#fed2ca89 .cell execution_count=3}\n``` {.python .cell-code}\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 211 entries, 0 to 210\nData columns (total 7 columns):\n #   Column       Non-Null Count  Dtype  \n---  ------       --------------  -----  \n 0   fecha        211 non-null    object \n 1   fabricacion  211 non-null    int64  \n 2   est          211 non-null    float64\n 3   mg           211 non-null    float64\n 4   ph           211 non-null    float64\n 5   cloruros     211 non-null    float64\n 6   coliformes   210 non-null    float64\ndtypes: float64(5), int64(1), object(1)\nmemory usage: 11.7+ KB\n```\n:::\n:::\n\n\nLa columna `fecha` aparece como tipo texto. La convertimos a formato fecha:\n\n::: {#04537290 .cell execution_count=4}\n``` {.python .cell-code}\ndf['fecha'] = pd.to_datetime(\n    df['fecha'],\n    format='%d/%m/%Y',\n    errors='coerce'\n)\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 211 entries, 0 to 210\nData columns (total 7 columns):\n #   Column       Non-Null Count  Dtype         \n---  ------       --------------  -----         \n 0   fecha        211 non-null    datetime64[ns]\n 1   fabricacion  211 non-null    int64         \n 2   est          211 non-null    float64       \n 3   mg           211 non-null    float64       \n 4   ph           211 non-null    float64       \n 5   cloruros     211 non-null    float64       \n 6   coliformes   210 non-null    float64       \ndtypes: datetime64[ns](1), float64(5), int64(1)\nmemory usage: 11.7 KB\n```\n:::\n:::\n\n\n## Verificar los datos\n\nAntes de analizar, verificamos que los valores son plausibles. Calculamos un resumen estadístico de todas las variables:\n\n::: {#20c3c90c .cell execution_count=5}\n``` {.python .cell-code}\ndf.describe().round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>fecha</th>\n      <th>fabricacion</th>\n      <th>est</th>\n      <th>mg</th>\n      <th>ph</th>\n      <th>cloruros</th>\n      <th>coliformes</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>211</td>\n      <td>211.00</td>\n      <td>211.00</td>\n      <td>211.00</td>\n      <td>211.00</td>\n      <td>211.00</td>\n      <td>210.00</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>2020-06-30 14:06:15.355450112</td>\n      <td>1.05</td>\n      <td>46.64</td>\n      <td>23.73</td>\n      <td>4.68</td>\n      <td>1.45</td>\n      <td>650.88</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>2020-01-11 00:00:00</td>\n      <td>1.00</td>\n      <td>42.92</td>\n      <td>21.50</td>\n      <td>4.35</td>\n      <td>-1.00</td>\n      <td>0.00</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>2020-03-21 12:00:00</td>\n      <td>1.00</td>\n      <td>45.61</td>\n      <td>23.00</td>\n      <td>4.63</td>\n      <td>1.35</td>\n      <td>0.00</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>2020-07-04 00:00:00</td>\n      <td>1.00</td>\n      <td>46.60</td>\n      <td>23.50</td>\n      <td>4.68</td>\n      <td>1.46</td>\n      <td>10.00</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>2020-10-05 12:00:00</td>\n      <td>1.00</td>\n      <td>47.47</td>\n      <td>24.50</td>\n      <td>4.74</td>\n      <td>1.56</td>\n      <td>190.00</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>2020-12-29 00:00:00</td>\n      <td>2.00</td>\n      <td>52.61</td>\n      <td>28.00</td>\n      <td>4.99</td>\n      <td>1.89</td>\n      <td>20200.00</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>NaN</td>\n      <td>0.22</td>\n      <td>1.45</td>\n      <td>0.94</td>\n      <td>0.08</td>\n      <td>0.23</td>\n      <td>2194.15</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nYa en este primer resumen aparecen varias señales que merecen atención: el mínimo de `cloruros` es -1, lo que es físicamente imposible; el máximo de `est` es 52,61, claramente alejado del resto; y el rango de `coliformes` va de 0 a 20.200, con una dispersión enorme. Analizaremos cada variable con detalle en la sección siguiente.\n\n## Análisis variable a variable\n\n### Extracto seco total (`est`)\n\nComenzamos con la variable principal. En el capítulo 6 usamos el histograma y el boxplot para estudiar la forma de los datos; aquí los aplicamos directamente al caso real.\n\n::: {#3a9f490a .cell execution_count=6}\n``` {.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['est'], kde=True, ax=ax1)\nax1.set_title(\"Histograma del extracto seco total\")\nax1.set_xlabel(\"EST (%)\")\n\nsns.boxplot(y=df['est'], ax=ax2)\nax2.set_title(\"Boxplot del extracto seco total\")\nax2.set_ylabel(\"EST (%)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-7-output-1.png){width=949 height=372}\n:::\n:::\n\n\nEl histograma muestra una distribución aproximadamente simétrica en torno a 46-47%, pero con una cola hacia la derecha y una barra aislada en torno a 52%. La curva de densidad muestra una pequeña elevación en ese extremo que no debería estar ahí si la distribución fuese una campana de Gauss limpia. El boxplot confirma la presencia de varios valores atípicos por encima de 50%.\n\n¿Son errores o valores reales? Para responderlo necesitamos contexto temporal.\n\n### Serie temporal del extracto seco\n\n::: {#27617ef3 .cell execution_count=7}\n``` {.python .cell-code}\ndf['fecha_index'] = pd.DatetimeIndex(df.fecha).normalize()\ndf.set_index('fecha_index', inplace=True)\ndf.sort_index(inplace=True)\n\nsns.lineplot(data=df, x='fecha', y='est')\nplt.title(\"Evolución anual del extracto seco total\")\nplt.xlabel(\"Fecha\")\nplt.ylabel(\"EST (%)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-8-output-1.png){width=659 height=468}\n:::\n:::\n\n\nLa serie temporal revela lo que el histograma no podía mostrar: los valores altos se concentran en los meses de verano, especialmente julio y agosto. El valor máximo de 52,61% corresponde al 21 de julio. Esto cambia completamente la interpretación: los valores por encima de 50% no son errores aislados sino parte de una desviación estacional sostenida durante varias semanas. La forma del histograma que parecía simplemente asimétrica era en realidad la mezcla de dos momentos del año con comportamientos distintos: exactamente el caso de distribución bimodal que estudiamos en el capítulo 6.\n\nVisualizamos la media semanal y su dispersión para ver la evolución con más claridad:\n\n::: {#d5ca4725 .cell execution_count=8}\n``` {.python .cell-code}\nmedia_semanal = df[\"est\"].resample(\n    'W-MON', label='left', closed='left').mean()\ndt_semanal = df[\"est\"].resample(\n    'W-MON', label='left', closed='left').std()\n\nfig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 5), sharex=True)\n\nax1.plot(media_semanal, color='tab:blue')\nax1.set_title(\"Media y desviación típica semanal del extracto seco total\")\nax1.set_ylabel(\"Media EST (%)\")\nax1.grid(True, linestyle='--', alpha=0.6)\nax1.tick_params(labelbottom=False)\n\nax2.plot(dt_semanal, color='tab:orange')\nax2.set_ylabel(\"D. Típica EST\")\nax2.grid(True, linestyle='--', alpha=0.6)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-9-output-1.png){width=948 height=469}\n:::\n:::\n\n\n### Boxplot mensual del extracto seco\n\nEl boxplot por meses permite ver si los valores de julio son atípicos dentro de su propio contexto mensual:\n\n::: {#3fe18bb8 .cell execution_count=9}\n``` {.python .cell-code}\nimport calendar\ndf_plot_est = df.copy()\ndf_plot_est['mes_abreviado'] = df_plot_est.index.strftime('%b')\nmeses_orden = [calendar.month_abbr[i] for i in range(1, 13)]\ndf_plot_est['mes_abreviado'] = pd.Categorical(\n    df_plot_est['mes_abreviado'],\n    categories=meses_orden,\n    ordered=True\n)\n\nsns.boxplot(x='mes_abreviado', y='est', data=df_plot_est)\nplt.title(\"Extracto seco total por mes\")\nplt.xlabel(\"Mes\")\nplt.ylabel(\"EST (%)\")\nplt.grid(axis='y', linestyle='--', alpha=0.7)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-10-output-1.png){width=661 height=468}\n:::\n:::\n\n\nAhora la imagen es completamente distinta. En julio prácticamente todos los valores son altos: la mediana mensual de julio es la más alta del año, y el valor de 52,61% no es tan extremo dentro de ese mes. En cambio, en mayo aparece una dispersión muy baja seguida de un salto brusco en junio, que merece atención. Los meses de otoño e invierno muestran una distribución mucho más estable y centrada.\n\n### Materia grasa (`mg`)\n\nAplicamos el mismo análisis a la materia grasa:\n\n::: {#e75949e0 .cell execution_count=10}\n``` {.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['mg'], kde=True, ax=ax1)\nax1.set_title(\"Histograma de la materia grasa\")\nax1.set_xlabel(\"MG (%)\")\n\nsns.boxplot(y=df['mg'], ax=ax2)\nax2.set_title(\"Boxplot de la materia grasa\")\nax2.set_ylabel(\"MG (%)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-11-output-1.png){width=949 height=372}\n:::\n:::\n\n\nEl histograma de la materia grasa muestra una distribución aproximadamente simétrica centrada en torno a 23,5%, pero el boxplot señala un valor atípico alto claramente separado del resto. Ese valor es 28%, registrado el 26 de enero, y es el único por encima de 27%. Puede ser un error de estandarización en el arranque del año, cuando la composición de la leche de invierno es más rica en grasa. Lo analizamos en la serie temporal:\n\n::: {#c6722a2d .cell execution_count=11}\n``` {.python .cell-code}\nsns.lineplot(data=df, x='fecha', y='mg')\nplt.title(\"Evolución anual de la materia grasa\")\nplt.xlabel(\"Fecha\")\nplt.ylabel(\"MG (%)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-12-output-1.png){width=659 height=468}\n:::\n:::\n\n\n::: {#3a85c919 .cell execution_count=12}\n``` {.python .cell-code}\nimport calendar\ndf_plot2 = df.copy()\ndf_plot2['mes_abreviado'] = df_plot2.index.strftime('%b')\nmeses_orden = [calendar.month_abbr[i] for i in range(1, 13)]\ndf_plot2['mes_abreviado'] = pd.Categorical(\n    df_plot2['mes_abreviado'],\n    categories=meses_orden,\n    ordered=True\n)\n\nsns.boxplot(x='mes_abreviado', y='mg', data=df_plot2)\nplt.title(\"Materia grasa por mes\")\nplt.xlabel(\"Mes\")\nplt.ylabel(\"MG (%)\")\nplt.grid(axis='y', linestyle='--', alpha=0.7)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-13-output-1.png){width=661 height=468}\n:::\n:::\n\n\nEl boxplot mensual de la materia grasa no muestra la misma estacionalidad pronunciada que el extracto seco. El valor de 28% de enero es claramente atípico respecto a su mes, pero el resto del año la materia grasa se mantiene en un rango bastante estable entre 22 y 26%. A partir de febrero se observa una tendencia moderada al alza hasta el verano, que se corrige progresivamente en el segundo semestre.\n\n### Análisis conjunto: gráfico de dispersión `est` vs `mg`\n\nHasta ahora hemos analizado cada variable por separado. El gráfico de dispersión nos permite ver si existe relación entre el extracto seco y la materia grasa:\n\n::: {#2078d2f8 .cell execution_count=13}\n``` {.python .cell-code}\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\nsns.scatterplot(data=df, x='mg', y='est')\nplt.title(\"Relación entre materia grasa y extracto seco total\")\nplt.xlabel(\"Materia grasa (%)\")\nplt.ylabel(\"Extracto seco total (%)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-14-output-1.png){width=661 height=468}\n:::\n:::\n\n\nLa nube de puntos muestra una correlación positiva moderada: en general, cuando la materia grasa sube, el extracto seco también sube. Pero hay tres puntos que se separan claramente del conjunto: son los valores con `est` muy alto (en torno a 50-52%) combinados con `mg` normal o incluso baja. Estos puntos corresponden al período de verano que ya identificamos. El punto aislado con `mg` = 28% y `est` normal también destaca. Estos tres puntos anómalos son los que discutiremos con el equipo en la fase de conclusiones.\n\nColoreamos por trimestre para ver mejor la estructura estacional con una paleta legible:\n\n::: {#adcc9174 .cell execution_count=14}\n``` {.python .cell-code}\ndf_plot = df.copy()\ndf_plot['trimestre'] = df_plot.index.quarter.map(\n    {1: 'T1 (Ene-Mar)', 2: 'T2 (Abr-Jun)',\n     3: 'T3 (Jul-Sep)', 4: 'T4 (Oct-Dic)'}\n)\n\nsns.scatterplot(data=df_plot, x='mg', y='est',\n                hue='trimestre',\n                palette=['steelblue','green','red','orange'],\n                s=50, alpha=0.7)\nplt.title(\"EST vs MG coloreado por trimestre\")\nplt.xlabel(\"Materia grasa (%)\")\nplt.ylabel(\"Extracto seco total (%)\")\nplt.legend(title='Trimestre', bbox_to_anchor=(1.05, 1))\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-15-output-1.png){width=664 height=468}\n:::\n:::\n\n\nLos puntos del tercer trimestre (julio-septiembre) se sitúan claramente en la parte superior del gráfico, confirmando que la desviación de verano afecta a ambas variables simultáneamente, aunque con mayor intensidad en el extracto seco.\n\n### Variable derivada: humedad del queso desnatado (`hqd`)\n\nComo tecnólogos queseros, sabemos que un factor crítico de la textura del queso, y en consecuencia de su calidad, es la humedad del extracto seco desnatado. Este parámetro se calcula a partir del extracto seco y la materia grasa:\n\n$$\\text{hqd} = \\frac{(100 - \\text{est\\%})}{(100 - \\text{mg\\%})} \\times 100$$\n\nCreamos la nueva columna y analizamos su evolución:\n\n::: {#91e8bea4 .cell execution_count=15}\n``` {.python .cell-code}\ndf['hqd'] = ((100 - df['est']) / (100 - df['mg'])) * 100\n\nmedia_semanal = df[\"hqd\"].resample(\n    'W-MON', label='left', closed='left').mean()\ndt_semanal = df[\"hqd\"].resample(\n    'W-MON', label='left', closed='left').std()\n\nfig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 5), sharex=True)\n\nax1.plot(media_semanal, color='tab:blue')\nax1.set_title(\"Media y desviación típica semanal de la HQD\")\nax1.set_ylabel(\"Media HQD (%)\")\nax1.grid(True, linestyle='--', alpha=0.6)\nax1.tick_params(labelbottom=False)\n\nax2.plot(dt_semanal, color='tab:orange')\nax2.set_ylabel(\"D. Típica HQD\")\nax2.grid(True, linestyle='--', alpha=0.6)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-16-output-1.png){width=953 height=469}\n:::\n:::\n\n\nLa `hqd` muestra el patrón más revelador de todo el análisis. El fabricante mantiene la humedad razonablemente estable en torno al 70-71% durante la primera mitad del año, con algunos ajustes menores. En julio se produce una caída brusca hasta valores de 61-63%, la peor semana corresponde al 21 de julio con una `hqd` de 61,15%. Esta desviación de casi 10 puntos es muy significativa para la textura del camembert y explica las reclamaciones de queso demasiado seco que se recibieron en ese período.\n\n## Análisis de otras variables\n\n### pH\n\n::: {#a1eefd62 .cell execution_count=16}\n``` {.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['ph'], kde=True, ax=ax1)\nax1.set_title(\"Histograma del pH\")\nax1.set_xlabel(\"pH\")\n\nsns.boxplot(y=df['ph'], ax=ax2)\nax2.set_title(\"Boxplot del pH\")\nax2.set_ylabel(\"pH\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-17-output-1.png){width=949 height=372}\n:::\n:::\n\n\nEl pH muestra una distribución aproximadamente simétrica centrada en 4,68, con un rango habitual entre 4,5 y 4,9. El boxplot señala dos valores atípicos: el mínimo de 4,35 (18 de abril) y el máximo de 4,99 (25 de enero). El valor de 4,35 merece atención porque se aleja bastante del rango habitual; puede indicar una acidificación excesiva en esa fabricación o un error analítico. El pH y los cloruros se proponen como ejercicio de análisis completo al final del capítulo.\n\n### Cloruros\n\n::: {#5a318cb4 .cell execution_count=17}\n``` {.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['cloruros'], kde=True, ax=ax1)\nax1.set_title(\"Histograma de cloruros\")\nax1.set_xlabel(\"Cloruros (%)\")\n\nsns.boxplot(y=df['cloruros'], ax=ax2)\nax2.set_title(\"Boxplot de cloruros\")\nax2.set_ylabel(\"Cloruros (%)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-18-output-1.png){width=949 height=372}\n:::\n:::\n\n\nEl histograma de cloruros muestra una distribución aproximadamente simétrica en torno a 1,45-1,50%, con un rango habitual entre 1,1 y 1,9%. El boxplot señala un único valor atípico muy llamativo: -1%, registrado el 11 de febrero. Un contenido en cloruros negativo es físicamente imposible, por lo que se trata sin duda de un error de entrada de datos: probablemente se introdujo el valor con el signo menos por error. Este valor debe tratarse como un dato ausente (`NaN`) antes de cualquier análisis posterior.\n\n### Coliformes: un ejemplo de distribución asimétrica positiva\n\nLos recuentos de bacterias coliformes merecen un análisis específico porque su distribución es radicalmente distinta a la del resto de variables. Antes de hacer el histograma, veamos los estadísticos básicos:\n\n::: {#c5659b26 .cell execution_count=18}\n``` {.python .cell-code}\nprint(df['coliformes'].describe().round(1))\nprint(f\"\\nValores = 0: {(df['coliformes']==0).sum()}\")\nprint(f\"Valores > 1000: {(df['coliformes']>1000).sum()}\")\nprint(f\"Valores > 5000: {(df['coliformes']>5000).sum()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncount      210.0\nmean       650.9\nstd       2194.1\nmin          0.0\n25%          0.0\n50%         10.0\n75%        190.0\nmax      20200.0\nName: coliformes, dtype: float64\n\nValores = 0: 89\nValores > 1000: 28\nValores > 5000: 9\n```\n:::\n:::\n\n\nLa mediana es 10 ufc/g pero la media es 651 ufc/g, casi 65 veces mayor. El 42% de los valores son exactamente cero, y hay 9 valores por encima de 5.000 ufc/g, con un máximo de 20.200 ufc/g el 12 de agosto. Esta diferencia enorme entre la mediana y la media es la señal característica de una distribución muy asimétrica positiva.\n\n::: {#b12054d4 .cell execution_count=19}\n``` {.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsns.histplot(df['coliformes'].dropna(), bins=30, ax=ax1)\nax1.set_title(\"Histograma de coliformes (escala lineal)\")\nax1.set_xlabel(\"Coliformes (ufc/g)\")\n\n# escala logarítmica para ver mejor la distribución\ncol_nozero = df['coliformes'][df['coliformes'] > 0].dropna()\nsns.histplot(col_nozero, log_scale=True, bins=20, ax=ax2)\nax2.set_title(\"Histograma de coliformes (escala log)\")\nax2.set_xlabel(\"Coliformes (ufc/g, escala log)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-20-output-1.png){width=949 height=371}\n:::\n:::\n\n\nEn escala lineal, el histograma muestra una barra altísima en los valores bajos y una larga cola hacia la derecha: es la asimetría positiva extrema que veíamos en el capítulo 6 con los goles por partido, pero mucho más pronunciada. En escala logarítmica la distribución se hace visible con más detalle: la mayoría de los recuentos positivos están entre 10 y 1.000 ufc/g, y los valores muy altos son escasos pero existen.\n\nEste efecto es el mismo que el de un peso situado lejos del fulcro de una balanza: aunque sea un solo valor extremo, su distancia al centro multiplica su influencia sobre la media de forma desproporcionada. Por eso en variables con distribución muy asimétrica la media no es un buen descriptor del conjunto.\n\nVeamos la distribución mensual mediante un boxplot con los puntos individuales superpuestos. Como el logaritmo de cero no está definido, excluimos las muestras con recuento nulo: estas muestras no aportan información sobre la magnitud de la contaminación, y su inclusión aplastaría el gráfico hacia el cero haciendo ilegible el resto de la distribución. El alumno debe tener en cuenta que los meses con muchos ceros tendrán menos puntos representados, lo que también es información relevante sobre la higiene del proceso.\n\n::: {#f23a0d63 .cell execution_count=20}\n``` {.python .cell-code}\nimport calendar\nimport numpy as np\ndf = df.reset_index(drop=True)\ndf_plot_col = df[df['coliformes'] > 0].copy()\ndf_plot_col['log_coliformes'] = np.log10(df_plot_col['coliformes'])\ndf_plot_col['mes_abreviado'] = df_plot_col['fecha'].dt.strftime('%b')\nmeses_orden = [calendar.month_abbr[i] for i in range(1, 13)]\ndf_plot_col['mes_abreviado'] = pd.Categorical(\n    df_plot_col['mes_abreviado'],\n    categories=meses_orden,\n    ordered=True\n)\n\nfig, ax = plt.subplots(figsize=(12, 5))\nsns.boxplot(data=df_plot_col, x='mes_abreviado', y='log_coliformes',\n            fliersize=0, color='lightgray', ax=ax)\nsns.stripplot(data=df_plot_col, x='mes_abreviado', y='log_coliformes',\n              jitter=True, size=3, alpha=0.5, ax=ax)\nax.set_title(\"Coliformes por mes: boxplot con puntos individuales (log₁₀)\")\nax.set_xlabel(\"Mes\")\nax.set_ylabel(\"log₁₀ Coliformes (ufc/g)\")\nax.grid(axis='y', linestyle='--', alpha=0.6)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](102-pract01b-colab-camembert_files/figure-html/cell-21-output-1.png){width=1141 height=468}\n:::\n:::\n\n\nEl gráfico muestra picos puntuales dispersos a lo largo del año, sin un patrón estacional claro y sostenido. La mediana de los valores se incrementa desde abril hasta julio, donde hay un máximo que parece significativo, ya que la caja del boxplot no se solapa con las anteriores. De manera coherente con la información agregada, los valores individuales se concentran en primavera y verano, coincidiendo con las temperaturas ambientales más altas y el período de sustituciones de personal en vacaciones. El valor máximo de 20.200 ufc/g del 12 de agosto es el más llamativo. En invierno los recuentos son en general más bajos y más homogéneos.\n\n## Conclusiones y plan de acción\n\n### Análisis de resultados\n\nUna vez explorados los datos de todas las variables, podemos formular las hipótesis de trabajo:\n\n1. A principio de año hay un valor anómalo de materia grasa (28%, 26 de enero) que puede haberse debido a un error en la estandarización coincidiendo con una leche de invierno más rica en grasa. A pesar de esto, la `hqd` se mantuvo estable, lo que indica que el fabricante corrigió el extracto seco para compensar.\n\n2. Hay un claro error de entrada en cloruros: el valor -1% del 11 de febrero es físicamente imposible y debe tratarse como dato ausente.\n\n3. El pH de 4,35 del 18 de abril se aleja significativamente del rango habitual y merece verificación con el laboratorio.\n\n4. La desviación más importante del año es el aumento sostenido del extracto seco en julio, con un máximo de 52,61% el 21 de julio, que produjo una caída de la `hqd` hasta 61,15%. Esta bajada de casi 10 puntos respecto al objetivo habitual de 70-71% es la causa directa de las reclamaciones por queso demasiado seco recibidas en ese período.\n\n5. Los recuentos de coliformes no muestran una tendencia estacional clara, pero los valores más altos se concentran en verano, coincidiendo con el período de aumento de temperatura ambiente que incrementa el riesgo de crecimiento bacteriano. Hay que tener en cuenta también las sustituciones de personal en vacaciones, que pueden añadir más variabilidad a los resultados analíticos como consecuencia de la menor experiencia analítica de las personas temporales.\n\n6. Hay tres puntos en el gráfico de dispersión `est` vs `mg` que se separan claramente del conjunto: son candidatos a revisión analítica antes de repetir el análisis definitivo.\n\n### Comunicar: discusión en equipo\n\nHemos presentado el análisis al equipo de fabricación, laboratorio y producción. Las conclusiones de la reunión son:\n\n- El responsable de fabricación confirma que hace ajustes estacionales en la estandarización a lo largo del año para mantener la `hqd` constante. En verano, debido a las temperaturas más altas en las zonas de distribución, la práctica habitual es bajar moderadamente la `hqd` para evitar una proteólisis excesiva durante el ciclo de comercialización.\n- Este año el quesero fue sustituido durante vacaciones por una persona con menos experiencia, que forzó el extracto seco más de lo debido. Las reclamaciones de los clientes por queso demasiado seco en agosto confirman esta hipótesis.\n- El laboratorio confirma que los tres valores anómalos del gráfico de dispersión pueden corresponder a análisis incorrectos, y recomienda no tenerlos en cuenta en el análisis definitivo.\n- El valor negativo de cloruros es claramente un error de entrada de datos.\n\n### Plan de acción\n\nA la vista del análisis, el equipo propone las siguientes acciones:\n\n1. Revisar diariamente la composición de la leche para evitar errores de estandarización, especialmente en los cambios de estación.\n2. Mejorar la formación de las personas que cubren los puntos clave (quesero, analistas) en períodos de vacaciones o enfermedad, anticipando los ciclos de formación.\n3. Revisar los métodos analíticos con el laboratorio y valorar un estudio de precisión, incluyendo la variabilidad entre analistas.\n4. Establecer un sistema de seguimiento ágil de la `hqd` en tiempo real, para detectar desviaciones antes de que afecten al producto en el punto de venta.\n5. Valorar si los problemas de proteólisis en verano son generales o se concentran en clientes específicos con peores condiciones de conservación, ajustando el objetivo de `hqd` de verano de forma más precisa.\n6. Repetir el análisis eliminando los valores erróneos identificados, para verificar que las conclusiones se mantienen.\n\nDado que la capacidad del equipo es limitada, en sucesivas reuniones se priorizarán las acciones de mayor impacto y se establecerán indicadores que se publicarán semanalmente en paneles de planta.\n\n## Resumen del capítulo\n\nEn este capítulo hemos aplicado el flujo de trabajo completo del análisis de datos a una fabricación real de queso camembert. El análisis variable a variable ha permitido identificar errores de entrada (el valor negativo de cloruros), valores atípicos que requieren verificación (el pH de 4,35 en abril, el valor de materia grasa de 28% en enero) y la desviación estacional más importante del año: el aumento sostenido del extracto seco en julio, que produjo una caída de la humedad del queso desnatado de casi 10 puntos y originó reclamaciones de los clientes.\n\nLa serie temporal ha sido la herramienta clave para interpretar correctamente lo que el histograma mostraba como una simple distribución asimétrica: lo que parecía un valor atípico aislado era en realidad parte de una desviación estacional sostenida durante varias semanas. El análisis de los coliformes ha ilustrado con datos reales el concepto de distribución asimétrica positiva extrema, característica de los recuentos microbiológicos, y la razón por la que la mediana es más informativa que la media en este tipo de variables.\n\nEl capítulo concluye con una fase de comunicación en equipo que transforma el análisis estadístico en hipótesis de trabajo contrastadas con el conocimiento tecnológico y en un plan de acción priorizado. En el capítulo siguiente nos enfrentaremos al análisis de las entradas de leche en una gran fábrica de queso.\n\n## Ejercicios propuestos\n\n### Ejercicio 1: análisis completo de pH y cloruros\n\nRealiza el análisis exploratorio completo de las variables `ph` y `cloruros`, siguiendo la misma metodología aplicada a `est` y `mg` en este capítulo:\n\n- Histograma y boxplot\n- Serie temporal anual\n- Boxplot mensual\n- Interpretación de los valores atípicos detectados\n\nPara los cloruros, filtra previamente el valor negativo convirtiéndolo en `NaN` antes de representar los gráficos.\n\n### Ejercicio 2: repetir el análisis sin los valores erróneos\n\nEl laboratorio ha confirmado que los tres puntos anómalos del gráfico de dispersión `est` vs `mg` son probablemente errores analíticos. Utiliza Python o R para filtrarlos y repite el análisis completo con el dataset corregido. ¿Cambian las conclusiones?\n\nComo referencia, los criterios de filtrado son: valores de `mg` superiores a 27%, valores de `est` superiores a 52%, y valores con `mg` inferior a 22% y `est` superior a 48% de forma simultánea.\n\n### Ejercicio 3 (avanzado): transformación logarítmica de coliformes\n\nLos recuentos microbiológicos se analizan habitualmente en escala logarítmica. Crea una nueva columna `log_coliformes` con el logaritmo en base 10 de los recuentos (excluyendo los ceros), y compara el histograma de la escala lineal con el de la escala logarítmica. ¿Cómo cambia la forma de la distribución? ¿Qué valores de la escala logarítmica corresponden a los límites microbiológicos habituales en queso camembert?\n\n\n",
    "supporting": [
      "102-pract01b-colab-camembert_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}