<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Los rendimientos queseros – Análisis de datos industriales usando Excel y Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./105-valoracion-bmat.html" rel="next">
<link href="./090-balance-materia.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-de070a7b0ab54f8780927367ac907214.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-364982630eef5352dd1537128a8ed5cb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./085-intro-balance-materia.html">Análisis cuantitativo de la producción quesera</a></li><li class="breadcrumb-item"><a href="./100-rendimientos.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Los rendimientos queseros</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Análisis de datos industriales usando Excel y Python</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Introducción</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./020-estad-entorno.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">El análisis de datos de producción en el entorno industrial.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./030-herramientas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Herramientas para el análisis. La reproducibilidad.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./040-organizacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">La organización de los datos y el flujo de trabajo.Los datos ordenados o <em>arreglados</em> (<em>tidy data</em>)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./050-intro-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Introducción a Python en el entorno Google Colab</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./060-exploracion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">La exploración de los datos mediante gráficos.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./070-estad-simple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Medidas centrales y medidas de dispersión: la media y la varianza.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./080-pract01-camembert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Práctica 1. Análisis exploratorio de una fabricación de queso camembert usando <code>Python</code> y Google Colab.</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Análisis cuantitativo de la producción quesera</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./085-intro-balance-materia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Análisis cuantitativo de la producción quesera</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./090-balance-materia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">El balance de materia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./100-rendimientos.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Los rendimientos queseros</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./105-valoracion-bmat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">La valoración económica del balance de materia y los rendimientos.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./110-pract02-rendimientos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Práctica 2. Análisis de los rendimientos en fabricación de queso mediante <code>Python</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Anexos</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./800-media-centro-gravedad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">La media aritmética como centro de gravedad de un grupo de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./810-bibliografia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografía</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./900-indice_dataframes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Indice de DataFrames utilizados</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#un-ejemplo-de-cálculo-de-rendimientos" id="toc-un-ejemplo-de-cálculo-de-rendimientos" class="nav-link active" data-scroll-target="#un-ejemplo-de-cálculo-de-rendimientos"><span class="header-section-number">11.1</span> Un ejemplo de cálculo de rendimientos</a></li>
  <li><a href="#lectura-y-exploración-de-los-datos" id="toc-lectura-y-exploración-de-los-datos" class="nav-link" data-scroll-target="#lectura-y-exploración-de-los-datos"><span class="header-section-number">11.2</span> Lectura y exploración de los datos</a></li>
  <li><a href="#rendimiento-simple" id="toc-rendimiento-simple" class="nav-link" data-scroll-target="#rendimiento-simple"><span class="header-section-number">11.3</span> Rendimiento simple</a></li>
  <li><a href="#cálculo-de-la-cantidad-de-leche-necesaria-para-fabricar-1-kg-de-queso" id="toc-cálculo-de-la-cantidad-de-leche-necesaria-para-fabricar-1-kg-de-queso" class="nav-link" data-scroll-target="#cálculo-de-la-cantidad-de-leche-necesaria-para-fabricar-1-kg-de-queso"><span class="header-section-number">11.4</span> Cálculo de la cantidad de leche necesaria para fabricar 1 kg de queso</a></li>
  <li><a href="#la-materia-grasa" id="toc-la-materia-grasa" class="nav-link" data-scroll-target="#la-materia-grasa"><span class="header-section-number">11.5</span> La materia grasa</a></li>
  <li><a href="#el-estándar-de-fabricación-o-estándar-técnico" id="toc-el-estándar-de-fabricación-o-estándar-técnico" class="nav-link" data-scroll-target="#el-estándar-de-fabricación-o-estándar-técnico"><span class="header-section-number">11.6</span> El estándar de fabricación o estándar técnico</a></li>
  <li><a href="#la-importancia-de-la-estandarización-de-la-leche" id="toc-la-importancia-de-la-estandarización-de-la-leche" class="nav-link" data-scroll-target="#la-importancia-de-la-estandarización-de-la-leche"><span class="header-section-number">11.7</span> La importancia de la estandarización de la leche</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./085-intro-balance-materia.html">Análisis cuantitativo de la producción quesera</a></li><li class="breadcrumb-item"><a href="./100-rendimientos.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Los rendimientos queseros</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Los rendimientos queseros</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>En este capítulo abordaremos el análisis de la eficiencia de la transformación quesera, mediante los indicadores del rendimiento quesero, que calcularemos a partir de los valores analíticos de la leche de fabricación y del queso recién elaborado. Extraeremos diversas conclusiones:</p>
<ul>
<li>Estableceremos los parámetros de referencia de nuestro propio proceso, que nos servirán de punto de comparación para las fabricaciones que vayamos realizando.</li>
<li>Evaluaremos las causas posibles de las desviaciones, y veremos cómo proponer planes de acción para la reducción o eliminación de estas desviaciones.</li>
</ul>
<section id="un-ejemplo-de-cálculo-de-rendimientos" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="un-ejemplo-de-cálculo-de-rendimientos"><span class="header-section-number">11.1</span> Un ejemplo de cálculo de rendimientos</h2>
<p>En este ejemplo, vamos a suponer que elaboramos un queso de vaca, del que tenemos valores analíticos de producto terminado y de la leche utilizada en su elaboración. El proceso siempre tiene los mismos pasos tecnológicos, con la variabilidad que suponemos que es la habitual.</p>
<p>Utilizaremos <code>Python</code> para el cálculo, al final se proporciona también una hoja de cálculo con la información necesaria.</p>
<p>Como siempre, es opcional descargar los datos de ejemplo y abrir el cuaderno en Colab para ejecutar el código a medida que se avanza en el estudio.</p>
<p><a href="https://colab.research.google.com/github/juanriera/master-queseria/blob/master/100-rendimientos.ipynb" target="_blank" rel="noopener noreferrer">Abrir este cuaderno en Google Colab</a></p>
<p><a href="https://raw.githubusercontent.com/juanriera/master-queseria/master/datos/fab_queso_bm.csv" target="_blank" rel="noopener noreferrer">Descargar los datos de ejemplo utilizados en este cuaderno (archivo <code>fab_queso_bm.csv</code>)</a></p>
</section>
<section id="lectura-y-exploración-de-los-datos" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="lectura-y-exploración-de-los-datos"><span class="header-section-number">11.2</span> Lectura y exploración de los datos</h2>
<p>Antes de lanzarnos al análisis cuantitativo, siempre es conveniente una primera visualización de los datos, por si hubiese algún valor que nos pueda resultar cuestionable.</p>
<p>Es una mala práctica, aunque muy extendida, usar la hoja de cálculo para hacer la media aritmética de cada parámetro que vayamos a utilizar y trabajar con estos valores medios. En un conjunto de datos que recoja muchas fabricaciones, nunca podemos estar seguros de que el 100% de los valores sean correctos, que no haya habido errores de muestreo, analíticos o problemas de fabricación que hayan producido valores anormales. Por eso vamos a utilizar siempre los valores <em>medianos</em> y no los valores medios; como sabemos, la <strong>mediana</strong> es resistente a los valores anormales y extremos, mientras que la media no lo es.</p>
<p>Procedemos a leer los datos, y visualizamos las primeras lineas. Se incluye el código <code>python</code>que permite visualizar las tablas, en algunos casos se han formateado mediante <code>HTML</code>.</p>
<div id="e86eaa0c-670c-42ea-a5b4-3c5c42841039" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">fecha</th>
<th data-quarto-table-cell-role="th">receta</th>
<th data-quarto-table-cell-role="th">litros_past</th>
<th data-quarto-table-cell-role="th">est_past</th>
<th data-quarto-table-cell-role="th">mg_past</th>
<th data-quarto-table-cell-role="th">mp_past</th>
<th data-quarto-table-cell-role="th">kg_cuba</th>
<th data-quarto-table-cell-role="th">dens_cuba</th>
<th data-quarto-table-cell-role="th">est_cuba</th>
<th data-quarto-table-cell-role="th">mg_cuba</th>
<th data-quarto-table-cell-role="th">mp_cuba</th>
<th data-quarto-table-cell-role="th">formato</th>
<th data-quarto-table-cell-role="th">est_salida_salmuera</th>
<th data-quarto-table-cell-role="th">mg_salida_salmuera</th>
<th data-quarto-table-cell-role="th">ph_salida_salmuera</th>
<th data-quarto-table-cell-role="th">peso_queso_total</th>
<th data-quarto-table-cell-role="th">sal_queso</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">fecha_index</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-03-01</td>
<td>01/03/2022</td>
<td>vaca</td>
<td>15350</td>
<td>12.542</td>
<td>4.200</td>
<td>3.076</td>
<td>15811</td>
<td>1.030</td>
<td>11.37</td>
<td>4.01</td>
<td>2.94</td>
<td>barra</td>
<td>55.94</td>
<td>29.50</td>
<td>5.41</td>
<td>1960.0</td>
<td>1.55</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2022-03-04</td>
<td>04/03/2022</td>
<td>vaca</td>
<td>14530</td>
<td>13.312</td>
<td>4.002</td>
<td>3.673</td>
<td>14990</td>
<td>1.032</td>
<td>13.25</td>
<td>3.79</td>
<td>3.45</td>
<td>barra</td>
<td>54.58</td>
<td>29.80</td>
<td>5.88</td>
<td>1888.0</td>
<td>1.77</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-03-25</td>
<td>25/03/2022</td>
<td>vaca</td>
<td>12633</td>
<td>12.856</td>
<td>3.889</td>
<td>3.372</td>
<td>13012</td>
<td>1.030</td>
<td>12.89</td>
<td>3.69</td>
<td>3.21</td>
<td>barra</td>
<td>54.10</td>
<td>30.63</td>
<td>5.48</td>
<td>1555.0</td>
<td>1.32</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2022-04-01</td>
<td>01/04/2022</td>
<td>vaca</td>
<td>15430</td>
<td>13.151</td>
<td>3.886</td>
<td>3.218</td>
<td>15947</td>
<td>1.033</td>
<td>11.88</td>
<td>3.71</td>
<td>3.02</td>
<td>barra</td>
<td>56.76</td>
<td>30.51</td>
<td>5.36</td>
<td>1750.0</td>
<td>1.36</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-04-08</td>
<td>08/04/2022</td>
<td>vaca</td>
<td>15930</td>
<td>13.103</td>
<td>4.022</td>
<td>3.396</td>
<td>16453</td>
<td>1.033</td>
<td>11.93</td>
<td>3.81</td>
<td>3.23</td>
<td>barra</td>
<td>55.63</td>
<td>30.01</td>
<td>5.31</td>
<td>1955.0</td>
<td>1.90</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Los datos se corresponden con un conjunto de fabricaciones de queso de vaca, como hemos dicho. Las principales variables recogidas son las siguientes:</p>
<div id="91f86b98-7b0b-438f-b36a-93ea4bf89b11" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"><strong>Variable</strong></th>
<th style="text-align: left;" data-quarto-table-cell-role="th"><strong>Descripción</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fecha</td>
<td style="text-align: left;">Fecha de producción</td>
</tr>
<tr class="even">
<td style="text-align: left;">receta</td>
<td style="text-align: left;">Tipo de receta utilizada</td>
</tr>
<tr class="odd">
<td style="text-align: left;">litros_past</td>
<td style="text-align: left;">Litros de leche pasteurizada</td>
</tr>
<tr class="even">
<td style="text-align: left;">est_past</td>
<td style="text-align: left;">Extracto seco total de la leche pasteurizada (g/100 ml leche)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mg_past</td>
<td style="text-align: left;">Materia grasa de la leche pasteurizada (g/100 ml leche)</td>
</tr>
<tr class="even">
<td style="text-align: left;">mp_past</td>
<td style="text-align: left;">Materia proteica de la leche pasteurizada (g/100 ml leche)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">kg_cuba</td>
<td style="text-align: left;">Kilos totales de leche en la cuba</td>
</tr>
<tr class="even">
<td style="text-align: left;">est_cuba</td>
<td style="text-align: left;">Extracto seco total en cuba (g/100 g leche)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mg_cuba</td>
<td style="text-align: left;">Materia grasa en cuba (g/100 g leche)</td>
</tr>
<tr class="even">
<td style="text-align: left;">mp_cuba</td>
<td style="text-align: left;">Materia proteica en cuba (g/100 g leche)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lactosa_cuba</td>
<td style="text-align: left;">Contenido de lactosa en cuba (g/100 g leche)</td>
</tr>
<tr class="even">
<td style="text-align: left;">ph_final_moldeo_cuba</td>
<td style="text-align: left;">pH final antes del moldeo</td>
</tr>
<tr class="odd">
<td style="text-align: left;">formato</td>
<td style="text-align: left;">Formato del queso una vez moldeado</td>
</tr>
<tr class="even">
<td style="text-align: left;">est_salida_salmuera</td>
<td style="text-align: left;">Extracto seco total tras salida de salado (g/100 g queso)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mg_salida_salmuera</td>
<td style="text-align: left;">Materia grasa tras salida de salado (g/100 g queso)</td>
</tr>
<tr class="even">
<td style="text-align: left;">ph_salida_salmuera</td>
<td style="text-align: left;">pH tras salida de salado</td>
</tr>
<tr class="odd">
<td style="text-align: left;">peso_queso_total</td>
<td style="text-align: left;">Peso total del queso producido (medido a la salida de la salmuera)</td>
</tr>
<tr class="even">
<td style="text-align: left;">sal_queso</td>
<td style="text-align: left;">Contenido de sal en el queso tras salida de salado (g/ 100 g queso)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="rendimiento-simple" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="rendimiento-simple"><span class="header-section-number">11.3</span> Rendimiento simple</h2>
<p>Por esta razón, debemos calcular el rendimiento mediante parámetros que no se vean afectados por la humedad del queso, sino que reflejen con precisión la calidad del trabajo quesero. La mejor forma de hacerlo consiste en calcular el porcentaje de materia quesera que hemos sido capaces de retener en el queso. Dado que los elementos de valor de la leche, que son los que se utilizan en el pago por calidad, son la materia grasa y la proteína, calcularemos la recuperación de materia grasa, de materia proteica y de extracto seco magro.</p>
<p>Estos valores son propios de cada tecnología quesera, y cada uno sirve de referencia para comprender cuáles son los diferentes problemas en fabricación,</p>
<ul>
<li>Una mala retención de materia grasa</li>
<li>Una mala retención de proteína</li>
<li>Una mala retención de extracto seco magro</li>
</ul>
<hr>
<p>El laboratorio nos facillita la información analítica de la leche pasteurizada en porcentaje masa/volumen, mientas que la leche en cubas y el queso es masa/masa. Esto es así porque la cantidad de leche que pasa por el pasteurizador se mide con un contador volumétrico, mientras que en la cuba se mide con una célula de carga.</p>
<p>Si el volumen de leche en cuba se midiese también con contador volumétrico, necesitaríamos convertir los resultados analíticos a masa/volumen para obtener los kilos de cada materia, utilizando la densidad.</p>
<p>En la práctica, usar una densidad promedio fija o ajustada por estaciones funciona bastante bien, y evita los errores de medida de este parámetro que parecen sencillos pero siempre están sometidos al error de muestreo, además de la necesidad de corregir la temperatura.</p>
<p>Veamos los datos analíticos del queso</p>
<div id="f808574a-96d4-4fad-9574-5f776a536522" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"><strong>Composición del queso</strong></th>
<th data-quarto-table-cell-role="th"><strong>Media (g/100 g)</strong></th>
<th data-quarto-table-cell-role="th"><strong>Mediana (g/100 g)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>EST a salida de salado</td>
<td>55.16%</td>
<td>54.85%</td>
</tr>
<tr class="even">
<td>MG a salida de salado</td>
<td>29.74%</td>
<td>29.80%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Para hacer este producto, estamos trabajando con una leche que hemos enriquecido en MG y MP, cuya composición es:</p>
<div id="3428c6b6-d6ab-47ca-a91a-2e5fe9f2dd94" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"><strong>Composición materia prima</strong></th>
<th style="text-align: left;" data-quarto-table-cell-role="th"><strong>Media (g/L)</strong></th>
<th style="text-align: left;" data-quarto-table-cell-role="th"><strong>Mediana (g/L)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Extracto seco total (ESM)</td>
<td style="text-align: left;">123.17</td>
<td style="text-align: left;">119.30</td>
</tr>
<tr class="even">
<td style="text-align: left;">Materia grasa (MG)</td>
<td style="text-align: left;">38.48</td>
<td style="text-align: left;">38.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Proteínas totales (MP)</td>
<td style="text-align: left;">31.98</td>
<td style="text-align: left;">32.10</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="cálculo-de-la-cantidad-de-leche-necesaria-para-fabricar-1-kg-de-queso" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="cálculo-de-la-cantidad-de-leche-necesaria-para-fabricar-1-kg-de-queso"><span class="header-section-number">11.4</span> Cálculo de la cantidad de leche necesaria para fabricar 1 kg de queso</h2>
<p>Sabemos que nuestro proceso de fabricación quesera consiste en la coagulación de la caseína y expulsión de suero, y que la materia grasa queda retenida en la red de caseína.</p>
<p>Este concepto es la base fundamental de la comprensión de la tecnología quesera: es el rendimiento en la recuperación de la proteína el que nos va a definir todo el proceso, la materia grasa “acompañará” de forma estática (aunque tendrá influencia en el desuerado)</p>
<p>Por esta razón, el principal elemento del rendimiento en la definición de la tecnología es el porcentaje de recuperación de proteína en el extracto seco magro (aislamos el efecto la grasa)</p>
<p>Hemos definido nuestro producto mediante los análisis de EST y MG; necesitamos saber el resto de parámetros, en concreto el ESM que estamos definiendo para nuestro producto:</p>
<div id="c248e5d4-b774-4ad1-bd5d-a14f6bb715cf" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"><strong>Composición del queso</strong></th>
<th style="text-align: left;" data-quarto-table-cell-role="th"><strong>Media (g/100 g)</strong></th>
<th style="text-align: left;" data-quarto-table-cell-role="th"><strong>Mediana (g/100 g)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EST a salida de salado</td>
<td style="text-align: left;">55.16%</td>
<td style="text-align: left;">54.85%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MG a salida de salado</td>
<td style="text-align: left;">29.74%</td>
<td style="text-align: left;">29.80%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ESM a salida de salado)</td>
<td style="text-align: left;">25.42%</td>
<td style="text-align: left;">25.05%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MG/EST a salida de salado</td>
<td style="text-align: left;">53.91%</td>
<td style="text-align: left;">54.33%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Ahora necesitamos conocer cuál es la tasa o ratio de conversión en ESM de queso del ESM, o bien de la MP, de la leche en cubas. Para ello calculamos estos ratios, que vamos a llamar <strong>coeficiente de recuperación de ESM</strong>, y el <strong>coeficiente de recuperación de MP</strong> junto con el <strong>coeficiente de recuperación de MG</strong>,que indicará la cantidad de MG que somos capaces de recuperar en el queso.</p>
<p>Si la recuperación de MG fuese perfecta, el coeficiente de recuperación sería 100%. El coeficiente refleja que hay pérdidas de MG, bien en el suero, bien en los finos de moldeo o en cuajada que se ha caído, etc, en resumen, que no ha ido a parar al queso moldeado. Podemos argumentar, correctamente, que la parte de los finos recoge también la eficiencia de la coagulación, pero al final lo que nos interesa es recoger la conversión real en queso de nuestra materia prima, excluyendo todo lo que constituyen las <strong>pérdidas de proceso</strong>.</p>
<p>El <strong>coeficiente de recuperación de ESM</strong> tiene un valor mucho más bajo, porque hay una parte significativa del ESM de la leche que vamos a perder en el suero y durante el salado, como las proteínas solubles, la lactosas y las sales minerales; por otra parte, vamos a incorporar a ese ESM la sal añadida durante el salado.</p>
<p>Lo importante es que el valor de este coeficiente, si nuestro proceso es estable, debe ser siempre constante: en un proceso estable, tanto las pérdidas como las ganancias deben ser muy semejantes de un día a otro, si las condiciones del proceso se han mantenido. Por lo tanto, lo que nos interesa es este valor <em>mediano</em> del coeficiente, y debemos asegurarnos de que es regular.</p>
<p>EL último coeficiente, el <strong>coeficiente de recuperación de MP</strong> se basa en esta misma regularidad del proceso para establecer la relación entre la proteína puesta en cuba y el ESM del queo. La ventaja de este coeficiente es que con los medios analíticos habituales, es más fácil analizar la leche mediante un NIR (<em>near-infrared</em>) como el MilkoScan, que hacer un extraco seco convencional en estufa.</p>
<div id="64ee31df-cdec-4029-8ba1-b1cbcb7dd28f" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">### 1. Cálculos de cuba</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'est_kg_cuba'</span>] <span class="op">=</span> df[<span class="st">'kg_cuba'</span>] <span class="op">*</span> df[<span class="st">'est_cuba'</span>] <span class="op">/</span> <span class="dv">100</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'mg_kg_cuba'</span>] <span class="op">=</span> df[<span class="st">'kg_cuba'</span>] <span class="op">*</span> df[<span class="st">'mg_cuba'</span>] <span class="op">/</span> <span class="dv">100</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'mp_kg_cuba'</span>] <span class="op">=</span> df[<span class="st">'kg_cuba'</span>] <span class="op">*</span> df[<span class="st">'mp_cuba'</span>] <span class="op">/</span> <span class="dv">100</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'esm_kg_cuba'</span>] <span class="op">=</span> df[<span class="st">'est_kg_cuba'</span>] <span class="op">-</span> df[<span class="st">'mg_kg_cuba'</span>] </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">### 2. Cálculos de queso </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">### ejemplo de cómo poner fórmulas largas para que no desborden</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">### la línea</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'est_kg_queso'</span>] <span class="op">=</span> (</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'peso_queso_total'</span>] <span class="op">*</span> df[<span class="st">'est_salida_salmuera'</span>] <span class="op">/</span> <span class="dv">100</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'mg_kg_queso'</span>] <span class="op">=</span> (</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'peso_queso_total'</span>] <span class="op">*</span> df[<span class="st">'mg_salida_salmuera'</span>] <span class="op">/</span> <span class="dv">100</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'esm_kg_queso'</span>] <span class="op">=</span> df[<span class="st">'est_kg_queso'</span>] <span class="op">-</span> df[<span class="st">'mg_kg_queso'</span>]</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'sal_kg_queso'</span>] <span class="op">=</span> df[<span class="st">'peso_queso_total'</span>] <span class="op">*</span> df[<span class="st">'sal_queso'</span>]<span class="op">/</span><span class="dv">100</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">### 3. Coeficientes de recuperación (expresado en porcentaje)</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'coef_recup_mg'</span>]  <span class="op">=</span> df[<span class="st">'mg_kg_queso'</span>]<span class="op">/</span>df[<span class="st">'mg_kg_cuba'</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'coef_recup_mp'</span>]  <span class="op">=</span> df[<span class="st">'esm_kg_queso'</span>]<span class="op">/</span>df[<span class="st">'mp_kg_cuba'</span>] <span class="op">*</span> <span class="dv">100</span> </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'coef_recup_esm'</span>] <span class="op">=</span> df[<span class="st">'esm_kg_queso'</span>]<span class="op">/</span>df[<span class="st">'esm_kg_cuba'</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"Coeficiente de recuperación de materia grasa "</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"(MG queso/MG leche en cuba): "</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>df[<span class="st">'coef_recup_mg'</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"Coeficiente de recuperación de proteína "</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"(ESM queso/MP leche en cuba): "</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>df[<span class="st">'coef_recup_mp'</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"Coeficiente de recuperación de extracto seco magro "</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"(ESM queso/ESM leche en cuba): "</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>df[<span class="st">'coef_recup_esm'</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Coeficiente de recuperación de materia grasa (MG queso/MG leche en cuba): 91.694
Coeficiente de recuperación de proteína (ESM queso/MP leche en cuba): 94.457
Coeficiente de recuperación de extracto seco magro (ESM queso/ESM leche en cuba): 35.948</code></pre>
</div>
</div>
<p>A partir de aquí, hacemos los cálculos teóricos del estándar técnico.</p>
<p>Utilizando el coeficiente de recuperación de la MP, podemos calcular la cantidad de ESM que vamos a recuperar. La mediana de la cantidad de proteína que tenemos en la leche es 32,10 g/L; sabemos que con 1 L de leche vamos a obtener en el queso</p>
<p><span class="math display">\[
\frac{32.10\ g\ proteína}{1\ L\ leche}*\ \frac{0.94457\ g\ ESM}{1\ g\ proteína} = 30.32\ g\ ESM\ en\ el\ queso\ por\ litro\ de\ leche
\]</span></p>
<p>Esta es la conversión clave de nuestra tecnología, y es conocida como <strong><em>coeficiente G</em></strong> en honor a su autor, Antoine M Guérault, que lo introdujo formalmente por primera vez por en su libro <em>La fromagerie devant les techniques nouvelles,</em> en 1966; desde entonces sigue utilizándose con plena validez. Originalmente, el coeficiente indica el porcentaje de ESM que hemos recuperado en el queso, dividiendo el ESM del queso entre el ESM de la leche puesta en fabricación, aunque es más habitual usar el coeficiente de recuperación de proteína en vez del de ESM, como hemos hecho arriba.</p>
<p>Como comentamos más atrás, para una tecnología concreta, normalmente la cantidad de sal incluida en el salado y las pérdidas de ESM en el proceso de fabricación deberían mantenerse en una horquilla más o menos estrecha, de acuerdo con la variabilidad de nuestro proceso y nuestra precisión analítica. Si el valor del coeficiente se mantiene en estos límites, nos indicará que la transformación se ha realizado dentro de los valores normales de la tecnología; en caso contrario, si hemos tenido valores anormalmente altos o bajos, será indicador de incidencias tecnológicas que intentaremos explicar para poner en marcha acciones correctivas. En este capítulo veremos el cálculo de los índices; en un capítulo posterior abordaremos el análisis de las desviaciones.</p>
<p>Como sabemos la cantidad de ESM que vamos a obtener de 1 L de leche, podemos calcular los litros de leche que necesitamos para obtener 1 kg de queso mediante una conversión simple. A este valor lo llamaremos <em>litraje unitario</em>.</p>
<p><span class="math display">\[
\text{Litraje unitario} = \frac{25.05\ g\ ESM}{100\ g\ queso\ }*\ \frac{1000\ g\ queso}{1\ kg\ queso}*\ \frac{1\ L\ leche}{30,32\ g\ ESM} = 8,261\ L\ leche\ para\ hacer\ 1\ kg\ de\ queso
\]</span></p>
<p>y el consumo de MP por kilo de queso es el que resulta de calcular</p>
<p><span class="math display">\[
8,261\ L\ leche*\ \frac{32.10\ g\ MP}{1\ L\ leche} = 265,18\ g\ MP\ por\ kilo\ de\ queso
\]</span></p>
<div id="0d8849d6" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">### 5. Litrajes unitarios: (g ESM en queso por kilo de queso) / (g MP leche en cuba por litro de leche) </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'litraje_unitario'</span>]  <span class="op">=</span> (df[<span class="st">'esm_kg_queso'</span>]<span class="op">/</span>df[<span class="st">'peso_queso_total'</span>]) <span class="op">*</span> <span class="dv">100</span> <span class="op">/</span> ((df[<span class="st">'mp_cuba'</span>] <span class="op">/</span> <span class="dv">100</span> ) <span class="op">*</span> df[<span class="st">'coef_recup_mp'</span>])</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">### 6. Consumos de materia por kilo de queso (g / kg)</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'consumo_mg_kg'</span>]  <span class="op">=</span> df[<span class="st">'mg_kg_cuba'</span>]<span class="op">/</span>df[<span class="st">'peso_queso_total'</span>] <span class="op">*</span> <span class="dv">1000</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'consumo_mp_kg'</span>]  <span class="op">=</span> df[<span class="st">'mp_kg_cuba'</span>]<span class="op">/</span>df[<span class="st">'peso_queso_total'</span>] <span class="op">*</span> <span class="dv">1000</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="926a46e1" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.dates <span class="im">as</span> mdates</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>esm_queso <span class="op">=</span> df[<span class="st">'esm_kg_queso'</span>] <span class="op">/</span> df[<span class="st">'peso_queso_total'</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>mp_cuba <span class="op">=</span> df[<span class="st">'mp_cuba'</span>] <span class="op">*</span> <span class="dv">10</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Graficar y capturar los ejes</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> esm_queso.plot(label<span class="op">=</span><span class="st">'ESM del Queso (g/100g)'</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>mp_cuba.plot(label<span class="op">=</span><span class="st">'Materia Prima en Cuba (g/L)'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Definir y aplicar el formateador</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Usamos "%d-%m" para mostrar Día-Mes sin el año.</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(df.index)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>date_form <span class="op">=</span> mdates.DateFormatter(<span class="st">"</span><span class="sc">%d</span><span class="st">-%m"</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_formatter(date_form)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Ajustes de visualización</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>) </span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>plt.tight_layout() <span class="co"># Ajusta automáticamente el gráfico para que las etiquetas no se corten</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="100-rendimientos_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Es necesario insistir en que estos cálculos teóricos sólo son válidos en nuestras condiciones de trabajo precisas:</p>
<ul>
<li><p>con la composición en ESM de nuestro queso</p></li>
<li><p>con la composición de proteína de nuestra leche</p></li>
<li><p>con la tasa de recuperación de la proteína de la leche en el ESM del queso de nuestro específico proceso de fabricación.</p></li>
</ul>
<p>Son valores teóricos que utilizamos como valor objetivo, y que pueden variar a medida que adaptemos o variemos nuestra tecnología. Para cualquier otro producto, otra composición de leche y/u otro proceso de fabricación, deberemos recalcular nuestro litraje por kilo y nuestro consumo de materia.</p>
<p>Sabemos que, en nuestras condiciones, 8,261 L de leche deben darnos 1 kg de queso. Si obtenemos más o menos queso querrá decir que nuestras hipótesis de partida no se han cumplido, y analizando los tres elementos básicos, sabremos la razón de la desviación:</p>
<ul>
<li><p>Nuestra leche tiene una composición diferente</p></li>
<li><p>Nuestro queso tiene una composición diferente</p></li>
<li><p>Nuestra recuperación de proteína ha sido diferente.</p></li>
</ul>
<p>Si disponemos de la analítica correspondiente, podremos tomar las decisiones correctas; no es lo mismo actuar ante un problema de composición de leche que ante un problema de composición de queso o un problema de tecnología quesera (el extracto seco magro del queso es consecuencia de la tecnología quesera). Otros factores pueden influir directamente en el coeficiente de recuperación de proteína, por ejemplo, la cantidad de proteína coagulable (caseína) frente a la proteína total analizada puede variar a lo largo del año, y el análisis de proteína total no nos da una indicación de esta ratio.</p>
</section>
<section id="la-materia-grasa" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="la-materia-grasa"><span class="header-section-number">11.5</span> La materia grasa</h2>
<p>Hasta aquí hemos hablado de proteína y ESM, pero ¿y la materia grasa?</p>
<p>En nuestro análisis de rendimiento hemos calculado también un % de recuperación de MG. Sin embargo, no utilizaremos este % para calcular el litraje, lo haremos tal como hemos visto, con la transformación de la proteína en ESM. La razón es que <em>la tecnología quesera nos permite actuar sobre el ESM del queso, pero la MG depende de la estandarización</em>, como veremos a continuación.</p>
<p>Como el cálculo que hemos realizado con el coeficiente de recuperación de la MP nos da los litros de leche que necesitamos para hacer 1 kg de queso, y tenemos una composición de nuestra leche, podemos saber la cantidad de MG que vamos a tener en esos litros. Por otra parte, sabemos la MG que hemos definido en nuestro queso de forma empírica, es decir, en la práctica: mediante un promedio de los diferentes análisis de nuestro producto que hemos ido obteniendo.</p>
<p>Hemos calculado nuestro litraje unitario: necesitamos 8,261 L leche para hacer 1 kg de queso.</p>
<p>Según nuestra composición de leche, 1 L de leche tiene 38,10 g de MG, luego los 8,261 L de leche tendrán</p>
<p><span class="math display">\[
8,261\ L\ leche*\ \frac{38.10\ g\ MG}{1\ L\ leche} = 314,74\ g\ MG
\]</span></p>
<p>Es decir, para fabricar 1 kg de queso necesitamos 8.261 L leche, que según su composición tienen 314,74 g MG</p>
<p>Sin embargo, la analítica de nuestro queso nos dice que en 1 kg de queso tenemos 29.80% de MG, es decir 298.0 g de MG por kilo de queso.</p>
<p>¿A qué se debe esta diferencia? La respuesta es: <em>a las pérdidas de MG en el proceso</em>, es decir, <em>a nuestro porcentaje de recuperación de MG.</em></p>
<p>Podemos calcular este porcentaje mediante la fracción</p>
<p><span class="math display">\[
\frac{MG\ en\ el\ queso}{MG\ en\ la\ leche\ de\ fabricación}\ =\ \frac{298,0\ g\ MG/kg\ en\ el\ queso}{314,74\ g\ MG/kg\ en\ la\ leche\ de\ fabricación} = 0,9468
\]</span></p>
<p>Es decir, nuestra recuperación teórica de MG es del 94.68%</p>
<p>¿Por qué <em>recuperación teórica</em>? Porque es la que resulta de hacer los cálculos según nuestros datos de composición de leche, composición del queso y recuperación de proteína, no de los análisis realizados.</p>
<p>De la misma forma que en el caso de la recuperación de proteína, si nuestra recuperación de MG es diferente de la calculada teóricamente, debemos encontrar la explicación en los mismos factores:</p>
<ul>
<li><p>Composición real de la leche</p></li>
<li><p>Composición real del queso</p></li>
<li><p>Variaciones en la tecnología</p></li>
</ul>
<p>Estas variaciones pueden implicar una mayor pérdida de MG, en el suero de quesería o en los finos de queso (o en ambos), y que en parte puede recuperarse mediante un desnatado del suero.</p>
</section>
<section id="el-estándar-de-fabricación-o-estándar-técnico" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="el-estándar-de-fabricación-o-estándar-técnico"><span class="header-section-number">11.6</span> El estándar de fabricación o estándar técnico</h2>
<p>Como hemos visto, la construcción del estándar técnico y el seguimiento de la tecnología quesera no se hacen siguiendo el consumo de <em>litros de leche</em>, sino de la cantidad de proteína y grasa utilizadas. Por esta razón, la construcción del estándar debe proporcionar las cantidades de MG y MP necesarias para obtener 1 kg de queso, y no sólo el litraje en cuba.</p>
<p>El razonamiento y cálculos que hemos ido realizando, se suelen recoger en lo que se llama un <em>estándar técnico de fabricación</em>. Este documento recoge los valores estándar de nuestra tecnología dada una composición media de nuestro queso obtenido (o un objetivo a obtener) y una composición de leche de partida. Al final del capítulo se puede descargar una hoja Excel con el estándar de fabricacion que hemos ido construyendo para nuestro queso de vaca.</p>
<p>Llamamos <strong>MG teórica en la cuba</strong> a la cantidad de MG que calculamos que vamos a tener en la cuba, es decir, en nuestros 8,261 L de leche a fabricar. Esta MG puede provenir de la leche de partida o del resultado de estandarizar la leche en MG, añadiendo nata o bien leche desnatada, para conseguir la cantidad de MG que nos permita alcanzar los valores de MG deseada en el queso.</p>
<p>De la misma forma, llamamos <strong>MP en cuba</strong> a la cantidad de MP que hemos puesto en cuba, ya sea la de la leche de partida o del resultado de haber estandarizado la leche mediante el añadido de proteínas.</p>
<p>En el caso de nuestro queso de vaca, vemos un proceso de fabricación que <em>no</em> usa estandarización y que no está recuperando la materia grasa del suero; las diferencias entre la MG en cuba y la MG en el queso se consideran pérdidas de proceso y su reducción es un objetivo prioritario del proceso de mejora.</p>
</section>
<section id="la-importancia-de-la-estandarización-de-la-leche" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="la-importancia-de-la-estandarización-de-la-leche"><span class="header-section-number">11.7</span> La importancia de la estandarización de la leche</h2>
<p>La tecnología quesera se diseña para optimizar el coeficiente de recuperación de proteína. Aunque la retención de materia grasa (MG) también depende de factores tecnológicos como el corte, el calentamiento y el pH, no está directamente controlada por la tecnología, aunque sí influenciada por ella.</p>
<p>En una tecnología concreta, con parámetros de trabajo fijados, cuando la cantidad de MG en la leche es superior a la definida en el proceso, se producen dos efectos:</p>
<ul>
<li><p>Una parte del exceso de MG queda retenida en la matriz proteica, lo que incrementa la cantidad de grasa en el queso y, por tanto, modifica su composición.</p></li>
<li><p>Otra parte de la MG se pierde en el suero, ya que las condiciones del proceso determinan una relación fija con la cantidad total de MG de partida. Es decir, al aumentar la MG inicial, también aumentan las pérdidas relativas en el suero.</p></li>
</ul>
<p>Desgraciadamente, no es posible calcular teóricamente cuánta MG se retendrá en el queso y cuánta se perderá en el suero, ya que estas cantidades no responden a una función conocida. Lo que sí sabemos es que:</p>
<ul>
<li><p>Aumentarán las pérdidas.</p></li>
<li><p>Se modificará la composición del queso, lo que puede alterar su textura y el valor nutricional declarado.</p></li>
<li><p>Se alterará la expulsión de suero de la matriz proteica, lo que afectará la cantidad de lactosa retenida en la cuajada y, en consecuencia, las curvas de acidificación, el extracto seco, etc.</p></li>
</ul>
<p>Cuando la MG es <em>inferior</em> a la definida, estos efectos se producen en sentido inverso, afectando tanto la composición del queso como su comportamiento tecnológico.</p>
<p>Para minimizar estas variaciones y mantener una composición constante del producto, es necesario:</p>
<ul>
<li><p>Trabajar con leche que tenga un contenido estable de materia grasa (MG) y materia proteica (MP). Dado que la composición de la leche varía estacionalmente, esto implica estandarizarla en MG y MP, <strong>manteniendo constante la relación MG/MP</strong>.</p></li>
<li><p>Adaptar la tecnología de forma estacional, ya que la variación estacional no solo afecta la relación MG/MP, sino también la proporción de caseína coagulable dentro del total de proteínas.</p></li>
</ul>
<p>Es fundamental recordar lo señalado al definir el estándar técnico: <em>la tecnología permite modificar el extracto seco magro (ESM) del queso, pero la MG depende principalmente de la cantidad presente en la leche de fabricación</em>. <strong>No es posible modificar la cantidad de grasa en el queso mediante la tecnología quesera en la cuba</strong>; es necesario preparar la leche con la cantidad de grasa adecuada para cubrir tanto la retención esperada como las pérdidas previstas.</p>
<p>En la medida en que no se puedan realizar estas adaptaciones, se deberá aceptar una mayor variabilidad en el producto, con dos consecuencias:</p>
<ul>
<li><p>Irregularidad en el producto final, que afecta la aceptación por parte del consumidor.</p></li>
<li><p>Variación en el coste del producto, que puede dar lugar a pérdidas económicas no previstas.</p></li>
</ul>
<p>Por estas razones, es imprescindible realizar un seguimiento detallado de las desviaciones tecnológicas, para comprender mejor el comportamiento del proceso y actuar eficazmente sobre sus causas. Las desviaciones observadas deben analizarse siempre apoyándose en el conocimiento tecnológico, para que los planes correctivos sean eficaces.</p>
<p>Conociendo el coste de la MG y de la MP pagada, es posible calcular el valor económico de cada desviación, lo que permite priorizar las acciones correctivas según su impacto financiero. El análisis de las desviaciones se hace en un capítulo posterior.</p>
<p>Hay una hoja Excel con todos los cálculos, que incluye también los estándares de fabricacion que veremos en el capítulo siguiente para el resto de recetas.</p>
<p><a href="https://raw.githubusercontent.com/juanriera/master-queseria/master/datos/2025-11-06-ejemplo-std-tecnico.xlsx" target="_blank" rel="noopener noreferrer">Abrir hoja Excel con estándar técnico</a></p>
<p>Veamos las características de los quesos, excluyendo ya los ensayos de I+D</p>
<div id="e16abdb7" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'esm_salida_salmuera'</span>] <span class="op">=</span> df[<span class="st">'est_salida_salmuera'</span>]<span class="op">-</span>df[<span class="st">'mg_salida_salmuera'</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'hqd_salida_salmuera'</span>] <span class="op">=</span> (<span class="dv">100</span> <span class="op">-</span> df[<span class="st">'est_salida_salmuera'</span>])<span class="op">/</span>(<span class="dv">100</span> <span class="op">-</span> df[<span class="st">'mg_salida_salmuera'</span>])</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'ges_salida_salmuera'</span>] <span class="op">=</span> df[<span class="st">'mg_salida_salmuera'</span>] <span class="op">/</span> df[<span class="st">'est_salida_salmuera'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="27433acc" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar receta 'i+D'</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>df_filtrado <span class="op">=</span> df[df[<span class="st">'receta'</span>] <span class="op">!=</span> <span class="st">'i+D'</span>].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear paleta de colores por receta</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>recetas <span class="op">=</span> df_filtrado[<span class="st">'receta'</span>].unique()</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>palette <span class="op">=</span> sns.color_palette(<span class="st">'tab10'</span>, n_colors<span class="op">=</span><span class="bu">len</span>(recetas))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>color_dict <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(recetas, palette))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>df[df[<span class="st">'receta'</span>] <span class="op">!=</span> <span class="st">'i+D'</span>], </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>                x<span class="op">=</span><span class="st">'est_salida_salmuera'</span>, </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>                y<span class="op">=</span><span class="st">'mg_salida_salmuera'</span>, </span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>                hue<span class="op">=</span><span class="st">'receta'</span>, </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                palette <span class="op">=</span> color_dict,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>                s<span class="op">=</span><span class="dv">80</span>, </span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>                <span class="co"># edgecolor = 'black',</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>                alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular y dibujar centroides</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>centroides_est_mg <span class="op">=</span> df.groupby(<span class="st">'receta'</span>)[[<span class="st">'est_salida_salmuera'</span>, <span class="st">'mg_salida_salmuera'</span>]].median()</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> receta <span class="kw">in</span> recetas:</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    centro <span class="op">=</span> centroides_est_mg.loc[receta]</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    plt.scatter(</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>        centro[<span class="st">'est_salida_salmuera'</span>],</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>        centro[<span class="st">'mg_salida_salmuera'</span>],</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>color_dict[receta],</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>        marker<span class="op">=</span><span class="st">'X'</span>,</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>        s<span class="op">=</span><span class="dv">150</span>,</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">'black'</span>,</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="ss">f'Centroide </span><span class="sc">{</span>receta<span class="sc">}</span><span class="ss">'</span></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Rendimientos de MP y MG en fabricación de queso'</span>)</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Composicion EST'</span>)</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Composicion MG'</span>)</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">'Receta'</span>) <span class="co"># Mostrar leyenda para la especie</span></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Mover la leyenda fuera del gráfico</span></span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>plt.legend(bbox_to_anchor<span class="op">=</span>(<span class="fl">1.05</span>, <span class="dv">1</span>), loc<span class="op">=</span><span class="st">'upper left'</span>, borderaxespad<span class="op">=</span><span class="fl">0.</span>)</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="100-rendimientos_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="0561c744" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(centroides_est_mg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        est_salida_salmuera  mg_salida_salmuera
receta                                         
vaca                  54.85                29.8</code></pre>
</div>
</div>
<div id="ce164b41" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">fecha</th>
<th data-quarto-table-cell-role="th">receta</th>
<th data-quarto-table-cell-role="th">litros_past</th>
<th data-quarto-table-cell-role="th">est_past</th>
<th data-quarto-table-cell-role="th">mg_past</th>
<th data-quarto-table-cell-role="th">mp_past</th>
<th data-quarto-table-cell-role="th">kg_cuba</th>
<th data-quarto-table-cell-role="th">dens_cuba</th>
<th data-quarto-table-cell-role="th">est_cuba</th>
<th data-quarto-table-cell-role="th">mg_cuba</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">sal_kg_queso</th>
<th data-quarto-table-cell-role="th">coef_recup_mg</th>
<th data-quarto-table-cell-role="th">coef_recup_mp</th>
<th data-quarto-table-cell-role="th">coef_recup_esm</th>
<th data-quarto-table-cell-role="th">litraje_unitario</th>
<th data-quarto-table-cell-role="th">consumo_mg_kg</th>
<th data-quarto-table-cell-role="th">consumo_mp_kg</th>
<th data-quarto-table-cell-role="th">esm_salida_salmuera</th>
<th data-quarto-table-cell-role="th">hqd_salida_salmuera</th>
<th data-quarto-table-cell-role="th">ges_salida_salmuera</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">fecha_index</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-03-01</td>
<td>01/03/2022</td>
<td>vaca</td>
<td>15350</td>
<td>12.542</td>
<td>4.200</td>
<td>3.076</td>
<td>15811</td>
<td>1.030</td>
<td>11.37</td>
<td>4.01</td>
<td>...</td>
<td>30.3800</td>
<td>91.195703</td>
<td>111.483566</td>
<td>44.532838</td>
<td>8.066837</td>
<td>323.480153</td>
<td>237.165000</td>
<td>26.44</td>
<td>0.624965</td>
<td>0.527351</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2022-03-04</td>
<td>04/03/2022</td>
<td>vaca</td>
<td>14530</td>
<td>13.312</td>
<td>4.002</td>
<td>3.673</td>
<td>14990</td>
<td>1.032</td>
<td>13.25</td>
<td>3.79</td>
<td>...</td>
<td>33.4176</td>
<td>99.032424</td>
<td>90.465412</td>
<td>32.992143</td>
<td>7.939619</td>
<td>300.911547</td>
<td>273.916843</td>
<td>24.78</td>
<td>0.647009</td>
<td>0.545988</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-03-25</td>
<td>25/03/2022</td>
<td>vaca</td>
<td>12633</td>
<td>12.856</td>
<td>3.889</td>
<td>3.372</td>
<td>13012</td>
<td>1.030</td>
<td>12.89</td>
<td>3.69</td>
<td>...</td>
<td>20.5260</td>
<td>99.198926</td>
<td>87.376450</td>
<td>30.486783</td>
<td>8.367846</td>
<td>308.773505</td>
<td>268.607846</td>
<td>23.47</td>
<td>0.661669</td>
<td>0.566174</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2022-04-01</td>
<td>01/04/2022</td>
<td>vaca</td>
<td>15430</td>
<td>13.151</td>
<td>3.886</td>
<td>3.218</td>
<td>15947</td>
<td>1.033</td>
<td>11.88</td>
<td>3.71</td>
<td>...</td>
<td>23.8000</td>
<td>90.245873</td>
<td>95.385293</td>
<td>35.258701</td>
<td>9.112571</td>
<td>338.076400</td>
<td>275.199657</td>
<td>26.25</td>
<td>0.622248</td>
<td>0.537526</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-04-08</td>
<td>08/04/2022</td>
<td>vaca</td>
<td>15930</td>
<td>13.103</td>
<td>4.022</td>
<td>3.396</td>
<td>16453</td>
<td>1.033</td>
<td>11.93</td>
<td>3.81</td>
<td>...</td>
<td>37.1450</td>
<td>93.592852</td>
<td>94.249329</td>
<td>37.490805</td>
<td>8.415857</td>
<td>320.644143</td>
<td>271.832174</td>
<td>25.62</td>
<td>0.633948</td>
<td>0.539457</td>
</tr>
</tbody>
</table>

<p>5 rows × 34 columns</p>
</div>
</div>
</div>
<div id="343cf6f8" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear paleta de colores por receta</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>recetas <span class="op">=</span> df[<span class="st">'receta'</span>].unique()</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>palette <span class="op">=</span> sns.color_palette(<span class="st">'tab10'</span>, n_colors<span class="op">=</span><span class="bu">len</span>(recetas))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>color_dict <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(recetas, palette))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>df[df[<span class="st">'receta'</span>] <span class="op">!=</span> <span class="st">'i+D'</span>], </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                x<span class="op">=</span><span class="st">'consumo_mg_kg'</span>, </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>                y<span class="op">=</span><span class="st">'consumo_mp_kg'</span>, </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                hue<span class="op">=</span><span class="st">'receta'</span>, </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                palette <span class="op">=</span> color_dict,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>                s<span class="op">=</span><span class="dv">80</span>, </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>                <span class="co"># edgecolor = 'black',</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>                alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular y dibujar centroides</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>centroides_consumos_materia <span class="op">=</span> df.groupby(<span class="st">'receta'</span>)[[<span class="st">'consumo_mg_kg'</span>, <span class="st">'consumo_mp_kg'</span>]].median()</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> receta <span class="kw">in</span> recetas:</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    centro <span class="op">=</span> centroides_consumos_materia.loc[receta]</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    plt.scatter(</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>        centro[<span class="st">'consumo_mg_kg'</span>],</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>        centro[<span class="st">'consumo_mp_kg'</span>],</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>color_dict[receta],</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>        marker<span class="op">=</span><span class="st">'X'</span>,</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>        s<span class="op">=</span><span class="dv">150</span>,</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">'black'</span>,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="ss">f'Centroide </span><span class="sc">{</span>receta<span class="sc">}</span><span class="ss">'</span></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Consumos de MG y MP por kg de queso'</span>)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Consumo MG/kg queso'</span>)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Consumo MP/kg queso ESM'</span>)</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">'Receta'</span>) <span class="co"># Mostrar leyenda para la especie</span></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Mover la leyenda fuera del gráfico</span></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>plt.legend(bbox_to_anchor<span class="op">=</span>(<span class="fl">1.05</span>, <span class="dv">1</span>), loc<span class="op">=</span><span class="st">'upper left'</span>, borderaxespad<span class="op">=</span><span class="fl">0.</span>)</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="100-rendimientos_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./090-balance-materia.html" class="pagination-link" aria-label="El balance de materia">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">El balance de materia</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./105-valoracion-bmat.html" class="pagination-link" aria-label="La valoración económica del balance de materia y los rendimientos.">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">La valoración económica del balance de materia y los rendimientos.</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>